In [15]:
import pandas as pd

df = pd.read_csv('data.csv', keep_default_na=False, na_values=[''])
# df.drop(columns=['totalByStateMean', 'totalByRegionMean', 'closedByStateMean', 'closedByRegionMean'], inplace=True)
df

,name,yearEstablished,state,stateAbbreviation,locationType,locationTypeKind,typeOwned,typeProfit,level,hasUndergraduate,...,closedByRegion_2024,totalByState_2025,closedByState_2025,totalByRegion_2025,closedByRegion_2025,regionUnemploymentRate,totalByStateMean,totalByRegionMean,closedByStateMean,closedByRegionMean
0,Alderson Broaddus University,1871,West Virginia,WV,Rural,Distant,Private,Nonprofit,4-year,True,...,4,67,0,2045,2,3.6,68.50,2052.50,0.50,1.50
1,Alliance University (Formerly Nyack College),1882,New York,NY,City,Large,Private,Nonprofit,4-year,True,...,8,406,0,1146,0,4.1,412.50,1160.25,1.00,2.25
2,Ancilla College,1937,Indiana,IN,Rural,Distant,Private,Nonprofit,2-year,True,...,9,100,0,1301,4,4.1,101.50,1318.25,0.25,3.25
3,Becker College,1784,Massachusetts,MA,City,Midsize,Private,Nonprofit,4-year,True,...,8,141,0,1146,0,4.1,142.75,1160.25,0.50,2.25
4,Bloomfield College,1868,New Jersey,NJ,Suburb,Large,Private,Nonprofit,4-year,True,...,8,143,0,1146,0,4.1,144.00,1160.25,0.25,2.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Eastern Nazarene College,1900,Massachusetts,MA,Suburb,Large,Private,Nonprofit,4-year,True,...,8,141,0,1146,0,4.1,142.75,1160.25,0.50,2.25
61,Cox College,1907,Missouri,MO,City,Midsize,Private,Nonprofit,4-year,True,...,9,136,2,1301,4,4.1,136.25,1318.25,0.25,3.25
62,University of Wisconsin–Platteville Richland,1967,Wisconsin,WI,Town,Distant,Public,Nonprofit,4-year,True,...,9,82,1,1301,4,4.1,87.25,1318.25,0.50,3.25
63,Maryland University of Integrative Health,1974,Maryland,MD,Suburb,Large,Private,Nonprofit,graduate school,False,...,4,77,1,2045,2,3.6,77.00,2052.50,0.00,1.50
64,B. H. Carroll Theological Seminary,2004,Texas,TX,City,Midsize,Private,Nonprofit,seminary,False,...,4,384,1,2045,2,3.6,384.00,2052.50,0.00,1.50

In [ ]:
years = [2020, 2021, 2022, 2023, 2024, 2025]

# df['totalClosedByState'] = 0
# df['totalClosedByRegion'] = 0

# for year in years:
#     df['totalClosedByState'] += df[f'closedByState_{year}']
#     df[f'totalByState_{year}'] = df[f'totalByState_{year}'] - df['totalClosedByState']

#     df['totalClosedByRegion'] += df[f'closedByRegion_{year}']
#     df[f'totalByRegion_{year}'] = df[f'totalByRegion_{year}'] - df['totalClosedByRegion']

# df = df.drop(columns=['totalClosedByState'])
# df = df.drop(columns=['totalClosedByRegion'])

df['closedNextYearByState'] = 0
df['closedNextYearByRegion'] = 0

for year in years:
    df[f'totalByState_{year}'] = df[f'totalByState_{year}'] - df['closedNextYearByState']
    df['closedNextYearByState'] += df[f'closedByState_{year}']

    df[f'totalByRegion_{year}'] = df[f'totalByRegion_{year}'] - df['closedNextYearByRegion']
    df['closedNextYearByRegion'] += df[f'closedByRegion_{year}']

df = df.drop(columns=['closedNextYearByState'])
df = df.drop(columns=['closedNextYearByRegion'])

df

,name,yearEstablished,state,stateAbbreviation,locationType,locationTypeKind,typeOwned,typeProfit,level,hasUndergraduate,...,closedByRegion_2023,totalByState_2024,closedByState_2024,totalByRegion_2024,closedByRegion_2024,totalByState_2025,closedByState_2025,totalByRegion_2025,closedByRegion_2025,regionUnemploymentRate
0,Alderson Broaddus University,1871,West Virginia,WV,Rural,Distant,Private,Nonprofit,4-year,True,...,1,67,0,2049,4,67,0,2045,2,3.6
1,Alliance University (Formerly Nyack College),1882,New York,NY,City,Large,Private,Nonprofit,4-year,True,...,4,409,3,1154,8,406,0,1146,0,4.1
2,Ancilla College,1937,Indiana,IN,Rural,Distant,Private,Nonprofit,2-year,True,...,6,101,1,1310,9,100,0,1301,4,4.1
3,Becker College,1784,Massachusetts,MA,City,Midsize,Private,Nonprofit,4-year,True,...,4,142,1,1154,8,141,0,1146,0,4.1
4,Bloomfield College,1868,New Jersey,NJ,Suburb,Large,Private,Nonprofit,4-year,True,...,4,143,0,1154,8,143,0,1146,0,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Eastern Nazarene College,1900,Massachusetts,MA,Suburb,Large,Private,Nonprofit,4-year,True,...,4,142,1,1154,8,141,0,1146,0,4.1
61,Cox College,1907,Missouri,MO,City,Midsize,Private,Nonprofit,4-year,True,...,6,136,0,1310,9,136,2,1301,4,4.1
62,University of Wisconsin–Platteville Richland,1967,Wisconsin,WI,Town,Distant,Public,Nonprofit,4-year,True,...,6,86,4,1310,9,82,1,1301,4,4.1
63,Maryland University of Integrative Health,1974,Maryland,MD,Suburb,Large,Private,Nonprofit,graduate school,False,...,1,77,0,2049,4,77,1,2045,2,3.6
64,B. H. Carroll Theological Seminary,2004,Texas,TX,City,Midsize,Private,Nonprofit,seminary,False,...,1,384,0,2049,4,384,1,2045,2,3.6

In [11]:
df['totalByStateMean'] = df[['totalByState_2020', 'totalByState_2021', 'totalByState_2022', 'totalByState_2023']].mean(axis=1)
df['totalByRegionMean'] = df[['totalByRegion_2020', 'totalByRegion_2021', 'totalByRegion_2022', 'totalByRegion_2023']].mean(axis=1)
df['closedByStateMean'] = df[['closedByState_2020', 'closedByState_2021', 'closedByState_2022', 'closedByState_2023']].mean(axis=1)
df['closedByRegionMean'] = df[['closedByRegion_2020', 'closedByRegion_2021', 'closedByRegion_2022', 'closedByRegion_2023']].mean(axis=1)
df.to_csv('data.csv', index=False)

In [12]:
# unique states in df['state']
unique_states = df['state'].unique()
print(len(unique_states))

28

In [13]:
df

,name,yearEstablished,state,stateAbbreviation,locationType,locationTypeKind,typeOwned,typeProfit,level,hasUndergraduate,...,closedByRegion_2024,totalByState_2025,closedByState_2025,totalByRegion_2025,closedByRegion_2025,regionUnemploymentRate,totalByStateMean,totalByRegionMean,closedByStateMean,closedByRegionMean
0,Alderson Broaddus University,1871,West Virginia,WV,Rural,Distant,Private,Nonprofit,4-year,True,...,4,67,0,2045,2,3.6,68.50,2052.50,0.50,1.50
1,Alliance University (Formerly Nyack College),1882,New York,NY,City,Large,Private,Nonprofit,4-year,True,...,8,406,0,1146,0,4.1,412.50,1160.25,1.00,2.25
2,Ancilla College,1937,Indiana,IN,Rural,Distant,Private,Nonprofit,2-year,True,...,9,100,0,1301,4,4.1,101.50,1318.25,0.25,3.25
3,Becker College,1784,Massachusetts,MA,City,Midsize,Private,Nonprofit,4-year,True,...,8,141,0,1146,0,4.1,142.75,1160.25,0.50,2.25
4,Bloomfield College,1868,New Jersey,NJ,Suburb,Large,Private,Nonprofit,4-year,True,...,8,143,0,1146,0,4.1,144.00,1160.25,0.25,2.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Eastern Nazarene College,1900,Massachusetts,MA,Suburb,Large,Private,Nonprofit,4-year,True,...,8,141,0,1146,0,4.1,142.75,1160.25,0.50,2.25
61,Cox College,1907,Missouri,MO,City,Midsize,Private,Nonprofit,4-year,True,...,9,136,2,1301,4,4.1,136.25,1318.25,0.25,3.25
62,University of Wisconsin–Platteville Richland,1967,Wisconsin,WI,Town,Distant,Public,Nonprofit,4-year,True,...,9,82,1,1301,4,4.1,87.25,1318.25,0.50,3.25
63,Maryland University of Integrative Health,1974,Maryland,MD,Suburb,Large,Private,Nonprofit,graduate school,False,...,4,77,1,2045,2,3.6,77.00,2052.50,0.00,1.50
64,B. H. Carroll Theological Seminary,2004,Texas,TX,City,Midsize,Private,Nonprofit,seminary,False,...,4,384,1,2045,2,3.6,384.00,2052.50,0.00,1.50

In [14]:
# sum all the closedByState columns
x= df[['closedByState_2020', 'closedByState_2021', 'closedByState_2022', 'closedByState_2023', 'closedByState_2024', 'closedByState_2025']].sum(axis=1)
print(x)

0     2
1     7
2     2
3     3
4     1
     ..
60    3
61    3
62    7
63    1
64    1
Length: 65, dtype: int64