In [287]:
import pandas as pd
import numpy as np
import openpyxl
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
df = pd.read_excel("sepehr_colleges.xlsx")
df

,index,UID,name,yearEstablished,state,stateAbbr,zip,locationType,locationTypeKind,Public/ Private,...,reasonPandemic,reasonMutualBenefit,reasonForClosure,EndowmentMedian2018,EndowmentMedian2019,EndowmentMedian2020,EndowmentMedian2021,EndowmentMedian2022,EndowmentMedian2023,EndowmentMedian2024
0,0,237118.0,Alderson Broaddus University,1871,West Virginia,NaN,26416,Rural,Distant,Private,...,0,0,Financial,18150386.0,17367369.0,18456342.0,18685108.0,16256321.0,0.000000e+00,0.0
1,1,194161.0,Alliance University (Formerly Nyack College),1882,New York,NaN,10004,City,Large,Private,...,0,0,Accreditation Issues,4255808.0,4393633.0,4577611.0,3736796.0,622193.0,0.000000e+00,0.0
2,2,241100.0,American University of Puerto Rico,1963,Puerto Rico,NaN,960,City,Midsize,Private,...,0,0,Financial,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,497833.0,Ancilla College,1937,Indiana,NaN,46513,Rural,Distant,Private,...,0,1,Mutual Benefit,4110469.0,4351295.0,4394680.0,0.0,0.0,0.000000e+00,0.0
4,4,164720.0,Becker College,1784,Massachusetts,NaN,1609,City,Midsize,Private,...,1,0,Pandemic; Enrollment,4962182.0,5116037.0,5024459.0,0.0,0.0,0.000000e+00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,61,165644.0,Eastern Nazarene College,1900,Massachusetts,NaN,2170,Suburb,Large,Private,...,0,0,Financial,19548765.0,19545720.0,18753406.0,19431518.0,19100262.0,1.937957e+07,0.0
62,62,176770.0,Cox College,1907,Missouri,NaN,65802,City,Midsize,Private,...,0,0,Financial,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,63,240462.0,University of Wisconsin–Platteville Richland,1967,Wisconsin,NaN,53581,Town,Distant,Public,...,0,0,Enrollment,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,64,164085.0,Maryland University of Integrative Health,1974,Maryland,NaN,20723,Suburb,Large,Private,...,0,1,Mutual Benefit,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,65,NaN,B. H. Carroll Theological Seminary,2004,Texas,NaN,76010,City,Midsize,Private,...,0,1,Mutual Benefit,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
stateAbbri = {"Alabama": "AL",
             "Alaska": "AK",
             "Arizona": "AZ",
             "Arkansas": "AR",
             "California": "CA",
             "Colorado": "CO",
             "Connecticut": "CT",
             "Delaware": "DE",
             "Florida": "FL",
             "Georgia": "GA",
             "Hawaii": "HI",
             "Idaho": "ID",
             "Illinois": "IL",
             "Indiana": "IN",
             "Iowa": "IA",
             "Kansas": "KS",
             "Kentucky": "KY",
             "Louisiana": "LA",
             "Maine": "ME",
             "Maryland": "MD",
             "Massachusetts": "MA",
             "Michigan": "MI",
             "Minnesota": "MN",
             "Mississippi": "MS",
             "Missouri": "MO",
             "Montana": "MT",
             "Nebraska": "NE",
             "Nevada": "NV",
             "New Hampshire": "NH",
             "New Jersey": "NJ",
             "New Mexico": "NM",
             "New York": "NY",
             "North Carolina": "NC",
             "North Dakota": "ND",
             "Ohio": "OH",
             "Oklahoma": "OK",
             "Oregon": "OR",
             "Pennsylvania": "PA",
             "Rhode Island": "RI",
             "South Carolina": "SC",
             "South Dakota": "SD",
             "Tennessee": "TN",
             "Texas": "TX",
             "Utah": "UT",
             "Vermont": "VT",
             "Virginia": "VA",
             "Washington": "WA",
             "West Virginia": "WV",
             "Wisconsin": "WI",
             "Wyoming": "WY",   
             "District of Columbia": "DC",
             "American Samoa": "AS",
             "Guam": "GU",
             "Northern Mariana Islands": "MP",
             "Puerto Rico": "PR",
             "U.S. Virgin Islands": "VI",
             "Federated States of Micronesia": "FM",
             "Marshall Islands": "MH",
             "Palau": "PW",
             "Armed Forces Americas": "AA",
             "Armed Forces Europe": "AE",
             "Armed Forces Pacific": "AP",
             "Alberta": "AB",
             "British Columbia": "BC"}

df['stateAbbr'] = df['state'].map(stateAbbri)

In [62]:
for x in ['yearEstablished', 'zip', 'UID', 'index', 'totalEnrollment', 'mergingInstitutionPopulation', 'mergingInstitutionZip']:
    df[x] = pd.to_numeric(df[x], errors='coerce').astype('Int64')

for x in df.columns:
    if x.startswith('Endowment'):
        df[x] = pd.to_numeric(df[x], errors='coerce').astype('float')

In [63]:
for x in ['mergingInstitution',
        #   'mergingInstitutionPopulation',
          'mergingInstitutionType',
        #   'mergingInstitutionZip',
          'mergingInstitutionLocationType',
          'mergingInstitutionReligiousAffiliation',
          'specialDemographic',
          'religionAffiliation']:
    df[x] = df[x].fillna("NA").astype(str)

In [ ]:
df.to_excel("sepehr_colleges_cleaned.xlsx", index=False)

In [102]:
states = pd.read_excel("sepehr_states.xlsx")
states

                   state stateAbbr     region
0                Alabama        AL      South
1                 Alaska        AK       West
2                Arizona        AZ       West
3               Arkansas        AR      South
4             California        CA       West
5               Colorado        CO       West
6            Connecticut        CT  Northeast
7               Delaware        DE      South
8   District of Columbia        DC      South
9                Florida        FL      South
10               Georgia        GA      South
11                Hawaii        HI       West
12                 Idaho        ID       West
13              Illinois        IL    Midwest
14               Indiana        IN    Midwest
15                  Iowa        IA    Midwest
16                Kansas        KS    Midwest
17              Kentucky        KY      South
18             Louisiana        LA      South
19                 Maine        ME  Northeast
20              Maryland        MD      South
21         Massachusetts        MA  Northeast
22              Michigan        MI    Midwest
23             Minnesota        MN    Midwest
24           Mississippi        MS      South
25              Missouri        MO    Midwest
26               Montana        MT       West
27              Nebraska        NE    Midwest
28                Nevada        NV       West
29         New Hampshire        NH  Northeast
30            New Jersey        NJ  Northeast
31            New Mexico        NM       West
32              New York        NY  Northeast
33        North Carolina        NC      South
34          North Dakota        ND    Midwest
35                  Ohio        OH    Midwest
36              Oklahoma        OK      South
37                Oregon        OR       West
38          Pennsylvania        PA  Northeast
39          Rhode Island        RI  Northeast
40        South Carolina        SC      South
41          South Dakota        SD    Midwest
42             Tennessee        TN      South
43                 Texas        TX      South
44                  Utah        UT       West
45               Vermont        VT  Northeast
46              Virginia        VA      South
47            Washington        WA       West
48         West Virginia        WV      South
49             Wisconsin        WI    Midwest
50               Wyoming        WY       West

In [70]:
states['stateAbbr'] = states['state'].map(stateAbbri)
states.to_excel("sepehr_states.xlsx", index=False)

In [ ]:
df = pd.read_csv("natality.txt", sep='\t', header=0, quotechar='"')

df['% of Total Births'] = df['% of Total Births'].str.replace('%', '', regex=False).astype(float)

df['Census Region of Residence'] = df['Census Region of Residence'].str.replace('Census Region ', '', regex=False)
df['Census Region of Residence'] = df['Census Region of Residence'].str[2:]

df = df.drop(columns=['State of Residence Code', 'Census Region of Residence Code'])

In [86]:
df.to_excel("natality_cleaned.xlsx", index=False)

In [94]:
stateRegions = {
    "Alabama": "South",
    "Alaska": "West",
    "Arizona": "West",
    "Arkansas": "South",
    "California": "West",
    "Colorado": "West",
    "Connecticut": "Northeast",
    "Delaware": "South",
    "Florida": "South",
    "Georgia": "South",
    "Hawaii": "West",
    "Idaho": "West",
    "Illinois": "Midwest",
    "Indiana": "Midwest",
    "Iowa": "Midwest",
    "Kansas": "Midwest",
    "Kentucky": "South",
    "Louisiana": "South",
    "Maine": "Northeast",
    "Maryland": "South",
    "Massachusetts": "Northeast",
    "Michigan": "Midwest",
    "Minnesota": "Midwest",
    "Mississippi": "South",
    "Missouri": "Midwest",
    "Montana": "West",
    "Nebraska": "Midwest",
    "Nevada": "West",
    "New Hampshire": "Northeast",
    "New Jersey": "Northeast",
    "New Mexico": "West",
    "New York": "Northeast",
    "North Carolina": "South",
    "North Dakota": "Midwest",
    "Ohio": "Midwest",
    "Oklahoma": "South",
    "Oregon": "West",
    "Pennsylvania": "Northeast",
    "Rhode Island": "Northeast",
    "South Carolina": "South",
    "South Dakota": "Midwest",
    "Tennessee": "South",
    "Texas": "South",
    "Utah": "West",
    "Vermont": "Northeast",
    "Virginia": "South",
    "Washington": "West",
    "West Virginia": "South",
    "Wisconsin": "Midwest",
    "Wyoming": "West",
    "District of Columbia": "South",
    "American Samoa": "West",
    "Guam": "West",
    "Northern Mariana Islands": "West",
    "Puerto Rico": "South"
}

states['region'] = states['state'].map(stateRegions)
states.to_excel("sepehr_states.xlsx", index=False)

In [ ]:
nat = pd.read_excel("natality_cleaned.xlsx")
nat.to_excel("natality.xlsx", index=False)

,Census Region of Residence,State of Residence,Births,Total Population,Birth Rate,Female Population,Fertility Rate,% of Total Births
0,Northeast,Connecticut,208004,21543936,9.65,4081181,50.97,0.94
1,Northeast,Maine,71355,8186066,8.72,1430071,49.90,0.32
2,Northeast,Massachusetts,409468,41656322,9.83,8419406,48.63,1.85
3,Northeast,New Hampshire,72263,8268721,8.74,1497455,48.26,0.33
4,Northeast,Rhode Island,61320,6459107,9.49,1273562,48.15,0.28
5,Northeast,Vermont,31691,3813733,8.31,704655,44.97,0.14
6,Northeast,New Jersey,604153,54492751,11.09,10293179,58.69,2.74
7,Northeast,New York,1279243,117416826,10.89,23255110,55.01,5.79
8,Northeast,Pennsylvania,790421,77290050,10.23,14466075,54.64,3.58
9,Northeast,TOTAL,3527918,339127512,10.40,65420694,53.93,15.98
10,Midwest,Illinois,803600,75803621,10.60,14934897,53.81,3.64
11,Midwest,Indiana,479716,40680271,11.79,7927380,60.51,2.17
12,Midwest,Michigan,628417,60071512,10.46,11321208,55.51,2.85
13,Midwest,Ohio,783704,70393769,11.13,13365288,58.64,3.55
14,Midwest,Wisconsin,369546,35168059,10.51,6601801,55.98,1.67
15,Midwest,Iowa,220941,19075376,11.58,3613047,61.15,1.00
16,Midwest,Kansas,209203,17550902,11.92,3396536,61.59,0.95
17,Midwest,Minnesota,386969,34070642,11.36,6552584,59.06,1.75
18,Midwest,Missouri,420242,36957728,11.37,7119267,59.03,1.90
19,Midwest,Nebraska,147599,11711222,12.60,2272581,64.95,0.67
20,Midwest,North Dakota,60475,4625583,13.07,906297,66.73,0.27
21,Midwest,South Dakota,68073,5384129,12.64,992778,68.57,0.31
22,Midwest,TOTAL,4578485,411492814,11.13,79003664,57.95,20.73
23,South,Delaware,63300,5981414,10.58,1108192,57.12,0.29
24,South,District of Columbia,51796,4141845,12.51,1112736,46.55,0.23
25,South,Florida,1313318,131147051,10.01,23772622,55.24,5.95
26,South,Georgia,750339,64588584,11.62,13290576,56.46,3.40
27,South,Maryland,412473,36654242,11.25,7192645,57.35,1.87
28,South,North Carolina,716519,63558153,11.27,12498057,57.33,3.24
29,South,South Carolina,342145,31297775,10.93,5998759,57.04,1.55
30,South,Virginia,576125,51685358,11.15,10227966,56.33,2.61
31,South,West Virginia,104440,10710952,9.75,1888053,55.32,0.47
32,South,Alabama,348084,29935229,11.63,5816314,59.85,1.58
33,South,Kentucky,315172,26961184,11.69,5122694,61.52,1.43
34,South,Mississippi,213399,17759177,12.02,3496766,61.03,0.97
35,South,Tennessee,486893,41639064,11.69,8166631,59.62,2.21
36,South,Arkansas,215533,18201411,11.84,3505626,61.48,0.98
37,South,Louisiana,344727,27742127,12.43,5509902,62.56,1.56
38,South,Oklahoma,291217,23941096,12.16,4723856,61.65,1.32
39,South,Texas,2275693,177119299,12.85,36976634,61.54,10.31
40,South,TOTAL,8821173,763063961,11.56,150408029,58.65,39.95
41,West,Arizona,471604,43938621,10.73,8478149,55.63,2.14
42,West,Colorado,374074,34791624,10.75,7170448,52.17,1.69
43,West,Idaho,132214,11172868,11.83,2177962,60.71,0.60
44,West,Montana,66867,6571610,10.18,1214373,55.06,0.30
45,West,Nevada,203080,18768746,10.82,3675214,55.26,0.92
46,West,New Mexico,131858,12642168,10.43,2415538,54.59,0.60
47,West,Utah,277236,19753451,14.03,4341180,63.86,1.26
48,West,Wyoming,37531,3483065,10.78,651779,57.58,0.17
49,West,Alaska,57118,4399803,12.98,867023,65.88,0.26
50,West,California,2561478,235669717,10.87,48016877,53.35,11.60
51,West,Hawaii,95517,8560256,11.16,1571913,60.76,0.43
52,West,Oregon,242571,25369607,9.56,4987114,48.64,1.10
53,West,Washington,502242,46181454,10.88,9240808,54.35,2.27
54,West,TOTAL,5153390,471302990,10.93,94808378,54.36,23.34
55,USA,TOTAL,22080966,1984987277,11.12,389640765,56.67,100.00

In [ ]:
# make a stateAbbr column in nat
nat['stateAbbr'] = nat['State of Residence'].map(stateAbbri)
nat.to_excel("natality.xlsx", index=False)

In [106]:
states = pd.read_excel("sepehr_states.xlsx")
nat = pd.read_excel("natality.xlsx")

states = states.merge(nat, on='stateAbbr', how='outer')
states = states.drop(columns=['Census Region of Residence', 'State of Residence'])
states.to_excel("sepehr_states_1.xlsx", index=False)

In [128]:
reg = pd.read_csv("sepehr_regions.csv")

reg = reg.rename(columns={
                          'Births': 'regionBirths', 
                          'Total Population': 'regionPopulation', 
                          'Birth Rate': 'regionBirthRate',
                          'Female Population': 'regionFemalePopulation', 
                          'Fertility Rate': 'regionFertilityRate',
                          '% of Total Births': 'regionPercentOfTotalBirths'})
mergetest = states.merge(reg, on='region', how='outer')
mergetest = mergetest.drop(index=[0, 52, 53, 54, 55, 56])

# order the states in alphabetical order
mergetest = mergetest.sort_values(by='state')
mergetest.to_excel("sepehr_states.xlsx", index=False)

In [130]:
inc = pd.read_excel("incomes.xlsx")
inc

,STATE,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3,2019:Q4,2020:Q1,...,2022:Q3,2022:Q4,2023:Q1,2023:Q2,2023:Q3,2023:Q4,2024:Q1,2024:Q2,2024:Q3,2024:Q4
0,Alabama,40825,41094,41404,41938,42579,42884,43118,43372,43931,...,52080,52798,53411,53847,54308,54869,55930,56395,56893,57551
1,Alaska,58076,58490,59483,59869,60094,60354,60680,60820,60261,...,69367,70276,69651,70925,71981,72593,74604,74705,75469,76299
2,Arizona,44628,44961,45539,45981,47035,47498,47930,48336,48912,...,59350,60255,61276,62190,62408,62804,64225,64432,64364,64904
3,Arkansas,42434,42762,43230,43670,43223,43473,43940,44263,44862,...,55969,57031,57509,57487,57548,57880,58869,59158,60090,60549
4,California,59735,60612,61457,62167,63291,63964,64328,65254,66306,...,77083,78356,79505,80520,81150,81691,84393,85201,85808,86834
5,Colorado,56452,57262,58297,59236,60763,60992,61643,61711,63076,...,78441,77705,78580,79551,79948,80840,82080,82838,82634,83374
6,Connecticut,71081,71679,72868,73045,73957,74045,73961,74641,74054,...,85572,86626,87884,89029,89592,90596,92496,93030,93408,94192
7,Delaware,51725,52313,53075,53504,53520,53795,53917,53801,54275,...,64766,65680,65784,66470,66815,67135,68349,69390,69317,70141
8,District of Columbia,80946,81715,83021,83549,83116,83648,83777,84046,84590,...,100848,101891,104040,105699,105600,106379,107908,108577,108103,108848
9,Florida,50086,50560,51364,52049,53095,53504,53735,54246,54623,...,64977,65874,67037,67628,67958,68695,70077,70155,70521,71040
10,Georgia,45853,46325,47017,47261,48149,48455,48645,48881,49157,...,57672,58262,58647,59521,59954,60663,61923,62192,62368,63154
11,Hawaii,51061,51439,51685,52079,53335,53654,54101,54616,54941,...,62789,64786,64623,65663,66161,66995,68269,69686,69789,70454
12,Idaho,42652,43005,43330,43942,45204,45697,46117,46440,47332,...,57479,58274,58693,58779,59271,59950,60954,61833,62119,62471
13,Illinois,55132,55880,56370,56903,57184,57427,57979,58328,58924,...,68943,69816,70531,71434,71996,72744,73646,73965,74282,75030
14,Indiana,46049,46288,46688,47188,47809,48086,48440,48727,49550,...,59023,60165,60126,60872,61338,61943,63529,63902,63678,64153
15,Iowa,47973,48452,48803,49815,49297,49129,50030,50237,50070,...,62433,62643,62253,62219,62766,62900,63153,63287,63682,64243
16,Kansas,49399,50005,50547,51172,51616,51850,52388,52709,52943,...,62910,63625,64814,65614,66336,66637,67229,67971,68170,68862
17,Kentucky,41189,41590,41755,42085,43045,43310,43552,43938,44472,...,52795,53375,54181,54857,55456,55709,57168,57285,57527,58200
18,Louisiana,44716,45343,45695,46069,46729,46889,47059,47374,47575,...,56117,56735,57809,58237,58821,59662,60867,61225,61459,61827
19,Maine,47115,47551,47977,48226,49424,49763,50102,50615,51423,...,62450,62792,64542,64357,65027,65826,67585,67855,68193,68918
20,Maryland,59189,59690,60246,60503,61227,61714,61753,62159,62266,...,71678,72524,73521,74623,75421,76054,78093,78337,78529,79325
21,Massachusetts,68245,68799,69520,70234,72195,72334,72320,72658,73566,...,85692,88976,88353,89588,90006,90904,93391,93817,93922,94849
22,Michigan,46671,46917,47266,47508,48091,48492,48655,49057,49435,...,58276,58800,60021,60712,61139,61495,62715,63304,63129,63816
23,Minnesota,55151,55881,56507,57276,57462,57637,58162,58371,58830,...,70670,71078,71382,72076,72712,73223,74378,74405,75094,75971
24,Mississippi,37071,37479,37705,38202,38785,38895,39297,39598,40058,...,47454,47989,48826,49450,49644,50451,51261,51837,52194,52757
25,Missouri,45796,46639,46877,47388,47760,48076,48658,49173,49802,...,59668,60469,61493,62296,62698,63390,64275,64500,64809,65415
26,Montana,46504,46993,47311,47987,49011,49277,49968,50258,50249,...,61985,62723,64200,64804,65286,66087,66974,67277,67754,68444
27,Nebraska,50476,50864,51439,52957,52754,52860,53933,54481,54020,...,67809,68661,70448,70855,71264,71404,71336,71884,71816,72496
28,Nevada,48716,48879,49382,50122,51421,51834,51992,52552,52941,...,62885,63894,64504,65492,66148,66952,68439,68543,68607,69175
29,New Hampshire,59798,60014,60633,60847,63832,63840,63942,64115,65539,...,75575,76697,77412,78744,79230,80304,82459,82702,82727,83674
30,New Jersey,63255,63788,64598,65121,67192,67457,67552,67822,68369,...,78003,78782,80103,80939,81802,82260,83460,84015,84139,84909
31,New Mexico,40314,40730,41233,41543,42569,43001,43487,43771,44550,...,54367,53949,54467,55145,55130,55861,57023,57576,57766,58286
32,New York,63330,63986,64654,64953,65768,66492,66595,66981,67342,...,77748,79182,79743,81420,82431,82699,84520,85565,86007,87061
33,North Carolina,45226,45771,46250,46928,47831,48226,48488,48915,49685,...,59065,59973,60805,61125,61778,62594,64019,64547,65173,65747
34,North Dakota,53653,54635,55521,56844,56402,55931,57115,57212,58162,...,72198,72172,71676,71675,71561,71393,70999,70865,70677,71453
35,Ohio,47112,47529,48076,48542,48971,49202,49492,49907,50272,...,58701,59376,60190,60973,61634,62342,63440,64197,64312,65011
36,Oklahoma,45333,45715,46271,46733,48213,47980,48179,48272,48476,...,58865,59358,59807,60076,60576,61145,62037,62642,62694,63300
37,Oregon,49343,49893,50581,51010,51588,51919,52216,53024,54064,...,64219,65166,66487,67211,67962,68276,69746,70762,70795,71524
38,Pennsylvania,53550,54083,54913,55346,55681,56027,56164,56634,57048,...,66016,66580,67777,68386,68782,69555,70279,70806,71366,72220
39,Rhode Island,51741,51870,52137,52847,54902,55086,54973,55473,56445,...,64538,64929,66049,66651,67609,67938,69535,69636,70003,70693
40,South Carolina,43136,43525,43995,44573,45723,45965,46245,46637,46579,...,54642,55827,56602,56668,57428,58042,59462,59880,60006,60659
41,South Dakota,50773,50865,51301,53283,53730,53569,54928,55416,55847,...,70318,70608,72118,72382,72773,72984,73575,73876,73856,74544
42,Tennessee,45732,46072,46802,47201,48439,48782,49034,49287,50482,...,59443,60264,61110,61712,62297,63045,64193,64972,64921,65596
43,Texas,50365,50969,51714,52272,52840,53113,53377,53681,53146,...,63594,64232,65189,65414,65932,66554,67598,67822,68029,68456
44,Utah,44732,45202,45703,46220,47763,47783,48334,48748,49250,...,61113,62056,62509,63412,64070,64708,66098,66547,66308,66966
45,Vermont,50941,51479,51908,52430,54136,54094,54366,54461,55786,...,63962,65293,65832,66691,66822,67895,69269,70108,70197,70811
46,Virginia,55380,55789,56365,56938,57769,58196,58574,58890,59377,...,70535,71492,72135,73396,73963,75095,76248,76984,77159,78074
47,Washington,58871,59261,60233,60937,62797,63186,63503,64188,65129,...,76085,77204,78741,80313,80813,81800,82950,84107,84077,84802
48,West Virginia,40006,40625,41507,41828,42520,42697,42719,42480,42717,...,50457,51075,51935,52697,52870,53695,54897,55228,54899,55532
49,Wisconsin,49984,50140,50735,51204,51857,52312,52359,52932,53257,...,62518,62898,63733,64381,65049,65848,67037,67245,67777,68347
50,Wyoming,57821,58729,59687,60422,61147,61459,62171,62518,63854,...,77095,78995,80612,81515,82276,83283,84589,85570,86359,87284

In [141]:
for x in [2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    inc[f'median{x}'] = inc[[f'{x}:Q1', f'{x}:Q2', f'{x}:Q3', f'{x}:Q4']].max(axis=1)

for x in [2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    for y in ['Q1', 'Q2', 'Q3', 'Q4']:
        inc = inc.drop(columns=[f'{x}:{y}'])

inc['stateAbbr'] = inc['STATE'].map(stateAbbri)

KeyError: "None of [Index(['2018:Q1', '2018:Q2', '2018:Q3', '2018:Q4'], dtype='object')] are in the [columns]"

In [143]:
inc['stateAbbr'] = inc['STATE'].map(stateAbbri)
inc

,STATE,median2018,median2019,median2020,median2021,median2022,median2023,median2024,stateAbbr
0,Alabama,41938,43372,47828,53279,52798,54869,57551,AL
1,Alaska,59869,60820,64390,68068,70276,72593,76299,AK
2,Arizona,45981,48336,54111,59129,60255,62804,64904,AZ
3,Arkansas,43670,44263,49385,54909,57031,57880,60549,AR
4,California,62167,65254,72352,78893,78356,81691,86834,CA
5,Colorado,59236,61711,65940,72734,78441,80840,83374,CO
6,Connecticut,73045,74641,77771,83235,86626,90596,94192,CT
7,Delaware,53504,53917,57283,62987,65680,67135,70141,DE
8,District of Columbia,83549,84046,92435,99053,101891,106379,108848,DC
9,Florida,52049,54246,58119,64409,65874,68695,71040,FL
10,Georgia,47261,48881,53532,58750,58262,60663,63154,GA
11,Hawaii,52079,54616,59741,63928,64786,66995,70454,HI
12,Idaho,43942,46440,50857,57842,58274,59950,62471,ID
13,Illinois,56903,58328,63173,68959,69816,72744,75030,IL
14,Indiana,47188,48727,53102,59797,60165,61943,64153,IN
15,Iowa,49815,50237,54978,60415,62643,62900,64243,IA
16,Kansas,51172,52709,56926,60655,63625,66637,68862,KS
17,Kentucky,42085,43938,49826,54463,53375,55709,58200,KY
18,Louisiana,46069,47374,53096,57085,56735,59662,61827,LA
19,Maine,48226,50615,57112,61842,62792,65826,68918,ME
20,Maryland,60503,62159,66549,71897,72524,76054,79325,MD
21,Massachusetts,70234,72658,79602,85585,88976,90904,94849,MA
22,Michigan,47508,49057,56065,59953,58800,61495,63816,MI
23,Minnesota,57276,58371,63783,69421,71078,73223,75971,MN
24,Mississippi,38202,39598,45310,50053,47989,50451,52757,MS
25,Missouri,47388,49173,54330,59202,60469,63390,65415,MO
26,Montana,47987,50258,56094,61425,62723,66087,68444,MT
27,Nebraska,52957,54481,58589,64583,68661,71404,72496,NE
28,Nevada,50122,52552,56889,62865,63894,66952,69175,NV
29,New Hampshire,60847,64115,68556,74338,76697,80304,83674,NH
30,New Jersey,65121,67822,71195,78329,78782,82260,84909,NJ
31,New Mexico,41543,43771,48750,53692,54367,55861,58286,NM
32,New York,64953,66981,72301,78501,79182,82699,87061,NY
33,North Carolina,46928,48915,53556,59301,59973,62594,65747,NC
34,North Dakota,56844,57212,62710,66879,72198,71676,71453,ND
35,Ohio,48542,49907,54936,60407,59376,62342,65011,OH
36,Oklahoma,46733,48272,52427,56502,59358,61145,63300,OK
37,Oregon,51010,53024,58255,64964,65166,68276,71524,OR
38,Pennsylvania,55346,56634,62463,66449,66580,69555,72220,PA
39,Rhode Island,52847,55473,61724,65492,64929,67938,70693,RI
40,South Carolina,44573,46637,51305,55928,55827,58042,60659,SC
41,South Dakota,53283,55416,61583,67885,70608,72984,74544,SD
42,Tennessee,47201,49287,53227,59954,60264,63045,65596,TN
43,Texas,52272,53681,56349,62015,64232,66554,68456,TX
44,Utah,46220,48748,53205,59964,62056,64708,66966,UT
45,Vermont,52430,54461,61507,64176,65293,67895,70811,VT
46,Virginia,56938,58890,62910,69013,71492,75095,78074,VA
47,Washington,60937,64188,69647,75611,77204,81800,84802,WA
48,West Virginia,41828,42719,48174,51918,51075,53695,55532,WV
49,Wisconsin,51204,52932,57292,62713,62898,65848,68347,WI
50,Wyoming,60422,62518,67053,72523,78995,83283,87284,WY

In [151]:
states = pd.read_excel("sepehr_states.xlsx")
states

,state,stateAbbr,region,Births,Total Population,Birth Rate,Female Population,Fertility Rate,percentOfTotalBirths,regionBirths,regionPopulation,regionBirthRate,regionFemalePopulation,regionFertilityRate,regionPercentOfTotalBirths,unemploymentRate
0,Alabama,AL,South,348084,29935229,11.63,5816314,59.85,1.58,8821173,763063961,11.56,150408029,58.65,39.95,3.3
1,Alaska,AK,West,57118,4399803,12.98,867023,65.88,0.26,5153390,471302990,10.93,94808378,54.36,23.34,4.7
2,Arizona,AZ,West,471604,43938621,10.73,8478149,55.63,2.14,5153390,471302990,10.93,94808378,54.36,23.34,4.1
3,Arkansas,AR,South,215533,18201411,11.84,3505626,61.48,0.98,8821173,763063961,11.56,150408029,58.65,39.95,3.7
4,California,CA,West,2561478,235669717,10.87,48016877,53.35,11.60,5153390,471302990,10.93,94808378,54.36,23.34,5.3
5,Colorado,CO,West,374074,34791624,10.75,7170448,52.17,1.69,5153390,471302990,10.93,94808378,54.36,23.34,4.8
6,Connecticut,CT,Northeast,208004,21543936,9.65,4081181,50.97,0.94,3527918,339127512,10.40,65420694,53.93,15.98,3.7
7,Delaware,DE,South,63300,5981414,10.58,1108192,57.12,0.29,8821173,763063961,11.56,150408029,58.65,39.95,3.9
8,District of Columbia,DC,South,51796,4141845,12.51,1112736,46.55,0.23,8821173,763063961,11.56,150408029,58.65,39.95,5.8
9,Florida,FL,South,1313318,131147051,10.01,23772622,55.24,5.95,8821173,763063961,11.56,150408029,58.65,39.95,3.7
10,Georgia,GA,South,750339,64588584,11.62,13290576,56.46,3.40,8821173,763063961,11.56,150408029,58.65,39.95,3.6
11,Hawaii,HI,West,95517,8560256,11.16,1571913,60.76,0.43,5153390,471302990,10.93,94808378,54.36,23.34,2.9
12,Idaho,ID,West,132214,11172868,11.83,2177962,60.71,0.60,5153390,471302990,10.93,94808378,54.36,23.34,3.7
13,Illinois,IL,Midwest,803600,75803621,10.60,14934897,53.81,3.64,4578485,411492814,11.13,79003664,57.95,20.73,4.8
14,Indiana,IN,Midwest,479716,40680271,11.79,7927380,60.51,2.17,4578485,411492814,11.13,79003664,57.95,20.73,3.9
15,Iowa,IA,Midwest,220941,19075376,11.58,3613047,61.15,1.00,4578485,411492814,11.13,79003664,57.95,20.73,3.5
16,Kansas,KS,Midwest,209203,17550902,11.92,3396536,61.59,0.95,4578485,411492814,11.13,79003664,57.95,20.73,3.8
17,Kentucky,KY,South,315172,26961184,11.69,5122694,61.52,1.43,8821173,763063961,11.56,150408029,58.65,39.95,5.2
18,Louisiana,LA,South,344727,27742127,12.43,5509902,62.56,1.56,8821173,763063961,11.56,150408029,58.65,39.95,4.4
19,Maine,ME,Northeast,71355,8186066,8.72,1430071,49.90,0.32,3527918,339127512,10.40,65420694,53.93,15.98,3.5
20,Maryland,MD,South,412473,36654242,11.25,7192645,57.35,1.87,8821173,763063961,11.56,150408029,58.65,39.95,3.1
21,Massachusetts,MA,Northeast,409468,41656322,9.83,8419406,48.63,1.85,3527918,339127512,10.40,65420694,53.93,15.98,4.6
22,Michigan,MI,Midwest,628417,60071512,10.46,11321208,55.51,2.85,4578485,411492814,11.13,79003664,57.95,20.73,5.5
23,Minnesota,MN,Midwest,386969,34070642,11.36,6552584,59.06,1.75,4578485,411492814,11.13,79003664,57.95,20.73,3.2
24,Mississippi,MS,South,213399,17759177,12.02,3496766,61.03,0.97,8821173,763063961,11.56,150408029,58.65,39.95,4.0
25,Missouri,MO,Midwest,420242,36957728,11.37,7119267,59.03,1.90,4578485,411492814,11.13,79003664,57.95,20.73,3.9
26,Montana,MT,West,66867,6571610,10.18,1214373,55.06,0.30,5153390,471302990,10.93,94808378,54.36,23.34,2.7
27,Nebraska,NE,Midwest,147599,11711222,12.60,2272581,64.95,0.67,4578485,411492814,11.13,79003664,57.95,20.73,3.0
28,Nevada,NV,West,203080,18768746,10.82,3675214,55.26,0.92,5153390,471302990,10.93,94808378,54.36,23.34,5.6
29,New Hampshire,NH,Northeast,72263,8268721,8.74,1497455,48.26,0.33,3527918,339127512,10.40,65420694,53.93,15.98,3.1
30,New Jersey,NJ,Northeast,604153,54492751,11.09,10293179,58.69,2.74,3527918,339127512,10.40,65420694,53.93,15.98,4.8
31,New Mexico,NM,West,131858,12642168,10.43,2415538,54.59,0.60,5153390,471302990,10.93,94808378,54.36,23.34,4.3
32,New York,NY,Northeast,1279243,117416826,10.89,23255110,55.01,5.79,3527918,339127512,10.40,65420694,53.93,15.98,4.2
33,North Carolina,NC,South,716519,63558153,11.27,12498057,57.33,3.24,8821173,763063961,11.56,150408029,58.65,39.95,3.7
34,North Dakota,ND,Midwest,60475,4625583,13.07,906297,66.73,0.27,4578485,411492814,11.13,79003664,57.95,20.73,2.6
35,Ohio,OH,Midwest,783704,70393769,11.13,13365288,58.64,3.55,4578485,411492814,11.13,79003664,57.95,20.73,4.9
36,Oklahoma,OK,South,291217,23941096,12.16,4723856,61.65,1.32,8821173,763063961,11.56,150408029,58.65,39.95,3.2
37,Oregon,OR,West,242571,25369607,9.56,4987114,48.64,1.10,5153390,471302990,10.93,94808378,54.36,23.34,4.7
38,Pennsylvania,PA,Northeast,790421,77290050,10.23,14466075,54.64,3.58,3527918,339127512,10.40,65420694,53.93,15.98,3.9
39,Rhode Island,RI,Northeast,61320,6459107,9.49,1273562,48.15,0.28,3527918,339127512,10.40,65420694,53.93,15.98,4.9
40,South Carolina,SC,South,342145,31297775,10.93,5998759,57.04,1.55,8821173,763063961,11.56,150408029,58.65,39.95,4.2
41,South Dakota,SD,Midwest,68073,5384129,12.64,992778,68.57,0.31,4578485,411492814,11.13,79003664,57.95,20.73,1.8
42,Tennessee,TN,South,486893,41639064,11.69,8166631,59.62,2.21,8821173,763063961,11.56,150408029,58.65,39.95,3.5
43,Texas,TX,South,2275693,177119299,12.85,36976634,61.54,10.31,8821173,763063961,11.56,150408029,58.65,39.95,4.1
44,Utah,UT,West,277236,19753451,14.03,4341180,63.86,1.26,5153390,471302990,10.93,94808378,54.36,23.34,3.1
45,Vermont,VT,Northeast,31691,3813733,8.31,704655,44.97,0.14,3527918,339127512,10.40,65420694,53.93,15.98,2.7
46,Virginia,VA,South,576125,51685358,11.15,10227966,56.33,2.61,8821173,763063961,11.56,150408029,58.65,39.95,3.3
47,Washington,WA,West,502242,46181454,10.88,9240808,54.35,2.27,5153390,471302990,10.93,94808378,54.36,23.34,4.4
48,West Virginia,WV,South,104440,10710952,9.75,1888053,55.32,0.47,8821173,763063961,11.56,150408029,58.65,39.95,3.8
49,Wisconsin,WI,Midwest,369546,35168059,10.51,6601801,55.98,1.67,4578485,411492814,11.13,79003664,57.95,20.73,3.3
50,Wyoming,WY,West,37531,3483065,10.78,651779,57.58,0.17,5153390,471302990,10.93,94808378,54.36,23.34,3.3

In [156]:
testmerge = states.merge(inc, on='stateAbbr', how='outer')
testmerge.drop(columns=['STATE'], inplace=True)
for x in ['median2018', 'median2019', 'median2020', 'median2021', 'median2022', 'median2023', 'median2024']:
    testmerge.rename(columns={x: f'perCapitaPersonalIncome{x.split("median")[1]}'}, inplace=True)

testmerge.to_excel("sepehr_states.xlsx", index=False)

In [ ]:
sheeo = pd.read_excel("sheeo.xlsx", sheet_name="Sector Data")
sheeo.rename(columns={'State': 'state'}, inplace=True)
sheeo
rev['stateAbbr'] = rev['state'].map(stateAbbri)

,state,FY,COLI (Cost of Living) Adjustment,HECA (Inflation) Adjustment,CPI (Inflation) Adjustment,Two-Year State Support,Four-Year State Support,Two-Year State and Local Support,Two-Year State and Local Support Excluding Federal Stimulus,Four-Year State and Local Support,...,Four-Year RAM,Two-Year Gross Tuition and Fee Revenue,Four-Year Gross Tuition and Fee Revenue,Two-Year Institutional Discounts and Waivers,Four-Year Institutional Discounts and Waivers,Four-Year Medical Tuition and Fee Revenue,Two-Year Tuition Used for Debt Service,Four-Year Tuition Used for Debt Service,Four-Year Gross FTE Enrollment,Four-Year Medical FTE Enrollment
0,Alabama,2024,0.876645,1.000000,1.000000,649971818,1834974274,652807818,652807818,1834974274,...,395315305,295171538,2824940539,0,0,2.645193e+08,22077974.0,126037140.0,155000,10597
1,Alaska,2024,1.240699,1.000000,1.000000,0,328063402,0,0,328816402,...,22867381,0,107699379,0,20547930,0.000000e+00,0.0,0.0,12684,0
2,Arizona,2024,0.964115,1.000000,1.000000,168884200,1207869800,1189046800,1189046800,1207869800,...,250165600,326001400,4570073200,89443100,1413664000,3.831330e+07,0.0,150158400.0,222845,958
3,Arkansas,2024,0.851381,1.000000,1.000000,192791709,819849031,233126278,233126278,819849031,...,242840558,143744272,982077062,14749019,159196530,5.564444e+07,19984461.0,180534067.0,82189,3271
4,California,2024,1.268947,1.000000,1.000000,7322820000,10858520872,11416681000,11416681000,10858520872,...,1249332000,1257968088,8636729771,0,2090359000,1.081860e+08,0.0,0.0,684868,17326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,West Virginia,2019,0.897032,0.841897,0.815044,68309173,397927750,68309173,68309173,397927750,...,142861228,53619015,790750537,4312365,141444304,1.319273e+08,1765363.0,47330959.0,57315,1814
308,Wisconsin,2019,0.942542,0.841897,0.815044,546951357,877095576,795416572,795416572,877095576,...,169464642,232959417,1444709694,4422882,160415462,3.791284e+07,NaN,NaN,138707,1107
309,Wyoming,2019,0.990072,0.841897,0.815044,148032490,244454986,182604336,182604336,244454986,...,44286798,45912474,112859000,10156832,40625000,0.000000e+00,0.0,805819.0,11023,43
310,U.S.,2019,1.000000,0.841897,0.815044,22588741369,63528793750,34201890861,34201890861,63654826713,...,10893821484,16302227294,87606359756,2122183971,14120565252,3.456191e+09,94020194.0,809112790.0,6754405,153428
311,D.C.,2019,1.497852,0.841897,0.815044,0,99066770,0,0,99066770,...,5900867,0,37583509,0,1440922,0.000000e+00,0.0,0.0,3518,0

In [ ]:
rev = pd.read_excel("forStateStuff.xlsx")

for year in range(2019, 2025):
    for state in rev['state']:
        rev['fourYearAppropriations' + str(year)] = # the "Four-Year Education Appropriations" column for that year.
        rev['twoYearAppropriations' + str(year)] = # the "Two-Year Education Appropriations" column for that year.
        rev['fourYearNetFTE' + str(year)] = # the "Four-Year Net FTE Enrollment" column for that year.
        rev['twoYearNetFTE' + str(year)] = # the "Two-Year Net FTE Enrollment" column for that year.
        rev['fourYearNetTuitionAndFeeRevenue' + str(year)] = # the "Four-Year Net Tuition and Fee Revenue" column for that year.
        rev['twoYearNetTuitionAndFeeRevenue' + str(year)] = # the "Two-Year Net Tuition and Fee Revenue" column for that year.
        rev['fourYearTotalEducationRevenue' + str(year)] = # the "Four-Year Total Education Revenue" column for that year.
        rev['twoYearTotalEducationRevenue' + str(year)] = # the "Two-Year Total Education Revenue" column for that year.

2019
2020
2021
2022
2023
2024

             state stateAbbr
0          Alabama        AL
1           Alaska        AK
2          Arizona        AZ
3         Arkansas        AR
4       California        CA
5         Colorado        CO
6      Connecticut        CT
7         Delaware        DE
8          Florida        FL
9          Georgia        GA
10          Hawaii        HI
11           Idaho        ID
12        Illinois        IL
13         Indiana        IN
14            Iowa        IA
15          Kansas        KS
16        Kentucky        KY
17       Louisiana        LA
18           Maine        ME
19        Maryland        MD
20   Massachusetts        MA
21        Michigan        MI
22       Minnesota        MN
23     Mississippi        MS
24        Missouri        MO
25         Montana        MT
26        Nebraska        NE
27          Nevada        NV
28   New Hampshire        NH
29      New Jersey        NJ
30      New Mexico        NM
31        New York        NY
32  North Carolina        NC
33    North Dakota        ND
34            Ohio        OH
35        Oklahoma        OK
36          Oregon        OR
37    Pennsylvania        PA
38    Rhode Island        RI
39  South Carolina        SC
40    South Dakota        SD
41       Tennessee        TN
42           Texas        TX
43            Utah        UT
44         Vermont        VT
45        Virginia        VA
46      Washington        WA
47   West Virginia        WV
48       Wisconsin        WI
49         Wyoming        WY

In [201]:

result = rev[['state']].copy()

columns_to_extract = {
    'Four-Year Education Appropriations': 'fourYearAppropriations',
    'Two-Year Education Appropriations': 'twoYearAppropriations',
    'Four-Year Net FTE Enrollment': 'fourYearNetFTE',
    'Two-Year Net FTE Enrollment': 'twoYearNetFTE',
    'Four-Year Net Tuition and Fee Revenue': 'fourYearNetTuitionAndFeeRevenue',
    'Two-Year Net Tuition and Fee Revenue': 'twoYearNetTuitionAndFeeRevenue',
    'Four-Year Total Education Revenue': 'fourYearTotalEducationRevenue',
    'Two-Year Total Education Revenue': 'twoYearTotalEducationRevenue',
    'Two-Year Student Share': 'twoYearStudentShare',
    'Four-Year Student Share': 'fourYearStudentShare'
}
for year in range(2019, 2025):
    year_data = sheeo[sheeo['FY'] == year][['state'] + list(columns_to_extract.keys())]
    year_data = year_data.rename(columns={old: f"{new}{year}" for old, new in columns_to_extract.items()})
    result = result.merge(year_data, left_on='state', right_on='state', how='left')
    if 'State' in result.columns:
        result = result.drop('State', axis=1)
result.to_excel("cleaned_sheeo_data.xlsx", index=False)

In [202]:
result

,state,fourYearAppropriations2019,twoYearAppropriations2019,fourYearNetFTE2019,twoYearNetFTE2019,fourYearNetTuitionAndFeeRevenue2019,twoYearNetTuitionAndFeeRevenue2019,fourYearTotalEducationRevenue2019,twoYearTotalEducationRevenue2019,twoYearStudentShare2019,...,fourYearAppropriations2024,twoYearAppropriations2024,fourYearNetFTE2024,twoYearNetFTE2024,fourYearNetTuitionAndFeeRevenue2024,twoYearNetTuitionAndFeeRevenue2024,fourYearTotalEducationRevenue2024,twoYearTotalEducationRevenue2024,twoYearStudentShare2024,fourYearStudentShare2024
0,Alabama,870474437,373978295,143485,59288,2202302684,281380200,2938256114,626186283,0.449355,...,1436147789,652807818,144403,56546,2520822860,288865816,3830933509,919595660,0.314123,0.658018
1,Alaska,317936098,0,16721,0,95873240,0,413809338,0,NaN,...,305949021,0,12684,0,75800668,0,381749689,0,NaN,0.198561
2,Arizona,621655200,1011140300,182299,110557,2279943700,219173700,2797858500,1230314000,0.178145,...,957704200,1189046800,221887,105282,3025577400,235947900,3833123200,1424994700,0.165578,0.789324
3,Arkansas,549066991,210661479,82311,30934,558577535,116421320,1040227329,310435644,0.375026,...,576361781,233126278,78918,27806,684913715,116717549,1080741429,329859366,0.353840,0.633744
4,California,6987935555,9920625750,672687,918444,5427976052,704990279,12415911607,10625616029,0.066348,...,9609188872,11416681000,667542,853174,4887378256,633708088,14496567128,12050389088,0.052588,0.337140
5,Colorado,545568907,348106684,127744,56000,1838423316,248778463,2383992223,596885147,0.416795,...,883748954,482042038,123216,58316,2176433850,243573218,3060182804,725615256,0.335678,0.711210
6,Connecticut,656771926,274395936,57374,26419,922158033,173388994,1578929959,447784930,0.387215,...,988182781,398443921,54369,21708,857868062,150901755,1846050843,549345676,0.274694,0.464704
7,Delaware,155842700,81266100,27524,8886,661616253,51949000,809591103,133215100,0.389963,...,179747600,94134700,29385,7855,750585670,42016440,922161986,136151140,0.308601,0.813941
8,Florida,3264208503,1417043690,293179,315763,732426706,815454125,3996635209,2232497815,0.365265,...,4534349057,1890466581,299049,280428,630038694,763825846,5164387751,2654292427,0.287770,0.121997
9,Georgia,2398496689,521565902,269808,86540,1397005897,233486948,3794690972,755052850,0.309233,...,3316954025,646198743,284195,82553,1413970025,228973765,4730837320,872849995,0.262329,0.298884
10,Hawaii,374900906,216369518,20434,14820,175834578,50802743,546110911,264771012,0.191874,...,417753225,230966989,20723,11971,185039640,39924572,598531517,268735330,0.148565,0.309156
11,Idaho,325709116,81353700,39610,14811,313196882,44776800,638905998,126130500,0.355004,...,393938104,103791621,40500,15284,402384921,45108753,775872945,148211514,0.304354,0.518622
12,Illinois,3017467188,1606815523,166254,140713,1646732954,701083892,4521657874,2307899415,0.303776,...,3920182109,2103336746,159605,102039,1635321421,591781266,5452987081,2695118012,0.219575,0.299895
13,Indiana,1130208640,328434443,182388,63913,2091043906,199967168,3179943627,522197118,0.382934,...,1211248383,374773932,179013,68931,2421439076,211615798,3583724431,581476288,0.363929,0.675677
14,Iowa,441297139,243092718,72148,57239,940858158,295577355,1382155297,538670073,0.548717,...,458260178,300586582,64906,51282,981541949,293545933,1439802127,594132515,0.494075,0.681720
15,Kansas,439318624,422494288,79358,52895,748176878,143407789,1187495502,565902077,0.253414,...,661542924,559318472,74194,46909,747689293,120603314,1398979833,679921786,0.177378,0.534453
16,Kentucky,677076000,228917300,98557,43446,997299484,175672455,1650610692,394186755,0.445658,...,902483944,277708062,96927,42736,1034610250,169880488,1914669769,437242052,0.388527,0.540360
17,Louisiana,694398663,143006506,120841,43091,666905944,155818967,1361304607,298825473,0.521438,...,850399183,191503602,123787,41134,731770334,152448254,1582169517,343951856,0.443226,0.462511
18,Maine,190137977,77996303,24174,9773,216764719,30968136,406902696,108964439,0.284204,...,252581823,109419897,22530,11276,220514252,18907759,473096075,128327656,0.147340,0.466109
19,Maryland,1311024223,804115016,139253,89990,1617504675,405437082,2928528898,1209552098,0.335196,...,2165653384,1034103199,147203,74290,1757389274,362700759,3923042658,1396803958,0.259665,0.447966
20,Massachusetts,1130048154,407309591,110528,49799,884221811,193303325,2014269965,600612916,0.321843,...,1688985706,714506125,94318,42767,1028858932,118535365,2717844638,833041490,0.142292,0.378557
21,Michigan,1378192169,963809154,249978,116340,3994299546,626904274,5372491715,1590713428,0.394103,...,1685847041,1391151754,231731,100514,4265285373,545624627,5951132414,1936776381,0.281718,0.716718
22,Minnesota,820634227,480882007,108148,76219,1290831123,368534372,2111465350,849416379,0.433868,...,1013772361,640326668,95009,66701,1285526671,350288761,2294884211,990615429,0.353607,0.560171
23,Mississippi,387182397,298335003,71200,61799,620658969,222790779,1007841366,521125782,0.427518,...,539257130,372343563,67498,54427,702848167,225508669,1242105297,597852232,0.377198,0.565852
24,Missouri,763826228,338671368,122734,59765,951715709,147642047,1715541937,486313415,0.303594,...,759340391,487695274,102046,42855,981403835,164260811,1740744226,651956085,0.251951,0.563784
25,Montana,177825497,35256995,29697,6678,250076813,11128321,427902310,46385316,0.239910,...,216532837,42184929,28069,6434,283445324,10754871,499978161,52939800,0.203153,0.566915
26,Nebraska,446717302,277420452,49798,26142,423471846,69543626,857005570,342866282,0.202830,...,560946230,345719215,48231,24394,421073434,60106507,966167917,400017811,0.150260,0.435818
27,Nevada,439927542,182977139,47398,29026,152932193,53609076,592859735,236586215,0.226594,...,535162667,244999341,44155,24736,165066122,63817968,700228789,308817309,0.206653,0.235732
28,New Hampshire,68585277,50493263,26500,9853,357236798,56411095,425822075,106904358,0.527678,...,92181065,71824372,22543,7348,305740433,42868710,397921498,114693082,0.373769,0.768344
29,New Jersey,1412319000,463026000,165182,99904,1837231894,324942786,3249550894,787968786,0.412380,...,2149408446,573737554,161065,86990,1721633875,253687727,3871042321,827425281,0.306599,0.444747
30,New Mexico,578461834,359404918,39242,37798,149864116,67574708,728325950,426979626,0.158262,...,795297332,422258954,41940,31403,185213658,48854010,980510990,471112964,0.103699,0.188895
31,New York,4548248299,1953533426,327088,210891,2323477548,915835486,6871725847,2869368912,0.319177,...,5299757084,1962585861,297457,159144,2260929987,862476777,7560687071,2825062638,0.305295,0.299038
32,North Carolina,2368608880,1291226029,214263,179659,1546595373,298247489,3915204253,1589473518,0.187639,...,3112901071,1643167084,217197,192388,1637320074,292009773,4750221145,1935176857,0.150896,0.344683
33,North Dakota,197780892,50404041,26753,7028,275201702,26181191,472982594,76585232,0.341857,...,249900359,64181851,26033,7384,306326264,25795447,556226623,89977298,0.286688,0.550722
34,Ohio,1508658985,660234134,287287,99164,2850770208,332789142,4359429193,993023276,0.335127,...,1688308308,719445753,250602,91210,2983024286,332988868,4671332594,1052434621,0.316399,0.638581
35,Oklahoma,524251783,209392653,88260,40585,764105353,143294453,1288357136,352687106,0.406293,...,666946565,281469697,87035,36248,889771571,109924142,1556718136,391393839,0.280853,0.571569
36,Oregon,421204801,476260495,83519,60770,1069729523,208716359,1490934324,684976854,0.304706,...,552284727,663245104,79833,48624,1268117594,133876809,1820402321,797121913,0.167950,0.696614
37,Pennsylvania,1191536050,412450009,251685,79979,3345838140,341933603,4537374190,754383612,0.453262,...,1459344228,476960218,228789,60619,3017084420,253784744,4476428648,730744962,0.347296,0.673994
38,Rhode Island,133322312,59403822,22645,9333,240348658,53997972,373670970,113401794,0.476165,...,187607409,73314567,21514,7679,299257353,55174415,486864762,128488982,0.429410,0.614662
39,South Carolina,566846085,364277502,109116,57624,1515781725,179957743,1955203208,524586004,0.343047,...,990575645,490364969,115616,59571,1589563244,249305574,2477617404,735647306,0.338893,0.641569
40,South Dakota,150142598,25983216,27006,5810,249382055,19193609,385113234,45176825,0.424855,...,212194396,35922677,25390,5792,236325427,40211482,432648242,70221242,0.572640,0.546230
41,Tennessee,984083013,558263729,111635,72783,990395049,117052372,1931320662,674786101,0.173466,...,1345850465,817911779,116213,63526,1230727576,32522273,2531862271,850009052,0.038261,0.486096
42,Texas,3351297068,3356493121,577131,471903,6056394038,940022889,9407691106,4296516010,0.218787,...,3784973375,4565525522,598674,445811,6714691050,923785553,10499664425,5489311075,0.168288,0.639515
43,Utah,781943425,229326889,102270,25832,723985904,73251211,1505929329,302578100,0.242090,...,1322465808,353517444,107356,26017,900340543,73412622,2222806351,426930066,0.171955,0.405047
44,Vermont,55157953,7945494,17806,2652,347319676,17998251,388296123,25943745,0.693741,...,95458439,21944888,17368,2619,346594230,13291021,427849785,35235909,0.377201,0.810084
45,Virginia,1239774408,463489268,201878,100141,2221289749,378184627,3439045270,838524210,0.451012,...,2120758201,686300652,205844,90626,2261190511,230187455,4358577233,913175612,0.252074,0.518791
46,Washington,979885049,867911611,112000,123981,1036970470,322948389,2016855519,1190860000,0.271189,...,1383608400,1293160399,96367,103022,1283267442,268695986,2666875842,1561856385,0.172036,0.481188
47,West Virginia,255066522,68309173,55501,11076,445541187,39613076,653276750,106156886,0.373156,...,300444867,85033184,48686,9622,420029413,36317949,647862617,120759160,0.300747,0.648331
48,Wisconsin,707630934,795416572,137600,72054,1161149195,195823619,1868780129,991240191,0.197554,...,914698070,857385297,137493,61924,1401792235,151361620,2316490305,1008746917,0.150049,0.605136
49,Wyoming,200168188,182604336,10980,11214,50599000,28846480,249961369,211450816,0.136422,...,243903433,157427397,9452,11035,38070972,44030669,281257320,201458066,0.218560,0.135360

In [203]:
for year in range(2019, 2025):
    for s in result['state']:
        result['fourYearAppropriationsPerFTE' + str(year)] = result['fourYearAppropriations' + str(year)] / result['fourYearNetFTE' + str(year)]
        result['twoYearAppropriationsPerFTE' + str(year)] = result['twoYearAppropriations' + str(year)] / result['twoYearNetFTE' + str(year)]

        result['fourYearNetTuitionRevenuePerFTE' + str(year)] = result['fourYearNetTuitionAndFeeRevenue' + str(year)] / result['fourYearNetFTE' + str(year)]
        result['twoYearNetTuitionRevenuePerFTE' + str(year)] = result['twoYearNetTuitionAndFeeRevenue' + str(year)] / result['twoYearNetFTE' + str(year)]

        result['fourYearTotalEducationRevenue' + str(year)] = result['fourYearTotalEducationRevenue' + str(year)] / result['fourYearNetFTE' + str(year)]
        result['twoYearTotalEducationRevenue' + str(year)] = result['twoYearTotalEducationRevenue' + str(year)] / result['twoYearNetFTE' + str(year)]

result

,state,fourYearAppropriations2019,twoYearAppropriations2019,fourYearNetFTE2019,twoYearNetFTE2019,fourYearNetTuitionAndFeeRevenue2019,twoYearNetTuitionAndFeeRevenue2019,fourYearTotalEducationRevenue2019,twoYearTotalEducationRevenue2019,twoYearStudentShare2019,...,fourYearNetTuitionRevenuePerFTE2022,twoYearNetTuitionRevenuePerFTE2022,fourYearAppropriationsPerFTE2023,twoYearAppropriationsPerFTE2023,fourYearNetTuitionRevenuePerFTE2023,twoYearNetTuitionRevenuePerFTE2023,fourYearAppropriationsPerFTE2024,twoYearAppropriationsPerFTE2024,fourYearNetTuitionRevenuePerFTE2024,twoYearNetTuitionRevenuePerFTE2024
0,Alabama,870474437,373978295,143485,59288,2202302684,281380200,4.243894e-249,1.407225e-230,0.449355,...,16827.454861,5115.434951,10843.068670,17754.001630,16946.399535,4915.602647,9945.415185,11544.721430,17456.859345,5108.510169
1,Alaska,317936098,0,16721,0,95873240,0,2.842418e-203,NaN,NaN,...,6321.867122,NaN,24291.805300,NaN,6210.738965,NaN,24120.862583,NaN,5976.085462,NaN
2,Arizona,621655200,1011140300,182299,110557,2279943700,219173700,2.556298e-254,8.141486e-244,0.178145,...,12159.572298,2045.546559,4582.305313,12384.238804,12709.558617,2125.463838,4316.179857,11293.922988,13635.667705,2241.103892
3,Arkansas,549066991,210661479,82311,30934,558577535,116421320,1.754827e-237,9.336144e-217,0.375026,...,7282.525190,3955.121772,7394.071753,8568.791269,7915.223176,4027.962836,7303.299387,8384.027836,8678.802238,4197.567036
4,California,6987935555,9920625750,672687,918444,5427976052,704990279,5.050413e-282,7.476874e-289,0.066348,...,7165.025293,796.747432,13669.137001,14445.009353,7340.661324,812.989345,14394.882827,13381.421609,7321.454314,742.765354
5,Colorado,545568907,348106684,127744,56000,1838423316,248778463,1.148892e-246,2.325356e-229,0.416795,...,16835.782151,3990.410495,6859.550513,6884.995050,17641.634551,3794.114192,7172.355490,8266.033987,17663.565203,4176.781981
6,Connecticut,656771926,274395936,57374,26419,922158033,173388994,1.830655e-229,3.591292e-213,0.387215,...,16409.212943,6595.712137,20497.159490,23579.980701,16520.080424,6151.031116,18175.482003,18354.704303,15778.624989,6951.435185
7,Delaware,155842700,81266100,27524,8886,661616253,51949000,8.369283e-214,4.889202e-190,0.389963,...,25455.438549,5601.656425,5982.647924,12608.964281,24597.205553,5788.884292,6116.984856,11984.048377,25543.157053,5349.005729
8,Florida,3264208503,1417043690,293179,315763,732426706,815454125,1.758132e-264,2.402863e-266,0.365265,...,2310.322854,2599.643714,12998.787527,6108.412325,2122.035444,2685.270089,15162.562179,6741.361708,2106.807560,2723.785949
9,Georgia,2398496689,521565902,269808,86540,1397005897,233486948,1.062760e-262,1.040238e-238,0.309233,...,5305.669418,2893.519284,12375.129768,8536.458905,5202.259452,2926.515505,11671.401766,7827.683343,4975.351519,2773.657711
10,Hawaii,374900906,216369518,20434,14820,175834578,50802743,1.658103e-207,7.593819e-201,0.191874,...,9050.476871,3181.916048,21060.481246,21763.703219,8989.444477,3475.361422,20158.916421,19293.875950,8929.191719,3335.107510
11,Idaho,325709116,81353700,39610,14811,313196882,44776800,8.226116e-222,3.729074e-201,0.355004,...,10125.881806,3014.628939,9596.002005,6673.256036,10094.387464,3003.104042,9726.866765,6790.867639,9935.430148,2951.370911
12,Illinois,3017467188,1606815523,166254,140713,1646732954,701083892,4.137067e-252,8.841089e-249,0.303776,...,10630.722523,6059.526731,22773.619199,18434.395089,10179.195469,5782.324386,24561.775063,20613.067023,10246.053827,5799.559639
13,Indiana,1130208640,328434443,182388,63913,2091043906,199967168,2.835348e-254,2.743938e-232,0.382934,...,13172.736201,2934.630081,6329.996678,5476.906027,13403.011583,2945.517588,6766.259339,5436.943204,13526.610224,3069.965589
14,Iowa,441297139,243092718,72148,57239,940858158,295577355,1.695673e-234,7.026207e-230,0.548717,...,14034.786609,5349.078315,7096.399298,5712.386839,14631.278312,5489.983646,7060.366961,5861.444210,15122.514852,5724.151418
15,Kansas,439318624,422494288,79358,52895,748176878,143407789,1.244791e-236,3.819533e-228,0.253414,...,8953.405022,2986.336744,7787.899154,11080.290956,9271.964913,2817.089526,8916.393832,11923.478906,10077.489999,2571.005862
16,Kentucky,677076000,228917300,98557,43446,997299484,175672455,3.414058e-241,4.991282e-224,0.445658,...,10750.455789,4212.999233,9047.828056,6863.796336,10394.570387,4027.770714,9310.965407,6498.223091,10674.118151,3975.114377
17,Louisiana,694398663,143006506,120841,43091,666905944,155818967,1.054969e-245,5.702811e-224,0.521438,...,5526.080788,4246.738204,6465.895975,4488.212476,6123.336482,3732.440497,6869.858572,4655.603686,5911.528141,3706.137356
18,Maine,190137977,77996303,24174,9773,216764719,30968136,2.767354e-211,3.434708e-192,0.284204,...,9434.668416,2808.069344,10441.897685,11115.602917,9327.137906,1473.987034,11210.910919,9703.786538,9787.583311,1676.814385
19,Maryland,1311024223,804115016,139253,89990,1617504675,405437082,1.889825e-248,2.360000e-239,0.335196,...,11723.073439,4720.037301,13152.372507,13411.971294,11912.619565,4797.703929,14712.019347,13919.816920,11938.542516,4882.228550
20,Massachusetts,1130048154,407309591,110528,49799,884221811,193303325,1.350523e-243,8.271106e-227,0.321843,...,7762.837360,3703.824660,15683.123331,15259.629613,11832.653903,3765.191585,17907.352849,16706.949868,10908.404886,2771.654897
21,Michigan,1378192169,963809154,249978,116340,3994299546,626904274,6.840476e-261,8.225058e-245,0.394103,...,17358.900796,5045.193382,7213.204355,12585.987832,17949.685111,5435.379787,7275.017330,13840.377997,18406.192408,5428.344579
22,Minnesota,820634227,480882007,108148,76219,1290831123,368534372,4.203967e-243,6.698203e-236,0.433868,...,13053.680871,5159.166528,9271.326065,8358.998406,13422.692078,5310.154815,10670.277142,9599.956043,13530.577851,5251.626827
23,Mississippi,387182397,298335003,71200,61799,620658969,222790779,2.395480e-234,1.471872e-231,0.427518,...,9401.818055,4012.190929,7922.361032,6521.329931,9630.469415,4104.258379,7989.231236,6841.155364,10412.873967,4143.323516
24,Missouri,763826228,338671368,122734,59765,951715709,147642047,6.111628e-246,7.320994e-231,0.303594,...,8284.328525,3269.508589,7143.713724,10343.203191,9002.205090,3583.339450,7441.157821,11380.125400,9617.269026,3832.943904
25,Montana,177825497,35256995,29697,6678,250076813,11128321,9.901835e-216,2.716813e-184,0.239910,...,8961.773866,1641.879212,7532.250758,6344.519791,9599.876841,1590.088649,7714.305355,6556.563413,10098.162528,1671.568387
26,Nebraska,446717302,277420452,49798,26142,423471846,69543626,1.181377e-226,4.657837e-213,0.202830,...,8570.369273,2579.084328,11024.182423,13880.860404,8588.535792,2546.900134,11630.408451,14172.305280,8730.348407,2463.987333
27,Nevada,439927542,182977139,47398,29026,152932193,53609076,9.659422e-226,1.716445e-215,0.226594,...,3892.349457,1962.387787,9860.574083,8232.266624,3694.496659,2017.459852,12120.092107,9904.565855,3738.333643,2579.963131
28,New Hampshire,68585277,50493263,26500,9853,357236798,56411095,2.930451e-213,2.241668e-192,0.527678,...,13652.800762,5717.689288,3563.736977,8325.146712,13727.329957,5701.190411,4089.121457,9774.683179,13562.544160,5834.065052
29,New Jersey,1412319000,463026000,165182,99904,1837231894,324942786,4.108538e-252,8.267328e-242,0.412380,...,11660.625748,3630.350042,11764.978042,6281.062673,11693.871499,3184.913650,13344.975296,6595.442626,10689.062646,2916.286090
30,New Mexico,578461834,359404918,39242,37798,149864116,67574708,1.495440e-221,5.714341e-221,0.158262,...,7303.581436,1961.079254,22804.267814,13943.772727,4493.499964,1384.210579,18962.740391,13446.452696,4416.157797,1555.711556
31,New York,4548248299,1953533426,327088,210891,2323477548,915835486,1.270092e-266,1.798391e-257,0.319177,...,6927.139656,5179.209940,16246.539107,12762.622526,7803.286351,5396.065889,17816.884740,12332.138573,7600.863274,5419.474042
32,North Carolina,2368608880,1291226029,214263,179659,1546595373,298247489,1.110185e-257,3.011649e-254,0.187639,...,7182.089402,1605.678720,13460.526316,8530.516309,7256.341301,1563.062513,14332.155007,8540.902156,7538.410171,1517.816979
33,North Dakota,197780892,50404041,26753,7028,275201702,26181191,2.024047e-213,3.487847e-185,0.341857,...,12371.421891,3920.639025,8319.248215,8192.400293,12545.827619,3740.725459,9599.368455,8692.016658,11766.844543,3493.424567
34,Ohio,1508658985,660234134,287287,99164,2850770208,332789142,5.292135e-264,1.510976e-241,0.335127,...,11086.264836,2838.500569,6448.096648,7069.309839,11625.813354,3000.388496,6737.010511,7887.794683,11903.433676,3650.793422
35,Oklahoma,524251783,209392653,88260,40585,764105353,143294453,6.634988e-239,1.346208e-222,0.406293,...,10205.379449,3560.643421,6852.497629,7187.042348,10894.563309,3240.930996,7662.969667,7765.109716,10223.146677,3032.557438
36,Oregon,421204801,476260495,83519,60770,1069729523,208716359,1.213932e-237,4.479341e-231,0.304706,...,15127.566299,3575.956492,7224.001914,12766.899837,15483.731321,3337.650234,6918.000413,13640.282659,15884.629088,2753.307194
37,Pennsylvania,1191536050,412450009,251685,79979,3345838140,341933603,4.110910e-261,5.355423e-237,0.453262,...,13311.849849,4223.857225,6738.651359,7804.851011,13203.367900,4187.726009,6378.559406,7868.163744,13187.191779,4186.554447
38,Rhode Island,133322312,59403822,22645,9333,240348658,53997972,6.666120e-210,3.577310e-191,0.476165,...,13693.659107,6714.444767,7572.592950,9157.742659,13272.404022,7027.211256,8720.247699,9547.410731,13909.889049,7185.104180
39,South Carolina,566846085,364277502,109116,57624,1515781725,179957743,2.493274e-243,4.893804e-230,0.343047,...,14028.597458,3194.736113,7078.918365,7003.534884,14632.613458,2591.426637,8567.807613,8231.605462,13748.644167,4185.015763
40,South Dakota,150142598,25983216,27006,5810,249382055,19193609,1.029379e-213,2.793245e-181,0.424855,...,9414.006810,6779.592554,7308.694810,5625.847093,9344.666425,6734.515342,8357.400394,6202.119648,9307.815163,6942.590124
41,Tennessee,984083013,558263729,111635,72783,990395049,117052372,7.867478e-244,5.341565e-235,0.173466,...,9266.531177,622.348311,11729.828869,12533.625305,9315.801684,250.870135,11580.894263,12875.228710,10590.274548,511.952161
42,Texas,3351297068,3356493121,577131,471903,6056394038,940022889,8.123869e-279,8.719258e-275,0.218787,...,11852.683164,2236.540976,6313.850682,9755.189008,11350.267181,1996.377470,6322.261155,10240.944082,11215.938975,2072.146163
43,Utah,781943425,229326889,102270,25832,723985904,73251211,4.902209e-242,7.463386e-213,0.242090,...,7897.688535,3380.297548,10216.723937,12278.620899,8027.490730,3039.888789,12318.508588,13587.940347,8386.494868,2821.717416
44,Vermont,55157953,7945494,17806,2652,347319676,17998251,1.150389e-204,1.719320e-164,0.693741,...,19427.158954,4970.157915,5515.987958,5847.953622,19680.433971,6340.442698,5496.225184,8379.109584,19955.909143,5074.845743
45,Virginia,1239774408,463489268,201878,100141,2221289749,378184627,1.914204e-256,7.814828e-242,0.451012,...,11427.089283,3253.475305,9007.888387,7027.483298,11563.627570,3077.424267,10302.744802,7572.889149,10984.971682,2539.971476
46,Washington,979885049,867911611,112000,123981,1036970470,322948389,6.978686e-244,2.559198e-246,0.271189,...,11150.324357,2494.250671,12422.615296,11124.211657,12605.484011,2088.625545,14357.699212,12552.274262,13316.461465,2608.141814
47,West Virginia,255066522,68309173,55501,11076,445541187,39613076,3.981592e-229,6.409156e-195,0.373156,...,8701.384390,3594.487956,6000.308116,9304.549336,8615.166124,3526.667197,6171.073142,8837.371025,8627.314074,3774.469861
48,Wisconsin,707630934,795416572,137600,72054,1161149195,195823619,2.190970e-248,1.297998e-234,0.197554,...,9195.000792,2482.689991,6148.822223,14025.160304,9756.439621,2381.878672,6652.688282,13845.767344,10195.371655,2444.312706
49,Wyoming,200168188,182604336,10980,11214,50599000,28846480,2.332147e-194,6.873561e-195,0.136422,...,3811.944615,3182.495330,21325.476683,13777.941343,4581.978775,3657.227196,25804.425836,14266.189126,4027.821837,3990.092343

In [ ]:
# df_rev = result.copy()
for year in range(2019, 2025):
    result.drop(columns=[
        'fourYearAppropriations' + str(year),
        'twoYearAppropriations' + str(year),
        'fourYearNetFTE' + str(year),
        'twoYearNetFTE' + str(year),
        'fourYearNetTuitionAndFeeRevenue' + str(year),
        'twoYearNetTuitionAndFeeRevenue' + str(year),
        'fourYearTotalEducationRevenue' + str(year),
        'twoYearTotalEducationRevenue' + str(year)
    ], inplace=True)

KeyError: "['fourYearAppropriations2019', 'twoYearAppropriations2019', 'fourYearNetFTE2019', 'twoYearNetFTE2019', 'fourYearNetTuitionAndFeeRevenue2019', 'twoYearNetTuitionAndFeeRevenue2019', 'fourYearTotalEducationRevenue2019', 'twoYearTotalEducationRevenue2019'] not found in axis"

In [ ]:
result.to_excel("sheeo_cleaned.xlsx", index=False)

In [209]:
states = pd.read_excel("states_final/sepehr_states.xlsx")
tester = states.merge(result, on='state', how='outer')
tester.to_excel("sepehr_states.xlsx", index=False)

In [248]:
sl2018 = pd.read_csv("ACSST5Y2018.S1501-Data.csv", skiprows=1)
sl2019 = pd.read_csv("ACSST5Y2019.S1501-Data.csv", skiprows=1)
sl2020 = pd.read_csv("ACSST5Y2020.S1501-Data.csv", skiprows=1)
sl2021 = pd.read_csv("ACSST5Y2021.S1501-Data.csv", skiprows=1)
sl2022 = pd.read_csv("ACSST5Y2022.S1501-Data.csv", skiprows=1)
sl2023 = pd.read_csv("ACSST5Y2023.S1501-Data.csv", skiprows=1)

sl2018

,Geography,Geographic Area Name,Estimate!!Total!!Population 18 to 24 years,Margin of Error!!Total MOE!!Population 18 to 24 years,Estimate!!Total!!Population 18 to 24 years!!Less than high school graduate,Margin of Error!!Total MOE!!Population 18 to 24 years!!Less than high school graduate,Estimate!!Total!!Population 18 to 24 years!!High school graduate (includes equivalency),Margin of Error!!Total MOE!!Population 18 to 24 years!!High school graduate (includes equivalency),Estimate!!Total!!Population 18 to 24 years!!Some college or associate's degree,Margin of Error!!Total MOE!!Population 18 to 24 years!!Some college or associate's degree,...,Margin of Error!!Percent MOE!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Estimate!!Male!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Margin of Error!!Male MOE!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Estimate!!Percent Male!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Margin of Error!!Percent Male MOE!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Estimate!!Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Margin of Error!!Female MOE!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Estimate!!Percent Female!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Margin of Error!!Percent Female MOE!!MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018 INFLATION-ADJUSTED DOLLARS)!!Population 25 years and over with earnings!!Graduate or professional degree,Unnamed: 770
0,0400000US01,Alabama,465929,1086,65096,2074,152557,2860,214231,2844,...,(X),81597,1630,(X),(X),52630,351,(X),(X),NaN
1,0400000US02,Alaska,74651,355,9914,618,30003,1015,29655,982,...,(X),89173,3004,(X),(X),67889,1560,(X),(X),NaN
2,0400000US04,Arizona,678970,555,108767,2346,220205,3103,297624,3429,...,(X),82617,1050,(X),(X),53640,480,(X),(X),NaN
3,0400000US05,Arkansas,285421,1016,37114,1354,95970,2239,129703,2015,...,(X),75169,1863,(X),(X),52641,745,(X),(X),NaN
4,0400000US06,California,3856220,1093,448601,4650,1152682,7893,1856816,8967,...,(X),104547,429,(X),(X),72811,335,(X),(X),NaN
5,0400000US08,Colorado,522730,865,65625,1822,160510,2405,233095,2764,...,(X),86547,1214,(X),(X),55820,730,(X),(X),NaN
6,0400000US09,Connecticut,350171,350,36732,1624,101261,1944,157623,1918,...,(X),103717,1216,(X),(X),69570,830,(X),(X),NaN
7,0400000US10,Delaware,86090,221,12141,867,28436,1062,37359,1077,...,(X),84001,2563,(X),(X),64058,1150,(X),(X),NaN
8,0400000US11,District of Columbia,75780,118,6898,518,20186,915,31451,1216,...,(X),104310,2011,(X),(X),84124,1397,(X),(X),NaN
9,0400000US12,Florida,1762860,1663,273595,4336,537561,5814,791324,6645,...,(X),77608,864,(X),(X),52321,356,(X),(X),NaN
10,0400000US13,Georgia,1009642,1913,159055,2914,327282,4734,431998,4675,...,(X),84304,787,(X),(X),56931,511,(X),(X),NaN
11,0400000US15,Hawaii,127161,123,9219,547,50004,1503,57039,1489,...,(X),81740,2291,(X),(X),59069,1428,(X),(X),NaN
12,0400000US16,Idaho,159367,726,21385,1077,56085,1640,71677,1748,...,(X),76719,3133,(X),(X),50062,1494,(X),(X),NaN
13,0400000US17,Illinois,1212593,1064,147960,2862,350211,4095,551084,4555,...,(X),93411,893,(X),(X),62978,322,(X),(X),NaN
14,0400000US18,Indiana,663318,966,103736,2240,210738,3296,283345,3712,...,(X),75759,1046,(X),(X),54704,493,(X),(X),NaN
15,0400000US19,Iowa,321094,951,32883,1194,87035,2063,165561,2342,...,(X),77271,1465,(X),(X),59515,1071,(X),(X),NaN
16,0400000US20,Kansas,298556,971,34944,1146,84658,1915,147033,2256,...,(X),77500,1696,(X),(X),52598,533,(X),(X),NaN
17,0400000US21,Kentucky,424181,1179,53243,1613,150237,2811,184513,2502,...,(X),70480,1375,(X),(X),52723,431,(X),(X),NaN
18,0400000US22,Louisiana,447201,1042,75697,1808,151257,2947,186270,2878,...,(X),78384,1555,(X),(X),52100,576,(X),(X),NaN
19,0400000US23,Maine,110255,430,12151,711,35412,1217,50714,1243,...,(X),69005,2504,(X),(X),53727,981,(X),(X),NaN
20,0400000US24,Maryland,544400,591,60981,1786,163944,2835,245008,3031,...,(X),103947,928,(X),(X),72988,531,(X),(X),NaN
21,0400000US25,Massachusetts,701501,555,73713,2078,190483,2995,310768,3576,...,(X),100436,637,(X),(X),68612,521,(X),(X),NaN
22,0400000US26,Michigan,989175,777,126336,2289,293587,2957,467659,3563,...,(X),87591,927,(X),(X),60148,534,(X),(X),NaN
23,0400000US27,Minnesota,503989,823,61173,1648,139569,2173,234532,2419,...,(X),84977,1018,(X),(X),64448,389,(X),(X),NaN
24,0400000US28,Mississippi,301140,1135,45436,1650,88689,1935,147879,2375,...,(X),69089,2085,(X),(X),49008,987,(X),(X),NaN
25,0400000US29,Missouri,580161,1307,74168,2035,177040,2575,270703,3371,...,(X),75407,873,(X),(X),52765,413,(X),(X),NaN
26,0400000US30,Montana,99873,624,12637,767,35265,1152,43587,1324,...,(X),65183,3008,(X),(X),50713,1043,(X),(X),NaN
27,0400000US31,Nebraska,189779,575,19603,762,54049,1517,93503,1619,...,(X),74723,1204,(X),(X),56069,794,(X),(X),NaN
28,0400000US32,Nevada,246923,382,41114,1261,93627,2068,98700,1943,...,(X),77804,1949,(X),(X),58118,1269,(X),(X),NaN
29,0400000US33,New Hampshire,128944,463,12815,667,41242,1230,57646,1340,...,(X),92891,2227,(X),(X),60495,1338,(X),(X),NaN
30,0400000US34,New Jersey,778901,407,88450,2347,219628,3614,346118,3641,...,(X),107362,665,(X),(X),72401,633,(X),(X),NaN
31,0400000US35,New Mexico,203990,817,35233,1254,61969,1867,94947,1948,...,(X),78143,1864,(X),(X),53518,617,(X),(X),NaN
32,0400000US36,New York,1870478,971,218500,3284,492098,4554,857399,5727,...,(X),92718,727,(X),(X),67389,413,(X),(X),NaN
33,0400000US37,North Carolina,981234,1440,130868,3229,306106,4237,447074,4366,...,(X),83097,822,(X),(X),52803,345,(X),(X),NaN
34,0400000US38,North Dakota,88250,578,7132,594,24229,1155,45460,1289,...,(X),77754,1973,(X),(X),57704,1919,(X),(X),NaN
35,0400000US39,Ohio,1086626,1224,144436,2435,362436,4037,469420,4148,...,(X),81613,890,(X),(X),59111,474,(X),(X),NaN
36,0400000US40,Oklahoma,385430,739,60329,1131,129933,1980,166411,2190,...,(X),74953,1293,(X),(X),48650,743,(X),(X),NaN
37,0400000US41,Oregon,363072,687,49695,1510,110001,2518,169426,2724,...,(X),82511,1403,(X),(X),55716,841,(X),(X),NaN
38,0400000US42,Pennsylvania,1194488,978,142524,2632,399558,3815,501411,4354,...,(X),87179,908,(X),(X),61273,420,(X),(X),NaN
39,0400000US44,Rhode Island,114554,360,11095,739,34569,1251,54421,1337,...,(X),85472,2640,(X),(X),68102,1801,(X),(X),NaN
40,0400000US45,South Carolina,474672,767,63614,1903,154041,2892,214707,3022,...,(X),74414,1512,(X),(X),51155,515,(X),(X),NaN
41,0400000US46,South Dakota,84140,636,11553,620,24819,1006,39246,1015,...,(X),64379,2225,(X),(X),51131,1287,(X),(X),NaN
42,0400000US47,Tennessee,618989,1250,71636,2106,219284,3694,267459,3189,...,(X),76991,1304,(X),(X),52156,432,(X),(X),NaN
43,0400000US48,Texas,2777150,1896,421016,5740,904155,7547,1213484,7965,...,(X),91884,646,(X),(X),59437,413,(X),(X),NaN
44,0400000US49,Utah,344236,546,40804,1295,106207,1913,173559,2151,...,(X),87872,1663,(X),(X),54115,714,(X),(X),NaN
45,0400000US50,Vermont,66936,357,6161,505,20981,900,31318,868,...,(X),69535,2155,(X),(X),53202,965,(X),(X),NaN
46,0400000US51,Virginia,815995,1572,83145,2326,250657,3400,377600,3871,...,(X),105314,482,(X),(X),64327,449,(X),(X),NaN
47,0400000US53,Washington,659518,896,92690,2165,207587,3181,284493,3278,...,(X),96912,1150,(X),(X),63303,434,(X),(X),NaN
48,0400000US54,West Virginia,163597,667,19994,940,59524,1608,70912,1717,...,(X),69148,3309,(X),(X),50921,839,(X),(X),NaN
49,0400000US55,Wisconsin,558562,748,60890,1551,177830,2920,256900,3093,...,(X),77552,995,(X),(X),58289,614,(X),(X),NaN
50,0400000US56,Wyoming,54826,616,7256,663,19015,838,24849,967,...,(X),70898,2938,(X),(X),56662,1859,(X),(X),NaN
51,0400000US72,Puerto Rico,334598,*****,31879,1442,93378,2078,181636,2157,...,(X),44335,2417,(X),(X),32477,828,(X),(X),NaN

In [256]:
sl2018 = pd.read_csv("ACSST5Y2018.S1501-Data.csv", skiprows=1)
sl2019 = pd.read_csv("ACSST5Y2019.S1501-Data.csv", skiprows=1)
sl2020 = pd.read_csv("ACSST5Y2020.S1501-Data.csv", skiprows=1)
sl2021 = pd.read_csv("ACSST5Y2021.S1501-Data.csv", skiprows=1)
sl2022 = pd.read_csv("ACSST5Y2022.S1501-Data.csv", skiprows=1)
sl2023 = pd.read_csv("ACSST5Y2023.S1501-Data.csv", skiprows=1)

for df in [sl2018, sl2019, sl2020, sl2021, sl2022, sl2023]:
    df.drop(columns=[col for col in df.columns if col.startswith("Margin of Error")], inplace=True)
    df.drop(columns=['Geography'], inplace=True)
    df.rename(columns={'Geographic Area Name': 'state'}, inplace=True)

x = 2018
for df in [sl2018, sl2019, sl2020, sl2021, sl2022, sl2023]:
    y = "sll" + str(x)
    y = df.iloc[:, :15]
    y['stateAbbr'] = y['state'].map(stateAbbri)
    y.to_csv(f"populationData/sll{x}.csv", index=False)
    x += 1

In [257]:
s2018 = pd.read_csv("populationData/sll2018.csv")
s2019 = pd.read_csv("populationData/sll2019.csv")
s2020 = pd.read_csv("populationData/sll2020.csv")
s2021 = pd.read_csv("populationData/sll2021.csv")
s2022 = pd.read_csv("populationData/sll2022.csv")
s2023 = pd.read_csv("populationData/sll2023.csv")

s2018

,state,Estimate!!Total!!Population 18 to 24 years,Estimate!!Total!!Population 18 to 24 years!!Less than high school graduate,Estimate!!Total!!Population 18 to 24 years!!High school graduate (includes equivalency),Estimate!!Total!!Population 18 to 24 years!!Some college or associate's degree,Estimate!!Total!!Population 18 to 24 years!!Bachelor's degree or higher,Estimate!!Total!!Population 25 years and over,Estimate!!Total!!Population 25 years and over!!Less than 9th grade,"Estimate!!Total!!Population 25 years and over!!9th to 12th grade, no diploma",Estimate!!Total!!Population 25 years and over!!High school graduate (includes equivalency),"Estimate!!Total!!Population 25 years and over!!Some college, no degree",Estimate!!Total!!Population 25 years and over!!Associate's degree,Estimate!!Total!!Population 25 years and over!!Bachelor's degree,Estimate!!Total!!Population 25 years and over!!Graduate or professional degree,Estimate!!Total!!Population 25 years and over!!High school graduate or higher,stateAbbr
0,Alabama,465929,65096,152557,214231,34045,3299958,149392,320651,1020172,713655,273493,515443,307152,2829915,AL
1,Alaska,74651,9914,30003,29655,5079,477727,12245,22515,133851,129419,40052,88053,51592,442967,AK
2,Arizona,678970,108767,220205,297624,52374,4633932,266283,346719,1112551,1172161,398147,835120,502951,4020930,AZ
3,Arkansas,285421,37114,95970,129703,22634,1999307,100384,175645,681223,451364,139070,288720,162901,1723278,AR
4,California,3856220,448601,1152682,1856816,398121,26218885,2471189,2004376,5391120,5582150,2051313,5445781,3272956,21743320,CA
5,Colorado,522730,65625,160510,233095,63500,3748592,133605,189113,803431,803337,314214,944470,560422,3425874,CO
6,Connecticut,350171,36732,101261,157623,54555,2478708,101068,134758,670519,416267,190869,538924,426303,2242882,CT
7,Delaware,86090,12141,28436,37359,8154,659979,22874,44608,208557,125186,51522,120794,86438,592497,DE
8,District of Columbia,75780,6898,20186,31451,17245,486981,18986,26819,83572,62618,14637,118817,161532,441176,DC
9,Florida,1762860,273595,537561,791324,160380,14686727,723824,1045665,4231678,2963473,1438630,2721635,1561822,12917238,FL
10,Georgia,1009642,159055,327282,431998,91307,6786547,324756,579158,1890132,1394241,518144,1282947,797169,5882633,GA
11,Hawaii,127161,9219,50004,57039,10899,988367,37398,43298,273633,207856,105186,212053,108943,907671,HI
12,Idaho,159367,21385,56085,71677,10220,1089266,38173,64518,301860,287113,104333,198648,94621,986575,ID
13,Illinois,1212593,147960,350211,551084,163338,8682343,432496,532091,2267535,1799808,692622,1801833,1155958,7717756,IL
14,Indiana,663318,103736,210738,283345,65499,4399815,164640,337984,1475931,898842,382510,727108,412800,3897191,IN
15,Iowa,321094,32883,87035,165561,35615,2081373,65482,101227,648137,441087,238423,395820,191197,1914664,IA
16,Kansas,298556,34944,84658,147033,31921,1894675,69212,106507,492819,442045,161016,394462,228614,1718956,KS
17,Kentucky,424181,53243,150237,184513,36188,3004004,174998,254575,991791,628235,244802,415937,293666,2574431,KY
18,Louisiana,447201,75697,151257,186270,33977,3107941,158218,313742,1055768,656172,186448,483170,254423,2635981,LA
19,Maine,110255,12151,35412,50714,11978,967897,26431,47995,308013,189609,96570,190172,109107,893471,ME
20,Maryland,544400,60981,163944,245008,74467,4114858,164123,245634,1021847,779171,273518,877641,752924,3705101,MD
21,Massachusetts,701501,73713,190483,310768,126537,4748795,214205,240155,1150846,740784,365103,1128877,908825,4294435,MA
22,Michigan,989175,126336,293587,467659,101593,6772215,200210,441326,1966809,1590065,636753,1179677,757375,6130679,MI
23,Minnesota,503989,61173,139569,234532,68715,3731762,109242,153159,930058,792097,424424,871363,451419,3469361,MN
24,Mississippi,301140,45436,88689,147879,19136,1967314,105815,210530,596564,440894,184334,266274,162903,1650969,MS
25,Missouri,580161,74168,177040,270703,58250,4124838,134369,296160,1266430,923045,323751,729543,451540,3694309,MO
26,Montana,99873,12637,35265,43587,8384,714267,14320,34288,208896,169796,64097,148624,74246,665659,MT
27,Nebraska,189779,19603,54049,93503,22624,1242463,49228,61511,326549,285916,130043,258291,130925,1131724,NE
28,Nevada,246923,41114,93627,98700,13482,2001450,113903,160260,563229,515011,163699,317510,167838,1727287,NV
29,New Hampshire,128944,12815,41242,57646,17241,952115,21176,46431,263005,177691,96387,213277,134148,884508,NH
30,New Jersey,778901,88450,219628,346118,124705,6129542,303217,337896,1683568,1019736,401069,1457910,926146,5488429,NJ
31,New Mexico,203990,35233,61969,94947,11841,1394280,86723,118835,368487,327375,114664,213129,165067,1188722,NM
32,New York,1870478,218500,492098,857399,302481,13606342,857177,982672,3556251,2137839,1184265,2748577,2139561,11766493,NY
33,North Carolina,981234,130868,306106,447074,97186,6881774,322916,546950,1780253,1479791,652658,1345846,753360,6011908,NC
34,North Dakota,88250,7132,24229,45460,11429,490233,15703,21091,131264,110567,67212,105552,38844,453439,ND
35,Ohio,1086626,144436,362436,469420,110334,7937085,223320,562840,2639478,1624247,681630,1370810,834760,7150925,OH
36,Oklahoma,385430,60329,129933,166411,28757,2574001,105753,208035,806407,606833,198903,428829,219241,2260213,OK
37,Oregon,363072,49695,110001,169426,33950,2850693,105456,168726,656365,732477,249852,583144,354673,2576511,OR
38,Pennsylvania,1194488,142524,399558,501411,150995,8921363,291164,582854,3133655,1426783,741590,1661705,1083612,8047345,PA
39,Rhode Island,114554,11095,34569,54421,14469,733188,38156,49838,207007,133087,61136,145595,98369,645194,RI
40,South Carolina,474672,63614,154041,214707,42310,3385002,141638,294132,998459,698504,324446,588965,338858,2949232,SC
41,South Dakota,84140,11553,24819,39246,8522,567083,17892,29052,173262,120325,65075,112426,49051,520139,SD
42,Tennessee,618989,71636,219284,267459,60610,4530706,219600,370670,1467848,942609,323928,762299,443752,3940436,TN
43,Texas,2777150,421016,904155,1213484,238495,17815359,1506111,1487321,4448881,3892527,1261050,3409836,1809633,14821927,TX
44,Utah,344236,40804,106207,173559,23666,1782065,49534,93826,407324,464955,173766,391237,201423,1638705,UT
45,Vermont,66936,6161,20981,31318,8476,439695,10187,22520,128172,77197,37513,97034,67072,406988,VT
46,Virginia,815995,83145,250657,377600,104593,5730352,248375,364445,1381080,1112619,436970,1244489,942374,5117532,VA
47,Washington,659518,92690,207587,284493,74748,5001943,187130,257591,1109016,1183496,501449,1104621,658640,4557222,WA
48,West Virginia,163597,19994,59524,70912,13167,1292084,57449,116781,523536,240593,91975,158032,103718,1117854,WV
49,Wisconsin,558562,60890,177830,256900,62942,3930889,108427,208747,1216570,814428,422227,762210,398280,3613715,WI
50,Wyoming,54826,7256,19015,24849,3706,389291,7402,20242,111899,102236,42835,67697,36980,361647,WY
51,Puerto Rico,334598,31879,93378,181636,27705,2364398,374779,203450,659670,292120,235051,428310,171018,1786169,PR

In [264]:
s2018 = pd.read_csv("populationData/sll2018.csv")
s2019 = pd.read_csv("populationData/sll2019.csv")
s2020 = pd.read_csv("populationData/sll2020.csv")
s2021 = pd.read_csv("populationData/sll2021.csv")
s2022 = pd.read_csv("populationData/sll2022.csv")
s2023 = pd.read_csv("populationData/sll2023.csv")

prename = "Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!"
x = 2018
s2018.drop(columns=['Estimate!!Total!!Population 18 to 24 years!!Less than high school graduate',
                    'Estimate!!Total!!Population 25 years and over!!Less than 9th grade',
                    'Estimate!!Total!!Population 25 years and over!!9th to 12th grade, no diploma',
                    'Estimate!!Total!!Population 25 years and over!!High school graduate or higher'
                    ], inplace=True)
s2018.rename(columns={
    'Estimate!!Total!!Population 18 to 24 years': f'population18to24yo_{x}',
    'Estimate!!Total!!Population 18 to 24 years!!High school graduate (includes equivalency)': f'population18to24yoHighSchoolGrad_{x}',
    "Estimate!!Total!!Population 18 to 24 years!!Some college or associate's degree": f'population18to24yoSomeCollege_{x}',
    "Estimate!!Total!!Population 18 to 24 years!!Bachelor's degree or higher": f'population18to24yoBachelorsOrHigher_{x}',
    'Estimate!!Total!!Population 25 years and over': f'population25yoAndOver_{x}',
    "Estimate!!Total!!Population 25 years and over!!High school graduate (includes equivalency)": f'population25yoAndOverHighSchoolGrad_{x}',
    "Estimate!!Total!!Population 25 years and over!!Some college, no degree": f'population25yoAndOverSomeCollege_{x}',
    "Estimate!!Total!!Population 25 years and over!!Associate's degree": f'population25yoAndOverAssociates_{x}',
    "Estimate!!Total!!Population 25 years and over!!Bachelor's degree": f'population25yoAndOverBachelors_{x}',
    "Estimate!!Total!!Population 25 years and over!!Graduate or professional degree": f'population25yoAndOverGraduateOrProfessional_{x}'}, inplace=True)

s2018[f"population18to24yoSomeCollegeOrHigher_{x}"] = s2018[f"population18to24yoSomeCollege_{x}"] + s2018[f"population18to24yoBachelorsOrHigher_{x}"]
s2018[f"population25yoAndOverSomeCollegeOrHigher_{x}"] = s2018[f'population25yoAndOverSomeCollege_{x}'] + s2018[f"population25yoAndOverAssociates_{x}"] + s2018[f"population25yoAndOverBachelors_{x}"] + s2018[f"population25yoAndOverGraduateOrProfessional_{x}"]
s2018.drop(columns=[f'population18to24yoSomeCollege_{x}', f"population18to24yoBachelorsOrHigher_{x}", f'population25yoAndOverSomeCollege_{x}', f"population25yoAndOverAssociates_{x}", f"population25yoAndOverBachelors_{x}", f"population25yoAndOverGraduateOrProfessional_{x}"], inplace=True)

s2018.to_csv(f"populationData/sll2018_new.csv", index=False)

x = 2019
for y in [s2019, s2020, s2021, s2022, s2023]:
    y.drop(columns=[f'{prename}Population 18 to 24 years!!Less than high school graduate',
                    f'{prename}Population 25 years and over!!Less than 9th grade',
                    f'{prename}Population 25 years and over!!9th to 12th grade, no diploma',
                    f'{prename}Population 25 years and over!!High school graduate or higher'
                    ], inplace=True)
    y.rename(columns={
        f'{prename}Population 18 to 24 years': f'population18to24yo_{x}',
        f'{prename}Population 18 to 24 years!!High school graduate (includes equivalency)': f'population18to24yoHighSchoolGrad_{x}',
        f"{prename}Population 18 to 24 years!!Some college or associate's degree": f'population18to24yoSomeCollege_{x}',
        f"{prename}Population 18 to 24 years!!Bachelor's degree or higher": f'population18to24yoBachelorsOrHigher_{x}',
        f'{prename}Population 25 years and over': f'population25yoAndOver_{x}',
        f"{prename}Population 25 years and over!!High school graduate (includes equivalency)": f'population25yoAndOverHighSchoolGrad_{x}',
        f"{prename}Population 25 years and over!!Some college, no degree": f'population25yoAndOverSomeCollege_{x}',
        f"{prename}Population 25 years and over!!Associate's degree": f'population25yoAndOverAssociates_{x}',
        f"{prename}Population 25 years and over!!Bachelor's degree": f'population25yoAndOverBachelors_{x}',
        f"{prename}Population 25 years and over!!Graduate or professional degree": f'population25yoAndOverGraduateOrProfessional_{x}'}, inplace=True)

    y[f"population18to24yoSomeCollegeOrHigher_{x}"] = y[f"population18to24yoSomeCollege_{x}"] + y[f"population18to24yoBachelorsOrHigher_{x}"]
    y[f"population25yoAndOverSomeCollegeOrHigher_{x}"] = y[f'population25yoAndOverSomeCollege_{x}'] + y[f"population25yoAndOverAssociates_{x}"] + y[f"population25yoAndOverBachelors_{x}"] + y[f"population25yoAndOverGraduateOrProfessional_{x}"]
    y.drop(columns=[f'population18to24yoSomeCollege_{x}', f"population18to24yoBachelorsOrHigher_{x}", f'population25yoAndOverSomeCollege_{x}', f"population25yoAndOverAssociates_{x}", f"population25yoAndOverBachelors_{x}", f"population25yoAndOverGraduateOrProfessional_{x}"], inplace=True)

    y.to_csv(f"populationData/sll{x}_new.csv", index=False)
    x += 1

In [271]:
sl2018_new = pd.read_csv("populationData/sll2018_new.csv")
sl2019_new = pd.read_csv("populationData/sll2019_new.csv")
sl2020_new = pd.read_csv("populationData/sll2020_new.csv")
sl2021_new = pd.read_csv("populationData/sll2021_new.csv")
sl2022_new = pd.read_csv("populationData/sll2022_new.csv")
sl2023_new = pd.read_csv("populationData/sll2023_new.csv")
states = pd.read_excel("states_final/sepehr_states.xlsx")


dfs = [sl2018_new, sl2019_new, sl2020_new, sl2021_new, sl2022_new, sl2023_new]
for df in dfs:
    df.drop(columns=['stateAbbr',], inplace=True)
merged_df = dfs[0]
for df in dfs[1:]:
    merged_df = pd.merge(merged_df, df, on='state', how='outer')

states = states.merge(merged_df, on='state', how='outer')
states.to_excel("states_final/sepehr_states.xlsx", index=False)

In [285]:
sl2018 = pd.read_csv("ACSST5Y2018.S1501-Data.csv", skiprows=1)
sl2019 = pd.read_csv("ACSST5Y2019.S1501-Data.csv", skiprows=1)
sl2020 = pd.read_csv("ACSST5Y2020.S1501-Data.csv", skiprows=1)
sl2021 = pd.read_csv("ACSST5Y2021.S1501-Data.csv", skiprows=1)
sl2022 = pd.read_csv("ACSST5Y2022.S1501-Data.csv", skiprows=1)
sl2023 = pd.read_csv("ACSST5Y2023.S1501-Data.csv", skiprows=1)

for df in [sl2018, sl2019, sl2020, sl2021, sl2022, sl2023]:
    df.drop(columns=[col for col in df.columns if col.startswith("Margin of Error")], inplace=True)
    df.drop(columns=['Geography'], inplace=True)
    df.rename(columns={'Geographic Area Name': 'state'}, inplace=True)

for df in [sl2018, sl2019, sl2020, sl2021, sl2022, sl2023]:
    columns_to_drop = []
    for col in df.columns:
        if df[col].astype(str).str.contains(r'\(X\)').any():
            columns_to_drop.append(col)
        # drop columns that start with 'Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population'
        if col.startswith('Estimate!!Total!!Population'):
            columns_to_drop.append(col)
        if col.startswith('Estimate!!Total!!AGE BY EDUCATIONAL ATTAINMENT!!Population'):
            columns_to_drop.append(col)

    if columns_to_drop:
        df.drop(columns=columns_to_drop, inplace=True)

sl2019

,state,Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone,Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!High school graduate or higher,Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone!!Bachelor's degree or higher,"Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino","Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!High school graduate or higher","Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!White alone, not Hispanic or Latino!!Bachelor's degree or higher",Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone,Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!High school graduate or higher,Estimate!!Total!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Black alone!!Bachelor's degree or higher,...,Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Some other race alone!!Bachelor's degree or higher,Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!High school graduate or higher,Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Two or more races!!Bachelor's degree or higher,Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!High school graduate or higher,Estimate!!Percent Female!!RACE AND HISPANIC OR LATINO ORIGIN BY EDUCATIONAL ATTAINMENT!!Hispanic or Latino Origin!!Bachelor's degree or higher,Estimate!!Percent Female!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Less than high school graduate,Estimate!!Percent Female!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!High school graduate (includes equivalency),Estimate!!Percent Female!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Some college or associate's degree,Estimate!!Percent Female!!POVERTY RATE FOR THE POPULATION 25 YEARS AND OVER FOR WHOM POVERTY STATUS IS DETERMINED BY EDUCATIONAL ATTAINMENT LEVEL!!Bachelor's degree or higher,Unnamed: 770
0,Alabama,2352070,2064499,655670,2288814,2022536,643416,831045,691558,149196,...,12.2,85.2,29.2,64.6,17.4,34.1,19.0,13.8,4.9,NaN
1,Alaska,335250,320393,118983,319243,306039,115292,15401,14452,3199,...,17.4,94.6,27.8,87.0,24.7,21.8,15.7,7.8,3.1,NaN
2,Arizona,3802974,3383816,1171529,2930339,2763763,1047452,196606,176368,49892,...,11.4,88.6,30.9,71.1,14.4,30.0,16.5,11.5,5.4,NaN
3,Arkansas,1607044,1416329,390836,1542183,1376758,382965,281226,235207,44375,...,9.2,87.0,22.5,60.0,11.4,32.3,17.9,14.6,4.7,NaN
4,California,16318050,14008652,5679216,11199800,10632033,4925920,1544982,1387057,397147,...,11.3,89.1,36.5,65.3,14.6,24.9,15.7,11.0,5.2,NaN
5,Colorado,3291935,3061847,1403170,2795761,2699118,1320663,149058,134458,39191,...,14.5,91.6,38.9,74.0,17.6,23.7,12.6,10.0,4.4,NaN
6,Connecticut,1959844,1816500,820444,1771370,1673311,780792,246556,213505,52638,...,13.1,87.7,32.8,74.2,18.9,27.3,12.8,9.0,4.0,NaN
7,Delaware,483942,439656,160762,451436,419413,156049,136568,121918,31861,...,13.8,90.8,32.1,66.3,18.0,25.1,14.5,10.3,3.7,NaN
8,District of Columbia,219790,215642,196752,198177,197107,182075,218421,188506,59718,...,29.9,93.8,74.9,74.9,49.5,38.2,26.9,18.8,5.5,NaN
9,Florida,11715824,10496811,3684564,8744092,8121633,2926992,2128338,1770884,410209,...,21.4,88.3,32.8,80.6,26.1,28.4,16.5,11.4,6.2,NaN
10,Georgia,4240615,3755666,1439365,3916069,3546252,1374354,2079101,1801944,498202,...,14.9,89.0,38.1,66.0,20.0,31.6,18.0,12.8,4.7,NaN
11,Hawaii,267334,258154,118435,242659,235237,111985,17429,16702,5195,...,33.0,95.0,27.2,91.6,24.9,19.1,12.6,8.7,4.7,NaN
12,Idaho,1023717,941884,288873,956115,896388,281315,5476,4946,1445,...,6.6,91.2,30.7,67.1,10.5,25.1,15.5,10.9,5.2,NaN
13,Illinois,6440803,5892549,2338948,5706930,5375279,2214175,1165513,1008393,252398,...,12.1,90.5,39.9,69.1,16.8,26.0,15.0,11.6,4.6,NaN
14,Indiana,3808655,3420510,1024515,3666437,3323434,1000716,380821,327130,69068,...,10.3,88.4,29.8,68.7,15.4,27.2,13.9,11.5,4.3,NaN
15,Iowa,1933642,1800596,556268,1868280,1758425,547087,62522,52505,10642,...,13.5,89.1,28.7,64.5,14.2,26.1,13.1,9.6,3.8,NaN
16,Kansas,1651688,1523743,569223,1530206,1443087,551488,103225,90495,20859,...,11.0,91.8,30.7,67.2,14.9,25.9,14.0,10.6,3.5,NaN
17,Kentucky,2689429,2327442,658308,2635316,2286952,646558,223886,193008,38237,...,15.7,88.4,27.2,73.4,21.4,36.1,18.7,14.7,4.9,NaN
18,Louisiana,2042165,1801939,567613,1948934,1732114,549393,932703,746737,146048,...,14.5,88.3,29.3,74.7,19.5,39.8,21.1,15.9,5.5,NaN
19,Maine,932999,866994,297686,924484,859272,294463,9276,7655,2402,...,38.2,89.2,28.3,91.5,37.5,29.5,16.5,10.8,4.3,NaN
20,Maryland,2408728,2226885,1067638,2248349,2108543,1019842,1206302,1088488,362557,...,15.4,92.5,45.4,68.7,24.0,23.1,13.0,8.6,3.4,NaN
21,Massachusetts,3862603,3586344,1751903,3612618,3401991,1693739,329719,282063,86689,...,15.6,82.4,37.1,72.5,21.0,27.6,14.4,10.1,4.4,NaN
22,Michigan,5519435,5078346,1655307,5346396,4947978,1620491,873014,751986,152414,...,15.2,88.3,28.2,75.1,19.8,31.7,16.1,12.0,4.5,NaN
23,Minnesota,3261851,3105277,1215044,3178001,3045444,1197495,193678,157429,41073,...,14.4,92.3,33.1,69.2,19.0,28.4,12.1,8.5,3.2,NaN
24,Mississippi,1219736,1070426,312887,1191300,1050128,307759,695072,554025,107052,...,15.6,87.9,29.2,69.3,18.7,37.7,23.6,16.7,5.7,NaN
25,Missouri,3509529,3183341,1055270,3424173,3117159,1034486,438904,379096,81438,...,17.5,90.1,31.2,75.5,23.7,30.2,15.3,11.7,4.2,NaN
26,Montana,659330,620639,217181,646116,609373,214382,3051,2726,1013,...,21.2,93.4,32.3,85.1,24.0,26.6,16.1,11.6,5.4,NaN
27,Nebraska,1120853,1039649,366604,1046093,994989,357010,53373,46233,11364,...,9.9,88.9,29.4,63.0,13.1,26.8,13.0,9.5,3.5,NaN
28,Nevada,1406086,1250583,367550,1132972,1064050,335732,174806,156531,31165,...,8.9,91.1,26.6,66.6,11.2,23.6,14.7,10.9,5.8,NaN
29,New Hampshire,904518,845067,331788,884111,829193,326354,12526,10821,3351,...,26.6,89.5,31.5,82.6,27.1,20.1,10.4,7.3,3.4,NaN
30,New Jersey,4301081,3929397,1742532,3619142,3411828,1595507,793348,699530,192876,...,16.0,88.2,39.1,75.9,21.7,26.0,13.0,9.0,3.8,NaN
31,New Mexico,1080137,943184,325880,610960,579268,248489,27008,24406,7553,...,14.5,91.6,32.9,78.3,17.4,36.9,20.2,15.8,6.6,NaN
32,New York,8989215,8199521,3663881,7977098,7448550,3427518,2054954,1722496,494110,...,16.6,83.8,37.8,70.9,21.3,31.9,16.9,12.2,5.4,NaN
33,North Carolina,5007387,4493038,1702651,4718733,4313250,1650414,1435294,1228025,305462,...,12.9,91.1,35.3,64.3,17.6,32.2,17.2,12.5,4.5,NaN
34,North Dakota,442308,413869,136930,434504,407347,135416,11984,10384,2721,...,11.5,90.9,29.7,84.1,17.8,25.9,13.7,8.8,3.2,NaN
35,Ohio,6689453,6108177,1950297,6541263,5992811,1918101,911714,782773,156619,...,17.0,89.3,26.1,78.6,21.5,30.7,15.2,12.6,4.1,NaN
36,Oklahoma,1982654,1768057,535949,1853430,1685985,518981,177080,157769,34501,...,9.9,89.7,25.7,66.0,12.9,30.3,17.3,12.9,4.8,NaN
37,Oregon,2516278,2314123,854191,2333424,2192948,823423,50259,44223,13623,...,14.3,90.6,31.8,67.7,17.8,26.9,15.7,12.2,5.5,NaN
38,Pennsylvania,7459404,6854137,2418527,7176924,6644296,2363109,902460,779266,172891,...,12.8,88.2,31.8,74.2,18.3,27.9,14.0,10.9,4.3,NaN
39,Rhode Island,618658,560365,222344,569265,521535,214342,43097,36611,9125,...,11.3,84.6,28.3,75.2,15.1,28.9,14.6,10.3,4.6,NaN
40,South Carolina,2418267,2175600,786478,2324975,2111925,769475,870680,718265,137158,...,14.3,88.5,27.1,69.7,19.7,33.4,17.5,12.5,4.5,NaN
41,South Dakota,505575,473283,154049,495899,465975,152226,9371,7396,1541,...,20.6,90.9,25.6,73.1,17.7,33.8,14.7,10.2,4.2,NaN
42,Tennessee,3678988,3244365,1039987,3553558,3162903,1018119,710073,610577,144860,...,15.7,87.8,29.8,65.8,17.7,31.9,17.3,12.1,4.6,NaN
43,Texas,13626034,11442651,4102590,8572364,8052661,3315692,2165688,1944160,532033,...,12.3,87.9,32.8,67.6,16.3,28.9,16.4,11.1,4.5,NaN
44,Utah,1607447,1513169,567713,1483251,1418585,546454,18531,16221,4524,...,11.5,92.4,35.8,72.3,15.0,22.0,11.3,7.6,4.5,NaN
45,Vermont,420621,391550,159755,416037,387515,158001,4282,3805,1536,...,45.8,89.9,44.3,87.1,42.1,29.3,13.9,10.4,4.7,NaN
46,Virginia,4046712,3699416,1667632,3767293,3489000,1588727,1072984,922275,261142,...,20.9,90.7,41.2,74.2,27.0,25.7,13.8,9.4,3.5,NaN
47,Washington,4008044,3742072,1454437,3750649,3560627,1403896,180350,161990,45394,...,13.0,92.9,34.2,69.1,18.1,24.5,13.2,10.3,4.3,NaN
48,West Virginia,1214592,1054606,247984,1203437,1045064,245265,43749,39222,6645,...,22.4,89.3,25.8,86.1,22.7,32.6,18.6,14.3,4.8,NaN
49,Wisconsin,3502519,3277337,1088320,3381290,3190207,1067774,212316,177272,31016,...,11.6,90.9,33.1,71.0,16.9,27.1,12.7,9.7,3.7,NaN
50,Wyoming,363476,340177,101419,340666,323108,98641,3206,2969,944,...,13.3,92.2,21.4,76.9,14.6,23.7,14.1,9.2,4.8,NaN
51,Puerto Rico,1558162,1209947,433579,23045,19903,8769,281690,210019,57108,...,26.9,79.9,30.2,78.5,29.8,63.1,54.8,42.0,17.4,NaN

In [ ]:
colleges = pd.read_excel("colleges_final/sepehr_colleges.xlsx")
states = pd.read_excel("states_final/sepehr_states.xlsx")
merged = colleges.merge(states, on='stateAbbr', how='outer')

merged = merged[merged['name'].notna()]
merged = merged.sort_values(by='index')
merged = merged.drop(columns=['state_y'])
merged.rename(columns={'state_x': 'state'}, inplace=True)
merged = merged[merged['index'] != 2]
merged = merged.drop(columns=['UID', 'zip', 'UID', 'reasonForClosure', 'mergingInstitutionZip', 'mergingInstitution'])

merged

,index,name,yearEstablished,state,stateAbbr,locationType,locationTypeKind,Public/ Private,type,level,...,population25yoAndOver_2022,population25yoAndOverHighSchoolGrad_2022,population18to24yoSomeCollegeOrHigher_2022,population25yoAndOverSomeCollegeOrHigher_2022,population18to24yo_2023,population18to24yoHighSchoolGrad_2023,population25yoAndOver_2023,population25yoAndOverHighSchoolGrad_2023,population18to24yoSomeCollegeOrHigher_2023,population25yoAndOverSomeCollegeOrHigher_2023
86,0.0,Alderson Broaddus University,1871.0,West Virginia,WV,Rural,Distant,Private,Nonprofit,4-year,...,1271529.0,502333.0,79342.0,622195.0,155849.0,63691.0,1269202.0,501118.0,75699.0,623530.0
51,1.0,Alliance University (Formerly Nyack College),1882.0,New York,NY,City,Large,Private,Nonprofit,4-year,...,14021808.0,3494392.0,1129113.0,8786629.0,1766904.0,520830.0,13996138.0,3437438.0,1074524.0,8860163.0
26,3.0,Ancilla College,1937.0,Indiana,IN,Rural,Distant,Private,Nonprofit,2-year,...,4532091.0,1495818.0,334872.0,2583019.0,656377.0,244351.0,4559304.0,1496214.0,319682.0,2617439.0
31,4.0,Becker College,1784.0,Massachusetts,MA,City,Midsize,Private,Nonprofit,4-year,...,4920101.0,1127899.0,421962.0,3360615.0,678357.0,206559.0,4945630.0,1129802.0,408550.0,3390619.0
48,5.0,Bloomfield College,1868.0,New Jersey,NJ,Suburb,Large,Private,Nonprofit,4-year,...,6427003.0,1674625.0,483882.0,4150637.0,776472.0,239785.0,6459220.0,1662983.0,459815.0,4195501.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,61.0,Eastern Nazarene College,1900.0,Massachusetts,MA,Suburb,Large,Private,Nonprofit,4-year,...,4920101.0,1127899.0,421962.0,3360615.0,678357.0,206559.0,4945630.0,1129802.0,408550.0,3390619.0
41,62.0,Cox College,1907.0,Missouri,MO,City,Midsize,Private,Nonprofit,4-year,...,4199109.0,1280433.0,319886.0,2553713.0,564178.0,197116.0,4217432.0,1279442.0,305441.0,2583258.0
85,63.0,University of Wisconsin–Platteville Richland,1967.0,Wisconsin,WI,Town,Distant,Public,Nonprofit,4-year,...,4047831.0,1211254.0,312313.0,2557172.0,548130.0,194507.0,4069583.0,1207407.0,296909.0,2592745.0
34,64.0,Maryland University of Integrative Health,1974.0,Maryland,MD,Suburb,Large,Private,Nonprofit,graduate school,...,4260095.0,1012724.0,303576.0,2863454.0,521989.0,171308.0,4272813.0,1014175.0,286670.0,2875937.0
74,65.0,B. H. Carroll Theological Seminary,2004.0,Texas,TX,City,Midsize,Private,Nonprofit,seminary,...,18910948.0,4626129.0,1497077.0,11492485.0,2863182.0,1019944.0,19294631.0,4691708.0,1454341.0,11843200.0

In [438]:
df = pd.read_excel("dataset1.xlsx")
df.drop(columns=['index'], inplace=True)

for x in ['religionAffiliation', 
          'specialDemographic', 
          'mergingInstitutionPopulation', 
          'mergingInstitutionType', 
          'mergingInstitutionLocationType', 
          'mergingInstitutionReligiousAffiliation',]:
    df[x] = df[x].fillna('None')

n = "Median"
for x in ['Endowment', 'twoYearStudentShare' , 'fourYearStudentShare',
          'twoYearAppropriationsPerFTE', 'fourYearAppropriationsPerFTE',
          'twoYearNetTuitionRevenuePerFTE', 'fourYearNetTuitionRevenuePerFTE',
          'population18to24yo', 'population25yoAndOver',
          'population18to24yoHighSchoolGrad', 'population25yoAndOverHighSchoolGrad',
          'population18to24yoSomeCollegeOrHigher', 'population25yoAndOverSomeCollegeOrHigher',
          'perCapitaPersonalIncome']:
    m = [col for col in df.columns if col.startswith(x)]
    df[x + n] = df[m].replace(0, np.nan).median(axis=1)

for y in [2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    df.drop(columns=[f"EndowmentMedian{y}", f"perCapitaPersonalIncome{y}"], inplace=True)

for y in [2019, 2020, 2021, 2022, 2023, 2024]:
    for x in ['twoYearStudentShare' , 'fourYearStudentShare',
          'twoYearAppropriationsPerFTE', 'fourYearAppropriationsPerFTE',
          'twoYearNetTuitionRevenuePerFTE', 'fourYearNetTuitionRevenuePerFTE']:
        df.drop(columns=[f"{x}{y}"], inplace=True)

for y in [2018, 2019, 2020, 2021, 2022, 2023]:
    for i in ['population18to24yo', 'population25yoAndOver',
            'population18to24yoHighSchoolGrad', 'population25yoAndOverHighSchoolGrad',
            'population18to24yoSomeCollegeOrHigher', 'population25yoAndOverSomeCollegeOrHigher']:
        df.drop(columns=[f"{i}_{y}"], inplace=True)

df['totalEnrollment'] = df['totalEnrollment'].fillna(450).astype(int)
df['Carnegie Classification'] = df['Carnegie Classification'].fillna("Associate's Colleges").astype(str)
df['Carnegie Classification 2'] = df['Carnegie Classification 2'].fillna("Diverse Fields").astype(str)

x = "state"
df.rename(columns={'stateAbbr': 'stateAbbreviation', 
                   'Public/ Private': 'typeOwned',
                   'type': 'typeProfit',
                   'Carnegie Classification': 'carnegieAward',
                   'Carnegie Classification 2': 'carnegieProgram',
                   'Births': 'stateBirths',
                   'Total Population': 'statePopulation',
                   'Birth Rate': 'stateBirthRate',
                   'Female Population': 'stateFemalePopulation',
                   'Fertility Rate': 'stateFertilityRate',
                   'percentOfTotalBirths': 'statePercentOfTotalBirths',
                   'unemploymentRate': 'stateUnemploymentRate',
                   'highSchoolACGR': 'stateHighSchoolACGR',
                   'EndowmentMedian': 'endowmentMedian',
                   'twoYearStudentShareMedian': 'stateTwoYearStudentShareMedian',
                   'fourYearStudentShareMedian': 'stateFourYearStudentShareMedian',
                   'twoYearAppropriationsPerFTEMedian': 'stateTwoYearAppropriationsPerFTEMedian',
                   'fourYearAppropriationsPerFTEMedian': 'stateFourYearAppropriationsPerFTEMedian',
                   'twoYearNetTuitionRevenuePerFTEMedian': 'stateTwoYearNetTuitionRevenuePerFTEMedian',
                   'fourYearNetTuitionRevenuePerFTEMedian': 'stateFourYearNetTuitionRevenuePerFTEMedian',
                   'population18to24yoMedian': 'statePopulation18to24yoMedian',
                   'population25yoAndOverMedian': 'statePopulation25yoAndOverMedian',
                   'population18to24yoHighSchoolGradMedian': 'statePopulation18to24yoHighSchoolGradMedian',
                   'population25yoAndOverHighSchoolGradMedian': 'statePopulation25yoAndOverHighSchoolGradMedian',
                   'population18to24yoSomeCollegeOrHigherMedian': 'statePopulation18to24yoSomeCollegeOrHigherMedian',
                   'population25yoAndOverSomeCollegeOrHigherMedian': 'statePopulation25yoAndOverSomeCollegeOrHigherMedian',
                   'perCapitaPersonalIncomeMedian': 'statePerCapitaPersonalIncomeMedian',
                   'hasUndergrad': 'hasUndergraduate',
                   'hasGrad': 'hasGraduate'},
                   inplace=True)


for x in ['hasUndergraduate', 'hasGraduate', 'hasReligionAffiliation', 
          'hasSpecialDemographic', 'reasonFinancial', 'reasonEnrollment', 
          'reasonPandemic', 'reasonMutualBenefit']:
    df[x] = df[x].replace({0: 'FALSE', 1: 'TRUE'})

df['isMerged'] = df['isMerged'].replace({'No': 'FALSE', 
                                         'Yes': 'TRUE',
                                         'Failed': 'FAILED'})

df.to_excel("ready_for_modeling_1.xlsx", index=False)
df.to_csv("ready_for_modeling_1.csv", index=False)
df

,name,yearEstablished,state,stateAbbreviation,locationType,locationTypeKind,typeOwned,typeProfit,level,hasUndergraduate,...,stateFourYearAppropriationsPerFTEMedian,stateTwoYearNetTuitionRevenuePerFTEMedian,stateFourYearNetTuitionRevenuePerFTEMedian,statePopulation18to24yoMedian,statePopulation25yoAndOverMedian,statePopulation18to24yoHighSchoolGradMedian,statePopulation25yoAndOverHighSchoolGradMedian,statePopulation18to24yoSomeCollegeOrHigherMedian,statePopulation25yoAndOverSomeCollegeOrHigherMedian,statePerCapitaPersonalIncomeMedian
0,Alderson Broaddus University,1871,West Virginia,WV,Rural,Distant,Private,Nonprofit,4-year,TRUE,...,5634.822870,3552.459646,8324.661159,79926.5,612398.0,60470.5,512687.5,79926.5,612398.0,51075.0
1,Alliance University (Formerly Nyack College),1882,New York,NY,City,Large,Private,Nonprofit,4-year,TRUE,...,14514.215742,4968.842112,7115.076497,1126667.0,8594351.5,497059.0,3517833.0,1126667.0,8594351.5,78501.0
2,Ancilla College,1937,Indiana,IN,Rural,Distant,Private,Nonprofit,2-year,TRUE,...,6263.361828,3082.258414,12604.847801,337715.5,2531049.0,228011.0,1484195.5,337715.5,2531049.0,59797.0
3,Becker College,1784,Massachusetts,MA,City,Midsize,Private,Nonprofit,4-year,TRUE,...,12392.121586,3823.431201,8164.798013,433897.0,3292373.5,194673.5,1135221.5,433897.0,3292373.5,85585.0
4,Bloomfield College,1868,New Jersey,NJ,Suburb,Large,Private,Nonprofit,4-year,TRUE,...,10431.614347,3230.813658,11047.054665,469274.0,4014028.0,225395.0,1672783.5,469274.0,4014028.0,78329.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Eastern Nazarene College,1900,Massachusetts,MA,Suburb,Large,Private,Nonprofit,4-year,TRUE,...,12392.121586,3823.431201,8164.798013,433897.0,3292373.5,194673.5,1135221.5,433897.0,3292373.5,85585.0
61,Cox College,1907,Missouri,MO,City,Midsize,Private,Nonprofit,4-year,TRUE,...,7348.161174,3158.651054,8110.752686,318494.5,2520719.5,185163.0,1276294.0,318494.5,2520719.5,59202.0
62,University of Wisconsin–Platteville Richland,1967,Wisconsin,WI,Town,Distant,Public,Nonprofit,4-year,TRUE,...,6027.145088,2499.698379,9046.426414,313717.5,2507124.5,179977.5,1210502.5,313717.5,2507124.5,62713.0
63,Maryland University of Integrative Health,1974,Maryland,MD,Suburb,Large,Private,Nonprofit,graduate school,FALSE,...,10549.410879,4758.870615,11787.159727,306338.5,2800406.0,166310.5,1014233.5,306338.5,2800406.0,71897.0
64,B. H. Carroll Theological Seminary,2004,Texas,TX,City,Midsize,Private,Nonprofit,seminary,FALSE,...,6184.249838,2058.177590,11149.697674,1456559.0,11117876.0,955436.0,4561326.5,1456559.0,11117876.0,62015.0