In [59]:
import pandas as pd
import numpy as np
import openpyxl

In [60]:
df = pd.read_excel("sepehr_colleges.xlsx")
df

,index,UID,name,yearEstablished,state,stateAbbr,zip,locationType,locationTypeKind,Public/ Private,...,reasonPandemic,reasonMutualBenefit,reasonForClosure,EndowmentMedian2018,EndowmentMedian2019,EndowmentMedian2020,EndowmentMedian2021,EndowmentMedian2022,EndowmentMedian2023,EndowmentMedian2024
0,0,237118.0,Alderson Broaddus University,1871,West Virginia,NaN,26416,Rural,Distant,Private,...,0,0,Financial,18150386.0,17367369.0,18456342.0,18685108.0,16256321.0,0.000000e+00,0.0
1,1,194161.0,Alliance University (Formerly Nyack College),1882,New York,NaN,10004,City,Large,Private,...,0,0,Accreditation Issues,4255808.0,4393633.0,4577611.0,3736796.0,622193.0,0.000000e+00,0.0
2,2,241100.0,American University of Puerto Rico,1963,Puerto Rico,NaN,960,City,Midsize,Private,...,0,0,Financial,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,497833.0,Ancilla College,1937,Indiana,NaN,46513,Rural,Distant,Private,...,0,1,Mutual Benefit,4110469.0,4351295.0,4394680.0,0.0,0.0,0.000000e+00,0.0
4,4,164720.0,Becker College,1784,Massachusetts,NaN,1609,City,Midsize,Private,...,1,0,Pandemic; Enrollment,4962182.0,5116037.0,5024459.0,0.0,0.0,0.000000e+00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,61,165644.0,Eastern Nazarene College,1900,Massachusetts,NaN,2170,Suburb,Large,Private,...,0,0,Financial,19548765.0,19545720.0,18753406.0,19431518.0,19100262.0,1.937957e+07,0.0
62,62,176770.0,Cox College,1907,Missouri,NaN,65802,City,Midsize,Private,...,0,0,Financial,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,63,240462.0,University of Wisconsin–Platteville Richland,1967,Wisconsin,NaN,53581,Town,Distant,Public,...,0,0,Enrollment,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,64,164085.0,Maryland University of Integrative Health,1974,Maryland,NaN,20723,Suburb,Large,Private,...,0,1,Mutual Benefit,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,65,NaN,B. H. Carroll Theological Seminary,2004,Texas,NaN,76010,City,Midsize,Private,...,0,1,Mutual Benefit,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
stateAbbri = {"Alabama": "AL",
             "Alaska": "AK",
             "Arizona": "AZ",
             "Arkansas": "AR",
             "California": "CA",
             "Colorado": "CO",
             "Connecticut": "CT",
             "Delaware": "DE",
             "Florida": "FL",
             "Georgia": "GA",
             "Hawaii": "HI",
             "Idaho": "ID",
             "Illinois": "IL",
             "Indiana": "IN",
             "Iowa": "IA",
             "Kansas": "KS",
             "Kentucky": "KY",
             "Louisiana": "LA",
             "Maine": "ME",
             "Maryland": "MD",
             "Massachusetts": "MA",
             "Michigan": "MI",
             "Minnesota": "MN",
             "Mississippi": "MS",
             "Missouri": "MO",
             "Montana": "MT",
             "Nebraska": "NE",
             "Nevada": "NV",
             "New Hampshire": "NH",
             "New Jersey": "NJ",
             "New Mexico": "NM",
             "New York": "NY",
             "North Carolina": "NC",
             "North Dakota": "ND",
             "Ohio": "OH",
             "Oklahoma": "OK",
             "Oregon": "OR",
             "Pennsylvania": "PA",
             "Rhode Island": "RI",
             "South Carolina": "SC",
             "South Dakota": "SD",
             "Tennessee": "TN",
             "Texas": "TX",
             "Utah": "UT",
             "Vermont": "VT",
             "Virginia": "VA",
             "Washington": "WA",
             "West Virginia": "WV",
             "Wisconsin": "WI",
             "Wyoming": "WY",   
             "District of Columbia": "DC",
             "American Samoa": "AS",
             "Guam": "GU",
             "Northern Mariana Islands": "MP",
             "Puerto Rico": "PR",
             "U.S. Virgin Islands": "VI",
             "Federated States of Micronesia": "FM",
             "Marshall Islands": "MH",
             "Palau": "PW",
             "Armed Forces Americas": "AA",
             "Armed Forces Europe": "AE",
             "Armed Forces Pacific": "AP",
             "Alberta": "AB",
             "British Columbia": "BC"}

df['stateAbbr'] = df['state'].map(stateAbbri)

In [62]:
for x in ['yearEstablished', 'zip', 'UID', 'index', 'totalEnrollment', 'mergingInstitutionPopulation', 'mergingInstitutionZip']:
    df[x] = pd.to_numeric(df[x], errors='coerce').astype('Int64')

for x in df.columns:
    if x.startswith('Endowment'):
        df[x] = pd.to_numeric(df[x], errors='coerce').astype('float')

In [63]:
for x in ['mergingInstitution',
        #   'mergingInstitutionPopulation',
          'mergingInstitutionType',
        #   'mergingInstitutionZip',
          'mergingInstitutionLocationType',
          'mergingInstitutionReligiousAffiliation',
          'specialDemographic',
          'religionAffiliation']:
    df[x] = df[x].fillna("NA").astype(str)

In [ ]:
df.to_excel("sepehr_colleges_cleaned.xlsx", index=False)

In [102]:
states = pd.read_excel("sepehr_states.xlsx")
states

                   state stateAbbr     region
0                Alabama        AL      South
1                 Alaska        AK       West
2                Arizona        AZ       West
3               Arkansas        AR      South
4             California        CA       West
5               Colorado        CO       West
6            Connecticut        CT  Northeast
7               Delaware        DE      South
8   District of Columbia        DC      South
9                Florida        FL      South
10               Georgia        GA      South
11                Hawaii        HI       West
12                 Idaho        ID       West
13              Illinois        IL    Midwest
14               Indiana        IN    Midwest
15                  Iowa        IA    Midwest
16                Kansas        KS    Midwest
17              Kentucky        KY      South
18             Louisiana        LA      South
19                 Maine        ME  Northeast
20              Maryland        MD      South
21         Massachusetts        MA  Northeast
22              Michigan        MI    Midwest
23             Minnesota        MN    Midwest
24           Mississippi        MS      South
25              Missouri        MO    Midwest
26               Montana        MT       West
27              Nebraska        NE    Midwest
28                Nevada        NV       West
29         New Hampshire        NH  Northeast
30            New Jersey        NJ  Northeast
31            New Mexico        NM       West
32              New York        NY  Northeast
33        North Carolina        NC      South
34          North Dakota        ND    Midwest
35                  Ohio        OH    Midwest
36              Oklahoma        OK      South
37                Oregon        OR       West
38          Pennsylvania        PA  Northeast
39          Rhode Island        RI  Northeast
40        South Carolina        SC      South
41          South Dakota        SD    Midwest
42             Tennessee        TN      South
43                 Texas        TX      South
44                  Utah        UT       West
45               Vermont        VT  Northeast
46              Virginia        VA      South
47            Washington        WA       West
48         West Virginia        WV      South
49             Wisconsin        WI    Midwest
50               Wyoming        WY       West

In [70]:
states['stateAbbr'] = states['state'].map(stateAbbri)
states.to_excel("sepehr_states.xlsx", index=False)

In [ ]:
df = pd.read_csv("natality.txt", sep='\t', header=0, quotechar='"')

df['% of Total Births'] = df['% of Total Births'].str.replace('%', '', regex=False).astype(float)

df['Census Region of Residence'] = df['Census Region of Residence'].str.replace('Census Region ', '', regex=False)
df['Census Region of Residence'] = df['Census Region of Residence'].str[2:]

df = df.drop(columns=['State of Residence Code', 'Census Region of Residence Code'])

In [86]:
df.to_excel("natality_cleaned.xlsx", index=False)

In [94]:
stateRegions = {
    "Alabama": "South",
    "Alaska": "West",
    "Arizona": "West",
    "Arkansas": "South",
    "California": "West",
    "Colorado": "West",
    "Connecticut": "Northeast",
    "Delaware": "South",
    "Florida": "South",
    "Georgia": "South",
    "Hawaii": "West",
    "Idaho": "West",
    "Illinois": "Midwest",
    "Indiana": "Midwest",
    "Iowa": "Midwest",
    "Kansas": "Midwest",
    "Kentucky": "South",
    "Louisiana": "South",
    "Maine": "Northeast",
    "Maryland": "South",
    "Massachusetts": "Northeast",
    "Michigan": "Midwest",
    "Minnesota": "Midwest",
    "Mississippi": "South",
    "Missouri": "Midwest",
    "Montana": "West",
    "Nebraska": "Midwest",
    "Nevada": "West",
    "New Hampshire": "Northeast",
    "New Jersey": "Northeast",
    "New Mexico": "West",
    "New York": "Northeast",
    "North Carolina": "South",
    "North Dakota": "Midwest",
    "Ohio": "Midwest",
    "Oklahoma": "South",
    "Oregon": "West",
    "Pennsylvania": "Northeast",
    "Rhode Island": "Northeast",
    "South Carolina": "South",
    "South Dakota": "Midwest",
    "Tennessee": "South",
    "Texas": "South",
    "Utah": "West",
    "Vermont": "Northeast",
    "Virginia": "South",
    "Washington": "West",
    "West Virginia": "South",
    "Wisconsin": "Midwest",
    "Wyoming": "West",
    "District of Columbia": "South",
    "American Samoa": "West",
    "Guam": "West",
    "Northern Mariana Islands": "West",
    "Puerto Rico": "South"
}

states['region'] = states['state'].map(stateRegions)
states.to_excel("sepehr_states.xlsx", index=False)

In [ ]:
nat = pd.read_excel("natality_cleaned.xlsx")
nat.to_excel("natality.xlsx", index=False)

,Census Region of Residence,State of Residence,Births,Total Population,Birth Rate,Female Population,Fertility Rate,% of Total Births
0,Northeast,Connecticut,208004,21543936,9.65,4081181,50.97,0.94
1,Northeast,Maine,71355,8186066,8.72,1430071,49.90,0.32
2,Northeast,Massachusetts,409468,41656322,9.83,8419406,48.63,1.85
3,Northeast,New Hampshire,72263,8268721,8.74,1497455,48.26,0.33
4,Northeast,Rhode Island,61320,6459107,9.49,1273562,48.15,0.28
5,Northeast,Vermont,31691,3813733,8.31,704655,44.97,0.14
6,Northeast,New Jersey,604153,54492751,11.09,10293179,58.69,2.74
7,Northeast,New York,1279243,117416826,10.89,23255110,55.01,5.79
8,Northeast,Pennsylvania,790421,77290050,10.23,14466075,54.64,3.58
9,Northeast,TOTAL,3527918,339127512,10.40,65420694,53.93,15.98
10,Midwest,Illinois,803600,75803621,10.60,14934897,53.81,3.64
11,Midwest,Indiana,479716,40680271,11.79,7927380,60.51,2.17
12,Midwest,Michigan,628417,60071512,10.46,11321208,55.51,2.85
13,Midwest,Ohio,783704,70393769,11.13,13365288,58.64,3.55
14,Midwest,Wisconsin,369546,35168059,10.51,6601801,55.98,1.67
15,Midwest,Iowa,220941,19075376,11.58,3613047,61.15,1.00
16,Midwest,Kansas,209203,17550902,11.92,3396536,61.59,0.95
17,Midwest,Minnesota,386969,34070642,11.36,6552584,59.06,1.75
18,Midwest,Missouri,420242,36957728,11.37,7119267,59.03,1.90
19,Midwest,Nebraska,147599,11711222,12.60,2272581,64.95,0.67
20,Midwest,North Dakota,60475,4625583,13.07,906297,66.73,0.27
21,Midwest,South Dakota,68073,5384129,12.64,992778,68.57,0.31
22,Midwest,TOTAL,4578485,411492814,11.13,79003664,57.95,20.73
23,South,Delaware,63300,5981414,10.58,1108192,57.12,0.29
24,South,District of Columbia,51796,4141845,12.51,1112736,46.55,0.23
25,South,Florida,1313318,131147051,10.01,23772622,55.24,5.95
26,South,Georgia,750339,64588584,11.62,13290576,56.46,3.40
27,South,Maryland,412473,36654242,11.25,7192645,57.35,1.87
28,South,North Carolina,716519,63558153,11.27,12498057,57.33,3.24
29,South,South Carolina,342145,31297775,10.93,5998759,57.04,1.55
30,South,Virginia,576125,51685358,11.15,10227966,56.33,2.61
31,South,West Virginia,104440,10710952,9.75,1888053,55.32,0.47
32,South,Alabama,348084,29935229,11.63,5816314,59.85,1.58
33,South,Kentucky,315172,26961184,11.69,5122694,61.52,1.43
34,South,Mississippi,213399,17759177,12.02,3496766,61.03,0.97
35,South,Tennessee,486893,41639064,11.69,8166631,59.62,2.21
36,South,Arkansas,215533,18201411,11.84,3505626,61.48,0.98
37,South,Louisiana,344727,27742127,12.43,5509902,62.56,1.56
38,South,Oklahoma,291217,23941096,12.16,4723856,61.65,1.32
39,South,Texas,2275693,177119299,12.85,36976634,61.54,10.31
40,South,TOTAL,8821173,763063961,11.56,150408029,58.65,39.95
41,West,Arizona,471604,43938621,10.73,8478149,55.63,2.14
42,West,Colorado,374074,34791624,10.75,7170448,52.17,1.69
43,West,Idaho,132214,11172868,11.83,2177962,60.71,0.60
44,West,Montana,66867,6571610,10.18,1214373,55.06,0.30
45,West,Nevada,203080,18768746,10.82,3675214,55.26,0.92
46,West,New Mexico,131858,12642168,10.43,2415538,54.59,0.60
47,West,Utah,277236,19753451,14.03,4341180,63.86,1.26
48,West,Wyoming,37531,3483065,10.78,651779,57.58,0.17
49,West,Alaska,57118,4399803,12.98,867023,65.88,0.26
50,West,California,2561478,235669717,10.87,48016877,53.35,11.60
51,West,Hawaii,95517,8560256,11.16,1571913,60.76,0.43
52,West,Oregon,242571,25369607,9.56,4987114,48.64,1.10
53,West,Washington,502242,46181454,10.88,9240808,54.35,2.27
54,West,TOTAL,5153390,471302990,10.93,94808378,54.36,23.34
55,USA,TOTAL,22080966,1984987277,11.12,389640765,56.67,100.00

In [ ]:
# make a stateAbbr column in nat
nat['stateAbbr'] = nat['State of Residence'].map(stateAbbri)
nat.to_excel("natality.xlsx", index=False)

In [106]:
states = pd.read_excel("sepehr_states.xlsx")
nat = pd.read_excel("natality.xlsx")

states = states.merge(nat, on='stateAbbr', how='outer')
states = states.drop(columns=['Census Region of Residence', 'State of Residence'])
states.to_excel("sepehr_states_1.xlsx", index=False)

In [128]:
reg = pd.read_csv("sepehr_regions.csv")

reg = reg.rename(columns={
                          'Births': 'regionBirths', 
                          'Total Population': 'regionPopulation', 
                          'Birth Rate': 'regionBirthRate',
                          'Female Population': 'regionFemalePopulation', 
                          'Fertility Rate': 'regionFertilityRate',
                          '% of Total Births': 'regionPercentOfTotalBirths'})
mergetest = states.merge(reg, on='region', how='outer')
mergetest = mergetest.drop(index=[0, 52, 53, 54, 55, 56])

# order the states in alphabetical order
mergetest = mergetest.sort_values(by='state')
mergetest.to_excel("sepehr_states.xlsx", index=False)

In [130]:
inc = pd.read_excel("incomes.xlsx")
inc

,STATE,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3,2019:Q4,2020:Q1,...,2022:Q3,2022:Q4,2023:Q1,2023:Q2,2023:Q3,2023:Q4,2024:Q1,2024:Q2,2024:Q3,2024:Q4
0,Alabama,40825,41094,41404,41938,42579,42884,43118,43372,43931,...,52080,52798,53411,53847,54308,54869,55930,56395,56893,57551
1,Alaska,58076,58490,59483,59869,60094,60354,60680,60820,60261,...,69367,70276,69651,70925,71981,72593,74604,74705,75469,76299
2,Arizona,44628,44961,45539,45981,47035,47498,47930,48336,48912,...,59350,60255,61276,62190,62408,62804,64225,64432,64364,64904
3,Arkansas,42434,42762,43230,43670,43223,43473,43940,44263,44862,...,55969,57031,57509,57487,57548,57880,58869,59158,60090,60549
4,California,59735,60612,61457,62167,63291,63964,64328,65254,66306,...,77083,78356,79505,80520,81150,81691,84393,85201,85808,86834
5,Colorado,56452,57262,58297,59236,60763,60992,61643,61711,63076,...,78441,77705,78580,79551,79948,80840,82080,82838,82634,83374
6,Connecticut,71081,71679,72868,73045,73957,74045,73961,74641,74054,...,85572,86626,87884,89029,89592,90596,92496,93030,93408,94192
7,Delaware,51725,52313,53075,53504,53520,53795,53917,53801,54275,...,64766,65680,65784,66470,66815,67135,68349,69390,69317,70141
8,District of Columbia,80946,81715,83021,83549,83116,83648,83777,84046,84590,...,100848,101891,104040,105699,105600,106379,107908,108577,108103,108848
9,Florida,50086,50560,51364,52049,53095,53504,53735,54246,54623,...,64977,65874,67037,67628,67958,68695,70077,70155,70521,71040
10,Georgia,45853,46325,47017,47261,48149,48455,48645,48881,49157,...,57672,58262,58647,59521,59954,60663,61923,62192,62368,63154
11,Hawaii,51061,51439,51685,52079,53335,53654,54101,54616,54941,...,62789,64786,64623,65663,66161,66995,68269,69686,69789,70454
12,Idaho,42652,43005,43330,43942,45204,45697,46117,46440,47332,...,57479,58274,58693,58779,59271,59950,60954,61833,62119,62471
13,Illinois,55132,55880,56370,56903,57184,57427,57979,58328,58924,...,68943,69816,70531,71434,71996,72744,73646,73965,74282,75030
14,Indiana,46049,46288,46688,47188,47809,48086,48440,48727,49550,...,59023,60165,60126,60872,61338,61943,63529,63902,63678,64153
15,Iowa,47973,48452,48803,49815,49297,49129,50030,50237,50070,...,62433,62643,62253,62219,62766,62900,63153,63287,63682,64243
16,Kansas,49399,50005,50547,51172,51616,51850,52388,52709,52943,...,62910,63625,64814,65614,66336,66637,67229,67971,68170,68862
17,Kentucky,41189,41590,41755,42085,43045,43310,43552,43938,44472,...,52795,53375,54181,54857,55456,55709,57168,57285,57527,58200
18,Louisiana,44716,45343,45695,46069,46729,46889,47059,47374,47575,...,56117,56735,57809,58237,58821,59662,60867,61225,61459,61827
19,Maine,47115,47551,47977,48226,49424,49763,50102,50615,51423,...,62450,62792,64542,64357,65027,65826,67585,67855,68193,68918
20,Maryland,59189,59690,60246,60503,61227,61714,61753,62159,62266,...,71678,72524,73521,74623,75421,76054,78093,78337,78529,79325
21,Massachusetts,68245,68799,69520,70234,72195,72334,72320,72658,73566,...,85692,88976,88353,89588,90006,90904,93391,93817,93922,94849
22,Michigan,46671,46917,47266,47508,48091,48492,48655,49057,49435,...,58276,58800,60021,60712,61139,61495,62715,63304,63129,63816
23,Minnesota,55151,55881,56507,57276,57462,57637,58162,58371,58830,...,70670,71078,71382,72076,72712,73223,74378,74405,75094,75971
24,Mississippi,37071,37479,37705,38202,38785,38895,39297,39598,40058,...,47454,47989,48826,49450,49644,50451,51261,51837,52194,52757
25,Missouri,45796,46639,46877,47388,47760,48076,48658,49173,49802,...,59668,60469,61493,62296,62698,63390,64275,64500,64809,65415
26,Montana,46504,46993,47311,47987,49011,49277,49968,50258,50249,...,61985,62723,64200,64804,65286,66087,66974,67277,67754,68444
27,Nebraska,50476,50864,51439,52957,52754,52860,53933,54481,54020,...,67809,68661,70448,70855,71264,71404,71336,71884,71816,72496
28,Nevada,48716,48879,49382,50122,51421,51834,51992,52552,52941,...,62885,63894,64504,65492,66148,66952,68439,68543,68607,69175
29,New Hampshire,59798,60014,60633,60847,63832,63840,63942,64115,65539,...,75575,76697,77412,78744,79230,80304,82459,82702,82727,83674
30,New Jersey,63255,63788,64598,65121,67192,67457,67552,67822,68369,...,78003,78782,80103,80939,81802,82260,83460,84015,84139,84909
31,New Mexico,40314,40730,41233,41543,42569,43001,43487,43771,44550,...,54367,53949,54467,55145,55130,55861,57023,57576,57766,58286
32,New York,63330,63986,64654,64953,65768,66492,66595,66981,67342,...,77748,79182,79743,81420,82431,82699,84520,85565,86007,87061
33,North Carolina,45226,45771,46250,46928,47831,48226,48488,48915,49685,...,59065,59973,60805,61125,61778,62594,64019,64547,65173,65747
34,North Dakota,53653,54635,55521,56844,56402,55931,57115,57212,58162,...,72198,72172,71676,71675,71561,71393,70999,70865,70677,71453
35,Ohio,47112,47529,48076,48542,48971,49202,49492,49907,50272,...,58701,59376,60190,60973,61634,62342,63440,64197,64312,65011
36,Oklahoma,45333,45715,46271,46733,48213,47980,48179,48272,48476,...,58865,59358,59807,60076,60576,61145,62037,62642,62694,63300
37,Oregon,49343,49893,50581,51010,51588,51919,52216,53024,54064,...,64219,65166,66487,67211,67962,68276,69746,70762,70795,71524
38,Pennsylvania,53550,54083,54913,55346,55681,56027,56164,56634,57048,...,66016,66580,67777,68386,68782,69555,70279,70806,71366,72220
39,Rhode Island,51741,51870,52137,52847,54902,55086,54973,55473,56445,...,64538,64929,66049,66651,67609,67938,69535,69636,70003,70693
40,South Carolina,43136,43525,43995,44573,45723,45965,46245,46637,46579,...,54642,55827,56602,56668,57428,58042,59462,59880,60006,60659
41,South Dakota,50773,50865,51301,53283,53730,53569,54928,55416,55847,...,70318,70608,72118,72382,72773,72984,73575,73876,73856,74544
42,Tennessee,45732,46072,46802,47201,48439,48782,49034,49287,50482,...,59443,60264,61110,61712,62297,63045,64193,64972,64921,65596
43,Texas,50365,50969,51714,52272,52840,53113,53377,53681,53146,...,63594,64232,65189,65414,65932,66554,67598,67822,68029,68456
44,Utah,44732,45202,45703,46220,47763,47783,48334,48748,49250,...,61113,62056,62509,63412,64070,64708,66098,66547,66308,66966
45,Vermont,50941,51479,51908,52430,54136,54094,54366,54461,55786,...,63962,65293,65832,66691,66822,67895,69269,70108,70197,70811
46,Virginia,55380,55789,56365,56938,57769,58196,58574,58890,59377,...,70535,71492,72135,73396,73963,75095,76248,76984,77159,78074
47,Washington,58871,59261,60233,60937,62797,63186,63503,64188,65129,...,76085,77204,78741,80313,80813,81800,82950,84107,84077,84802
48,West Virginia,40006,40625,41507,41828,42520,42697,42719,42480,42717,...,50457,51075,51935,52697,52870,53695,54897,55228,54899,55532
49,Wisconsin,49984,50140,50735,51204,51857,52312,52359,52932,53257,...,62518,62898,63733,64381,65049,65848,67037,67245,67777,68347
50,Wyoming,57821,58729,59687,60422,61147,61459,62171,62518,63854,...,77095,78995,80612,81515,82276,83283,84589,85570,86359,87284

In [141]:
for x in [2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    inc[f'median{x}'] = inc[[f'{x}:Q1', f'{x}:Q2', f'{x}:Q3', f'{x}:Q4']].max(axis=1)

for x in [2018, 2019, 2020, 2021, 2022, 2023, 2024]:
    for y in ['Q1', 'Q2', 'Q3', 'Q4']:
        inc = inc.drop(columns=[f'{x}:{y}'])

inc['stateAbbr'] = inc['STATE'].map(stateAbbri)

KeyError: "None of [Index(['2018:Q1', '2018:Q2', '2018:Q3', '2018:Q4'], dtype='object')] are in the [columns]"

In [143]:
inc['stateAbbr'] = inc['STATE'].map(stateAbbri)
inc

,STATE,median2018,median2019,median2020,median2021,median2022,median2023,median2024,stateAbbr
0,Alabama,41938,43372,47828,53279,52798,54869,57551,AL
1,Alaska,59869,60820,64390,68068,70276,72593,76299,AK
2,Arizona,45981,48336,54111,59129,60255,62804,64904,AZ
3,Arkansas,43670,44263,49385,54909,57031,57880,60549,AR
4,California,62167,65254,72352,78893,78356,81691,86834,CA
5,Colorado,59236,61711,65940,72734,78441,80840,83374,CO
6,Connecticut,73045,74641,77771,83235,86626,90596,94192,CT
7,Delaware,53504,53917,57283,62987,65680,67135,70141,DE
8,District of Columbia,83549,84046,92435,99053,101891,106379,108848,DC
9,Florida,52049,54246,58119,64409,65874,68695,71040,FL
10,Georgia,47261,48881,53532,58750,58262,60663,63154,GA
11,Hawaii,52079,54616,59741,63928,64786,66995,70454,HI
12,Idaho,43942,46440,50857,57842,58274,59950,62471,ID
13,Illinois,56903,58328,63173,68959,69816,72744,75030,IL
14,Indiana,47188,48727,53102,59797,60165,61943,64153,IN
15,Iowa,49815,50237,54978,60415,62643,62900,64243,IA
16,Kansas,51172,52709,56926,60655,63625,66637,68862,KS
17,Kentucky,42085,43938,49826,54463,53375,55709,58200,KY
18,Louisiana,46069,47374,53096,57085,56735,59662,61827,LA
19,Maine,48226,50615,57112,61842,62792,65826,68918,ME
20,Maryland,60503,62159,66549,71897,72524,76054,79325,MD
21,Massachusetts,70234,72658,79602,85585,88976,90904,94849,MA
22,Michigan,47508,49057,56065,59953,58800,61495,63816,MI
23,Minnesota,57276,58371,63783,69421,71078,73223,75971,MN
24,Mississippi,38202,39598,45310,50053,47989,50451,52757,MS
25,Missouri,47388,49173,54330,59202,60469,63390,65415,MO
26,Montana,47987,50258,56094,61425,62723,66087,68444,MT
27,Nebraska,52957,54481,58589,64583,68661,71404,72496,NE
28,Nevada,50122,52552,56889,62865,63894,66952,69175,NV
29,New Hampshire,60847,64115,68556,74338,76697,80304,83674,NH
30,New Jersey,65121,67822,71195,78329,78782,82260,84909,NJ
31,New Mexico,41543,43771,48750,53692,54367,55861,58286,NM
32,New York,64953,66981,72301,78501,79182,82699,87061,NY
33,North Carolina,46928,48915,53556,59301,59973,62594,65747,NC
34,North Dakota,56844,57212,62710,66879,72198,71676,71453,ND
35,Ohio,48542,49907,54936,60407,59376,62342,65011,OH
36,Oklahoma,46733,48272,52427,56502,59358,61145,63300,OK
37,Oregon,51010,53024,58255,64964,65166,68276,71524,OR
38,Pennsylvania,55346,56634,62463,66449,66580,69555,72220,PA
39,Rhode Island,52847,55473,61724,65492,64929,67938,70693,RI
40,South Carolina,44573,46637,51305,55928,55827,58042,60659,SC
41,South Dakota,53283,55416,61583,67885,70608,72984,74544,SD
42,Tennessee,47201,49287,53227,59954,60264,63045,65596,TN
43,Texas,52272,53681,56349,62015,64232,66554,68456,TX
44,Utah,46220,48748,53205,59964,62056,64708,66966,UT
45,Vermont,52430,54461,61507,64176,65293,67895,70811,VT
46,Virginia,56938,58890,62910,69013,71492,75095,78074,VA
47,Washington,60937,64188,69647,75611,77204,81800,84802,WA
48,West Virginia,41828,42719,48174,51918,51075,53695,55532,WV
49,Wisconsin,51204,52932,57292,62713,62898,65848,68347,WI
50,Wyoming,60422,62518,67053,72523,78995,83283,87284,WY

In [151]:
states = pd.read_excel("sepehr_states.xlsx")
states

,state,stateAbbr,region,Births,Total Population,Birth Rate,Female Population,Fertility Rate,percentOfTotalBirths,regionBirths,regionPopulation,regionBirthRate,regionFemalePopulation,regionFertilityRate,regionPercentOfTotalBirths,unemploymentRate
0,Alabama,AL,South,348084,29935229,11.63,5816314,59.85,1.58,8821173,763063961,11.56,150408029,58.65,39.95,3.3
1,Alaska,AK,West,57118,4399803,12.98,867023,65.88,0.26,5153390,471302990,10.93,94808378,54.36,23.34,4.7
2,Arizona,AZ,West,471604,43938621,10.73,8478149,55.63,2.14,5153390,471302990,10.93,94808378,54.36,23.34,4.1
3,Arkansas,AR,South,215533,18201411,11.84,3505626,61.48,0.98,8821173,763063961,11.56,150408029,58.65,39.95,3.7
4,California,CA,West,2561478,235669717,10.87,48016877,53.35,11.60,5153390,471302990,10.93,94808378,54.36,23.34,5.3
5,Colorado,CO,West,374074,34791624,10.75,7170448,52.17,1.69,5153390,471302990,10.93,94808378,54.36,23.34,4.8
6,Connecticut,CT,Northeast,208004,21543936,9.65,4081181,50.97,0.94,3527918,339127512,10.40,65420694,53.93,15.98,3.7
7,Delaware,DE,South,63300,5981414,10.58,1108192,57.12,0.29,8821173,763063961,11.56,150408029,58.65,39.95,3.9
8,District of Columbia,DC,South,51796,4141845,12.51,1112736,46.55,0.23,8821173,763063961,11.56,150408029,58.65,39.95,5.8
9,Florida,FL,South,1313318,131147051,10.01,23772622,55.24,5.95,8821173,763063961,11.56,150408029,58.65,39.95,3.7
10,Georgia,GA,South,750339,64588584,11.62,13290576,56.46,3.40,8821173,763063961,11.56,150408029,58.65,39.95,3.6
11,Hawaii,HI,West,95517,8560256,11.16,1571913,60.76,0.43,5153390,471302990,10.93,94808378,54.36,23.34,2.9
12,Idaho,ID,West,132214,11172868,11.83,2177962,60.71,0.60,5153390,471302990,10.93,94808378,54.36,23.34,3.7
13,Illinois,IL,Midwest,803600,75803621,10.60,14934897,53.81,3.64,4578485,411492814,11.13,79003664,57.95,20.73,4.8
14,Indiana,IN,Midwest,479716,40680271,11.79,7927380,60.51,2.17,4578485,411492814,11.13,79003664,57.95,20.73,3.9
15,Iowa,IA,Midwest,220941,19075376,11.58,3613047,61.15,1.00,4578485,411492814,11.13,79003664,57.95,20.73,3.5
16,Kansas,KS,Midwest,209203,17550902,11.92,3396536,61.59,0.95,4578485,411492814,11.13,79003664,57.95,20.73,3.8
17,Kentucky,KY,South,315172,26961184,11.69,5122694,61.52,1.43,8821173,763063961,11.56,150408029,58.65,39.95,5.2
18,Louisiana,LA,South,344727,27742127,12.43,5509902,62.56,1.56,8821173,763063961,11.56,150408029,58.65,39.95,4.4
19,Maine,ME,Northeast,71355,8186066,8.72,1430071,49.90,0.32,3527918,339127512,10.40,65420694,53.93,15.98,3.5
20,Maryland,MD,South,412473,36654242,11.25,7192645,57.35,1.87,8821173,763063961,11.56,150408029,58.65,39.95,3.1
21,Massachusetts,MA,Northeast,409468,41656322,9.83,8419406,48.63,1.85,3527918,339127512,10.40,65420694,53.93,15.98,4.6
22,Michigan,MI,Midwest,628417,60071512,10.46,11321208,55.51,2.85,4578485,411492814,11.13,79003664,57.95,20.73,5.5
23,Minnesota,MN,Midwest,386969,34070642,11.36,6552584,59.06,1.75,4578485,411492814,11.13,79003664,57.95,20.73,3.2
24,Mississippi,MS,South,213399,17759177,12.02,3496766,61.03,0.97,8821173,763063961,11.56,150408029,58.65,39.95,4.0
25,Missouri,MO,Midwest,420242,36957728,11.37,7119267,59.03,1.90,4578485,411492814,11.13,79003664,57.95,20.73,3.9
26,Montana,MT,West,66867,6571610,10.18,1214373,55.06,0.30,5153390,471302990,10.93,94808378,54.36,23.34,2.7
27,Nebraska,NE,Midwest,147599,11711222,12.60,2272581,64.95,0.67,4578485,411492814,11.13,79003664,57.95,20.73,3.0
28,Nevada,NV,West,203080,18768746,10.82,3675214,55.26,0.92,5153390,471302990,10.93,94808378,54.36,23.34,5.6
29,New Hampshire,NH,Northeast,72263,8268721,8.74,1497455,48.26,0.33,3527918,339127512,10.40,65420694,53.93,15.98,3.1
30,New Jersey,NJ,Northeast,604153,54492751,11.09,10293179,58.69,2.74,3527918,339127512,10.40,65420694,53.93,15.98,4.8
31,New Mexico,NM,West,131858,12642168,10.43,2415538,54.59,0.60,5153390,471302990,10.93,94808378,54.36,23.34,4.3
32,New York,NY,Northeast,1279243,117416826,10.89,23255110,55.01,5.79,3527918,339127512,10.40,65420694,53.93,15.98,4.2
33,North Carolina,NC,South,716519,63558153,11.27,12498057,57.33,3.24,8821173,763063961,11.56,150408029,58.65,39.95,3.7
34,North Dakota,ND,Midwest,60475,4625583,13.07,906297,66.73,0.27,4578485,411492814,11.13,79003664,57.95,20.73,2.6
35,Ohio,OH,Midwest,783704,70393769,11.13,13365288,58.64,3.55,4578485,411492814,11.13,79003664,57.95,20.73,4.9
36,Oklahoma,OK,South,291217,23941096,12.16,4723856,61.65,1.32,8821173,763063961,11.56,150408029,58.65,39.95,3.2
37,Oregon,OR,West,242571,25369607,9.56,4987114,48.64,1.10,5153390,471302990,10.93,94808378,54.36,23.34,4.7
38,Pennsylvania,PA,Northeast,790421,77290050,10.23,14466075,54.64,3.58,3527918,339127512,10.40,65420694,53.93,15.98,3.9
39,Rhode Island,RI,Northeast,61320,6459107,9.49,1273562,48.15,0.28,3527918,339127512,10.40,65420694,53.93,15.98,4.9
40,South Carolina,SC,South,342145,31297775,10.93,5998759,57.04,1.55,8821173,763063961,11.56,150408029,58.65,39.95,4.2
41,South Dakota,SD,Midwest,68073,5384129,12.64,992778,68.57,0.31,4578485,411492814,11.13,79003664,57.95,20.73,1.8
42,Tennessee,TN,South,486893,41639064,11.69,8166631,59.62,2.21,8821173,763063961,11.56,150408029,58.65,39.95,3.5
43,Texas,TX,South,2275693,177119299,12.85,36976634,61.54,10.31,8821173,763063961,11.56,150408029,58.65,39.95,4.1
44,Utah,UT,West,277236,19753451,14.03,4341180,63.86,1.26,5153390,471302990,10.93,94808378,54.36,23.34,3.1
45,Vermont,VT,Northeast,31691,3813733,8.31,704655,44.97,0.14,3527918,339127512,10.40,65420694,53.93,15.98,2.7
46,Virginia,VA,South,576125,51685358,11.15,10227966,56.33,2.61,8821173,763063961,11.56,150408029,58.65,39.95,3.3
47,Washington,WA,West,502242,46181454,10.88,9240808,54.35,2.27,5153390,471302990,10.93,94808378,54.36,23.34,4.4
48,West Virginia,WV,South,104440,10710952,9.75,1888053,55.32,0.47,8821173,763063961,11.56,150408029,58.65,39.95,3.8
49,Wisconsin,WI,Midwest,369546,35168059,10.51,6601801,55.98,1.67,4578485,411492814,11.13,79003664,57.95,20.73,3.3
50,Wyoming,WY,West,37531,3483065,10.78,651779,57.58,0.17,5153390,471302990,10.93,94808378,54.36,23.34,3.3

In [156]:
testmerge = states.merge(inc, on='stateAbbr', how='outer')
testmerge.drop(columns=['STATE'], inplace=True)
for x in ['median2018', 'median2019', 'median2020', 'median2021', 'median2022', 'median2023', 'median2024']:
    testmerge.rename(columns={x: f'perCapitaPersonalIncome{x.split("median")[1]}'}, inplace=True)

testmerge.to_excel("sepehr_states.xlsx", index=False)

In [ ]:
sheeo = pd.read_excel("sheeo.xlsx", sheet_name="Sector Data")
sheeo.rename(columns={'State': 'state'}, inplace=True)
sheeo
rev['stateAbbr'] = rev['state'].map(stateAbbri)

,state,FY,COLI (Cost of Living) Adjustment,HECA (Inflation) Adjustment,CPI (Inflation) Adjustment,Two-Year State Support,Four-Year State Support,Two-Year State and Local Support,Two-Year State and Local Support Excluding Federal Stimulus,Four-Year State and Local Support,...,Four-Year RAM,Two-Year Gross Tuition and Fee Revenue,Four-Year Gross Tuition and Fee Revenue,Two-Year Institutional Discounts and Waivers,Four-Year Institutional Discounts and Waivers,Four-Year Medical Tuition and Fee Revenue,Two-Year Tuition Used for Debt Service,Four-Year Tuition Used for Debt Service,Four-Year Gross FTE Enrollment,Four-Year Medical FTE Enrollment
0,Alabama,2024,0.876645,1.000000,1.000000,649971818,1834974274,652807818,652807818,1834974274,...,395315305,295171538,2824940539,0,0,2.645193e+08,22077974.0,126037140.0,155000,10597
1,Alaska,2024,1.240699,1.000000,1.000000,0,328063402,0,0,328816402,...,22867381,0,107699379,0,20547930,0.000000e+00,0.0,0.0,12684,0
2,Arizona,2024,0.964115,1.000000,1.000000,168884200,1207869800,1189046800,1189046800,1207869800,...,250165600,326001400,4570073200,89443100,1413664000,3.831330e+07,0.0,150158400.0,222845,958
3,Arkansas,2024,0.851381,1.000000,1.000000,192791709,819849031,233126278,233126278,819849031,...,242840558,143744272,982077062,14749019,159196530,5.564444e+07,19984461.0,180534067.0,82189,3271
4,California,2024,1.268947,1.000000,1.000000,7322820000,10858520872,11416681000,11416681000,10858520872,...,1249332000,1257968088,8636729771,0,2090359000,1.081860e+08,0.0,0.0,684868,17326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,West Virginia,2019,0.897032,0.841897,0.815044,68309173,397927750,68309173,68309173,397927750,...,142861228,53619015,790750537,4312365,141444304,1.319273e+08,1765363.0,47330959.0,57315,1814
308,Wisconsin,2019,0.942542,0.841897,0.815044,546951357,877095576,795416572,795416572,877095576,...,169464642,232959417,1444709694,4422882,160415462,3.791284e+07,NaN,NaN,138707,1107
309,Wyoming,2019,0.990072,0.841897,0.815044,148032490,244454986,182604336,182604336,244454986,...,44286798,45912474,112859000,10156832,40625000,0.000000e+00,0.0,805819.0,11023,43
310,U.S.,2019,1.000000,0.841897,0.815044,22588741369,63528793750,34201890861,34201890861,63654826713,...,10893821484,16302227294,87606359756,2122183971,14120565252,3.456191e+09,94020194.0,809112790.0,6754405,153428
311,D.C.,2019,1.497852,0.841897,0.815044,0,99066770,0,0,99066770,...,5900867,0,37583509,0,1440922,0.000000e+00,0.0,0.0,3518,0

In [ ]:
rev = pd.read_excel("forStateStuff.xlsx")

for year in range(2019, 2025):
    for state in rev['state']:
        rev['fourYearAppropriations' + str(year)] = # the "Four-Year Education Appropriations" column for that year.
        rev['twoYearAppropriations' + str(year)] = # the "Two-Year Education Appropriations" column for that year.
        rev['fourYearNetFTE' + str(year)] = # the "Four-Year Net FTE Enrollment" column for that year.
        rev['twoYearNetFTE' + str(year)] = # the "Two-Year Net FTE Enrollment" column for that year.
        rev['fourYearNetTuitionAndFeeRevenue' + str(year)] = # the "Four-Year Net Tuition and Fee Revenue" column for that year.
        rev['twoYearNetTuitionAndFeeRevenue' + str(year)] = # the "Two-Year Net Tuition and Fee Revenue" column for that year.
        rev['fourYearTotalEducationRevenue' + str(year)] = # the "Four-Year Total Education Revenue" column for that year.
        rev['twoYearTotalEducationRevenue' + str(year)] = # the "Two-Year Total Education Revenue" column for that year.

2019
2020
2021
2022
2023
2024

             state stateAbbr
0          Alabama        AL
1           Alaska        AK
2          Arizona        AZ
3         Arkansas        AR
4       California        CA
5         Colorado        CO
6      Connecticut        CT
7         Delaware        DE
8          Florida        FL
9          Georgia        GA
10          Hawaii        HI
11           Idaho        ID
12        Illinois        IL
13         Indiana        IN
14            Iowa        IA
15          Kansas        KS
16        Kentucky        KY
17       Louisiana        LA
18           Maine        ME
19        Maryland        MD
20   Massachusetts        MA
21        Michigan        MI
22       Minnesota        MN
23     Mississippi        MS
24        Missouri        MO
25         Montana        MT
26        Nebraska        NE
27          Nevada        NV
28   New Hampshire        NH
29      New Jersey        NJ
30      New Mexico        NM
31        New York        NY
32  North Carolina        NC
33    North Dakota        ND
34            Ohio        OH
35        Oklahoma        OK
36          Oregon        OR
37    Pennsylvania        PA
38    Rhode Island        RI
39  South Carolina        SC
40    South Dakota        SD
41       Tennessee        TN
42           Texas        TX
43            Utah        UT
44         Vermont        VT
45        Virginia        VA
46      Washington        WA
47   West Virginia        WV
48       Wisconsin        WI
49         Wyoming        WY

In [ ]:

result = rev[['state']].copy()

columns_to_extract = {
    'Four-Year Education Appropriations': 'fourYearAppropriations',
    'Two-Year Education Appropriations': 'twoYearAppropriations',
    'Four-Year Net FTE Enrollment': 'fourYearNetFTE',
    'Two-Year Net FTE Enrollment': 'twoYearNetFTE',
    'Four-Year Net Tuition and Fee Revenue': 'fourYearNetTuitionAndFeeRevenue',
    'Two-Year Net Tuition and Fee Revenue': 'twoYearNetTuitionAndFeeRevenue',
    'Four-Year Total Education Revenue': 'fourYearTotalEducationRevenue',
    'Two-Year Total Education Revenue': 'twoYearTotalEducationRevenue',
    'Two-Year Student Share': 'twoYearStudentShare',
    'Four-Year Student Share': 'fourYearStudentShare'
}
for year in range(2019, 2025):
    year_data = sheeo[sheeo['FY'] == year][['state'] + list(columns_to_extract.keys())]
    year_data = year_data.rename(columns={old: f"{new}{year}" for old, new in columns_to_extract.items()})
    result = result.merge(year_data, left_on='state', right_on='state', how='left')
    if 'State' in result.columns:
        result = result.drop('State', axis=1)
# result.to_excel("cleaned_sheeo_data.xlsx", index=False)

In [190]:
result

,state,fourYearAppropriations2019,twoYearAppropriations2019,fourYearNetFTE2019,twoYearNetFTE2019,fourYearNetTuitionAndFeeRevenue2019,twoYearNetTuitionAndFeeRevenue2019,fourYearTotalEducationRevenue2019,twoYearTotalEducationRevenue2019,fourYearAppropriations2020,...,fourYearTotalEducationRevenue2023,twoYearTotalEducationRevenue2023,fourYearAppropriations2024,twoYearAppropriations2024,fourYearNetFTE2024,twoYearNetFTE2024,fourYearNetTuitionAndFeeRevenue2024,twoYearNetTuitionAndFeeRevenue2024,fourYearTotalEducationRevenue2024,twoYearTotalEducationRevenue2024
0,Alabama,870474437,373978295,143485,59288,2202302684,281380200,2938256114,626186283,934837520,...,3797867981,1241818588,1436147789,652807818,144403,56546,2520822860,288865816,3830933509,919595660
1,Alaska,317936098,0,16721,0,95873240,0,413809338,0,294945498,...,368318222,0,305949021,0,12684,0,75800668,0,381749689,0
2,Arizona,621655200,1011140300,182299,110557,2279943700,219173700,2797858500,1230314000,700784500,...,3555337900,1328697000,957704200,1189046800,221887,105282,3025577400,235947900,3833123200,1424994700
3,Arkansas,549066991,210661479,82311,30934,558577535,116421320,1040227329,310435644,554366399,...,1097367708,323024510,576361781,233126278,78918,27806,684913715,116717549,1080741429,329859366
4,California,6987935555,9920625750,672687,918444,5427976052,704990279,12415911607,10625616029,7384224361,...,13800159971,11860256000,9609188872,11416681000,667542,853174,4887378256,633708088,14496567128,12050389088
5,Colorado,545568907,348106684,127744,56000,1838423316,248778463,2383992223,596885147,606661026,...,2920443255,606285069,883748954,482042038,123216,58316,2176433850,243573218,3060182804,725615256
6,Connecticut,656771926,274395936,57374,26419,922158033,173388994,1578929959,447784930,675916335,...,1936853044,623935014,988182781,398443921,54369,21708,857868062,150901755,1846050843,549345676
7,Delaware,155842700,81266100,27524,8886,661616253,51949000,809591103,133215100,175041423,...,874795740,133402800,179747600,94134700,29385,7855,750585670,42016440,922161986,136151140
8,Florida,3264208503,1417043690,293179,315763,732426706,815454125,3996635209,2232497815,3378443061,...,4449150951,2345873070,4534349057,1890466581,299049,280428,630038694,763825846,5164387751,2654292427
9,Georgia,2398496689,521565902,269808,86540,1397005897,233486948,3794690972,755052850,2547118266,...,4792616947,866885655,3316954025,646198743,284195,82553,1413970025,228973765,4730837320,872849995
10,Hawaii,374900906,216369518,20434,14820,175834578,50802743,546110911,264771012,366968512,...,604609040,291071012,417753225,230966989,20723,11971,185039640,39924572,598531517,268735330
11,Idaho,325709116,81353700,39610,14811,313196882,44776800,638905998,126130500,339125647,...,751098973,143044704,393938104,103791621,40500,15284,402384921,45108753,775872945,148211514
12,Illinois,3017467188,1606815523,166254,140713,1646732954,701083892,4521657874,2307899415,3187254988,...,5290210995,2650737897,3920182109,2103336746,159605,102039,1635321421,591781266,5452987081,2695118012
13,Indiana,1130208640,328434443,182388,63913,2091043906,199967168,3179943627,522197118,1114291880,...,3414540330,522291440,1211248383,374773932,179013,68931,2421439076,211615798,3583724431,581476288
14,Iowa,441297139,243092718,72148,57239,940858158,295577355,1382155297,538670073,454574890,...,1393070050,571298490,458260178,300586582,64906,51282,981541949,293545933,1439802127,594132515
15,Kansas,439318624,422494288,79358,52895,748176878,143407789,1187495502,565902077,462484573,...,1236668525,635985823,661542924,559318472,74194,46909,747689293,120603314,1398979833,679921786
16,Kentucky,677076000,228917300,98557,43446,997299484,175672455,1650610692,394186755,690742100,...,1820770332,431929874,902483944,277708062,96927,42736,1034610250,169880488,1914669769,437242052
17,Louisiana,694398663,143006506,120841,43091,666905944,155818967,1361304607,298825473,690139603,...,1496796793,329985231,850399183,191503602,123787,41134,731770334,152448254,1582169517,343951856
18,Maine,190137977,77996303,24174,9773,216764719,30968136,406902696,108964439,198733750,...,443241547,124284432,252581823,109419897,22530,11276,220514252,18907759,473096075,128327656
19,Maryland,1311024223,804115016,139253,89990,1617504675,405437082,2928528898,1209552098,1440656580,...,3584870361,1319454857,2165653384,1034103199,147203,74290,1757389274,362700759,3923042658,1396803958
20,Massachusetts,1130048154,407309591,110528,49799,884221811,193303325,2014269965,600612916,1185419488,...,2584887145,709911203,1688985706,714506125,94318,42767,1028858932,118535365,2717844638,833041490
21,Michigan,1378192169,963809154,249978,116340,3994299546,626904274,5372491715,1590713428,1395929471,...,5740359648,1749099877,1685847041,1391151754,231731,100514,4265285373,545624627,5951132414,1936776381
22,Minnesota,820634227,480882007,108148,76219,1290831123,368534372,2111465350,849416379,867441081,...,2152063567,874812137,1013772361,640326668,95009,66701,1285526671,350288761,2294884211,990615429
23,Mississippi,387182397,298335003,71200,61799,620658969,222790779,1007841366,521125782,407082330,...,1174477438,569361524,539257130,372343563,67498,54427,702848167,225508669,1242105297,597852232
24,Missouri,763826228,338671368,122734,59765,951715709,147642047,1715541937,486313415,811736828,...,1634354486,587379789,759340391,487695274,102046,42855,981403835,164260811,1740744226,651956085
25,Montana,177825497,35256995,29697,6678,250076813,11128321,427902310,46385316,189459617,...,474491406,48512196,216532837,42184929,28069,6434,283445324,10754871,499978161,52939800
26,Nebraska,446717302,277420452,49798,26142,423471846,69543626,857005570,342866282,464311999,...,927433046,374631422,560946230,345719215,48231,24394,421073434,60106507,966167917,400017811
27,Nevada,439927542,182977139,47398,29026,152932193,53609076,592859735,236586215,466772726,...,639026700,274825916,535162667,244999341,44155,24736,165066122,63817968,700228789,308817309
28,New Hampshire,68585277,50493263,26500,9853,357236798,56411095,425822075,106904358,78230478,...,392662839,102392261,92181065,71824372,22543,7348,305740433,42868710,397921498,114693082
29,New Jersey,1412319000,463026000,165182,99904,1837231894,324942786,3249550894,787968786,1709490759,...,3718884500,792794449,2149408446,573737554,161065,86990,1721633875,253687727,3871042321,827425281
30,New Mexico,578461834,359404918,39242,37798,149864116,67574708,728325950,426979626,688336556,...,1151993098,473787964,795297332,422258954,41940,31403,185213658,48854010,980510990,471112964
31,New York,4548248299,1953533426,327088,210891,2323477548,915835486,6871725847,2869368912,4616273600,...,7040562353,2789029271,5299757084,1962585861,297457,159144,2260929987,862476777,7560687071,2825062638
32,North Carolina,2368608880,1291226029,214263,179659,1546595373,298247489,3915204253,1589473518,2376700413,...,4457358369,1802894862,3112901071,1643167084,217197,192388,1637320074,292009773,4750221145,1935176857
33,North Dakota,197780892,50404041,26753,7028,275201702,26181191,472982594,76585232,202954826,...,528825347,81324252,249900359,64181851,26033,7384,306326264,25795447,556226623,89977298
34,Ohio,1508658985,660234134,287287,99164,2850770208,332789142,4359429193,993023276,1505426792,...,4511175641,1001512057,1688308308,719445753,250602,91210,2983024286,332988868,4671332594,1052434621
35,Oklahoma,524251783,209392653,88260,40585,764105353,143294453,1288357136,352687106,536320120,...,1497213049,366167856,666946565,281469697,87035,36248,889771571,109924142,1556718136,391393839
36,Oregon,421204801,476260495,83519,60770,1069729523,208716359,1490934324,684976854,456336626,...,1767569955,738957280,552284727,663245104,79833,48624,1268117594,133876809,1820402321,797121913
37,Pennsylvania,1191536050,412450009,251685,79979,3345838140,341933603,4537374190,754383612,1235638032,...,4589157182,709948567,1459344228,476960218,228789,60619,3017084420,253784744,4476428648,730744962
38,Rhode Island,133322312,59403822,22645,9333,240348658,53997972,373670970,113401794,133573647,...,440559011,119056521,187607409,73314567,21514,7679,299257353,55174415,486864762,128488982
39,South Carolina,566846085,364277502,109116,57624,1515781725,179957743,1955203208,524586004,634787323,...,2327463180,554926472,990575645,490364969,115616,59571,1589563244,249305574,2477617404,735647306
40,South Dakota,150142598,25983216,27006,5810,249382055,19193609,385113234,45176825,169542514,...,397533841,66964125,212194396,35922677,25390,5792,236325427,40211482,432648242,70221242
41,Tennessee,984083013,558263729,111635,72783,990395049,117052372,1931320662,674786101,1062138003,...,2388505688,769214410,1345850465,817911779,116213,63526,1230727576,32522273,2531862271,850009052
42,Texas,3351297068,3356493121,577131,471903,6056394038,940022889,9407691106,4296516010,3412177926,...,10303444621,4978668654,3784973375,4565525522,598674,445811,6714691050,923785553,10499664425,5489311075
43,Utah,781943425,229326889,102270,25832,723985904,73251211,1505929329,302578100,861529818,...,1907140736,376314509,1322465808,353517444,107356,26017,900340543,73412622,2222806351,426930066
44,Vermont,55157953,7945494,17806,2652,347319676,17998251,388296123,25943745,72460961,...,422917205,31799526,95458439,21944888,17368,2619,346594230,13291021,427849785,35235909
45,Virginia,1239774408,463489268,201878,100141,2221289749,378184627,3439045270,838524210,1543298911,...,4147606239,876046876,2120758201,686300652,205844,90626,2261190511,230187455,4358577233,913175612
46,Washington,979885049,867911611,112000,123981,1036970470,322948389,2016855519,1190860000,1076781748,...,2431805213,1379169160,1383608400,1293160399,96367,103022,1283267442,268695986,2666875842,1561856385
47,West Virginia,255066522,68309173,55501,11076,445541187,39613076,653276750,106156886,286050815,...,652044931,112389411,300444867,85033184,48686,9622,420029413,36317949,647862617,120759160
48,Wisconsin,707630934,795416572,137600,72054,1161149195,195823619,1868780129,991240191,729357600,...,2149278033,984602816,914698070,857385297,137493,61924,1401792235,151361620,2316490305,1008746917
49,Wyoming,200168188,182604336,10980,11214,50599000,28846480,249961369,211450816,203413238,...,247032929,197069710,243903433,157427397,9452,11035,38070972,44030669,281257320,201458066

In [192]:
for year in range(2019, 2025):
    for s in result['state']:
        result['fourYearAppropriationsPerFTE' + str(year)] = result['fourYearAppropriations' + str(year)] / result['fourYearNetFTE' + str(year)]
        result['twoYearAppropriationsPerFTE' + str(year)] = result['twoYearAppropriations' + str(year)] / result['twoYearNetFTE' + str(year)]

        result['fourYearNetTuitionRevenuePerFTE' + str(year)] = result['fourYearNetTuitionAndFeeRevenue' + str(year)] / result['fourYearNetFTE' + str(year)]
        result['twoYearNetTuitionRevenuePerFTE' + str(year)] = result['twoYearNetTuitionAndFeeRevenue' + str(year)] / result['twoYearNetFTE' + str(year)]

        result['fourYearTotalEducationRevenue' + str(year)] = result['fourYearTotalEducationRevenue' + str(year)] / result['fourYearNetFTE' + str(year)]
        result['twoYearTotalEducationRevenue' + str(year)] = result['twoYearTotalEducationRevenue' + str(year)] / result['twoYearNetFTE' + str(year)]

result

,state,fourYearAppropriations2019,twoYearAppropriations2019,fourYearNetFTE2019,twoYearNetFTE2019,fourYearNetTuitionAndFeeRevenue2019,twoYearNetTuitionAndFeeRevenue2019,fourYearTotalEducationRevenue2019,twoYearTotalEducationRevenue2019,fourYearAppropriations2020,...,fourYearNetTuitionRevenuePerFTE2022,twoYearNetTuitionRevenuePerFTE2022,fourYearAppropriationsPerFTE2023,twoYearAppropriationsPerFTE2023,fourYearNetTuitionRevenuePerFTE2023,twoYearNetTuitionRevenuePerFTE2023,fourYearAppropriationsPerFTE2024,twoYearAppropriationsPerFTE2024,fourYearNetTuitionRevenuePerFTE2024,twoYearNetTuitionRevenuePerFTE2024
0,Alabama,870474437,373978295,143485,59288,2202302684,281380200,0.0,0.0,934837520,...,16827.454861,5115.434951,10843.068670,17754.001630,16946.399535,4915.602647,9945.415185,11544.721430,17456.859345,5108.510169
1,Alaska,317936098,0,16721,0,95873240,0,0.0,NaN,294945498,...,6321.867122,NaN,24291.805300,NaN,6210.738965,NaN,24120.862583,NaN,5976.085462,NaN
2,Arizona,621655200,1011140300,182299,110557,2279943700,219173700,0.0,0.0,700784500,...,12159.572298,2045.546559,4582.305313,12384.238804,12709.558617,2125.463838,4316.179857,11293.922988,13635.667705,2241.103892
3,Arkansas,549066991,210661479,82311,30934,558577535,116421320,0.0,0.0,554366399,...,7282.525190,3955.121772,7394.071753,8568.791269,7915.223176,4027.962836,7303.299387,8384.027836,8678.802238,4197.567036
4,California,6987935555,9920625750,672687,918444,5427976052,704990279,0.0,0.0,7384224361,...,7165.025293,796.747432,13669.137001,14445.009353,7340.661324,812.989345,14394.882827,13381.421609,7321.454314,742.765354
5,Colorado,545568907,348106684,127744,56000,1838423316,248778463,0.0,0.0,606661026,...,16835.782151,3990.410495,6859.550513,6884.995050,17641.634551,3794.114192,7172.355490,8266.033987,17663.565203,4176.781981
6,Connecticut,656771926,274395936,57374,26419,922158033,173388994,0.0,0.0,675916335,...,16409.212943,6595.712137,20497.159490,23579.980701,16520.080424,6151.031116,18175.482003,18354.704303,15778.624989,6951.435185
7,Delaware,155842700,81266100,27524,8886,661616253,51949000,0.0,0.0,175041423,...,25455.438549,5601.656425,5982.647924,12608.964281,24597.205553,5788.884292,6116.984856,11984.048377,25543.157053,5349.005729
8,Florida,3264208503,1417043690,293179,315763,732426706,815454125,0.0,0.0,3378443061,...,2310.322854,2599.643714,12998.787527,6108.412325,2122.035444,2685.270089,15162.562179,6741.361708,2106.807560,2723.785949
9,Georgia,2398496689,521565902,269808,86540,1397005897,233486948,0.0,0.0,2547118266,...,5305.669418,2893.519284,12375.129768,8536.458905,5202.259452,2926.515505,11671.401766,7827.683343,4975.351519,2773.657711
10,Hawaii,374900906,216369518,20434,14820,175834578,50802743,0.0,0.0,366968512,...,9050.476871,3181.916048,21060.481246,21763.703219,8989.444477,3475.361422,20158.916421,19293.875950,8929.191719,3335.107510
11,Idaho,325709116,81353700,39610,14811,313196882,44776800,0.0,0.0,339125647,...,10125.881806,3014.628939,9596.002005,6673.256036,10094.387464,3003.104042,9726.866765,6790.867639,9935.430148,2951.370911
12,Illinois,3017467188,1606815523,166254,140713,1646732954,701083892,0.0,0.0,3187254988,...,10630.722523,6059.526731,22773.619199,18434.395089,10179.195469,5782.324386,24561.775063,20613.067023,10246.053827,5799.559639
13,Indiana,1130208640,328434443,182388,63913,2091043906,199967168,0.0,0.0,1114291880,...,13172.736201,2934.630081,6329.996678,5476.906027,13403.011583,2945.517588,6766.259339,5436.943204,13526.610224,3069.965589
14,Iowa,441297139,243092718,72148,57239,940858158,295577355,0.0,0.0,454574890,...,14034.786609,5349.078315,7096.399298,5712.386839,14631.278312,5489.983646,7060.366961,5861.444210,15122.514852,5724.151418
15,Kansas,439318624,422494288,79358,52895,748176878,143407789,0.0,0.0,462484573,...,8953.405022,2986.336744,7787.899154,11080.290956,9271.964913,2817.089526,8916.393832,11923.478906,10077.489999,2571.005862
16,Kentucky,677076000,228917300,98557,43446,997299484,175672455,0.0,0.0,690742100,...,10750.455789,4212.999233,9047.828056,6863.796336,10394.570387,4027.770714,9310.965407,6498.223091,10674.118151,3975.114377
17,Louisiana,694398663,143006506,120841,43091,666905944,155818967,0.0,0.0,690139603,...,5526.080788,4246.738204,6465.895975,4488.212476,6123.336482,3732.440497,6869.858572,4655.603686,5911.528141,3706.137356
18,Maine,190137977,77996303,24174,9773,216764719,30968136,0.0,0.0,198733750,...,9434.668416,2808.069344,10441.897685,11115.602917,9327.137906,1473.987034,11210.910919,9703.786538,9787.583311,1676.814385
19,Maryland,1311024223,804115016,139253,89990,1617504675,405437082,0.0,0.0,1440656580,...,11723.073439,4720.037301,13152.372507,13411.971294,11912.619565,4797.703929,14712.019347,13919.816920,11938.542516,4882.228550
20,Massachusetts,1130048154,407309591,110528,49799,884221811,193303325,0.0,0.0,1185419488,...,7762.837360,3703.824660,15683.123331,15259.629613,11832.653903,3765.191585,17907.352849,16706.949868,10908.404886,2771.654897
21,Michigan,1378192169,963809154,249978,116340,3994299546,626904274,0.0,0.0,1395929471,...,17358.900796,5045.193382,7213.204355,12585.987832,17949.685111,5435.379787,7275.017330,13840.377997,18406.192408,5428.344579
22,Minnesota,820634227,480882007,108148,76219,1290831123,368534372,0.0,0.0,867441081,...,13053.680871,5159.166528,9271.326065,8358.998406,13422.692078,5310.154815,10670.277142,9599.956043,13530.577851,5251.626827
23,Mississippi,387182397,298335003,71200,61799,620658969,222790779,0.0,0.0,407082330,...,9401.818055,4012.190929,7922.361032,6521.329931,9630.469415,4104.258379,7989.231236,6841.155364,10412.873967,4143.323516
24,Missouri,763826228,338671368,122734,59765,951715709,147642047,0.0,0.0,811736828,...,8284.328525,3269.508589,7143.713724,10343.203191,9002.205090,3583.339450,7441.157821,11380.125400,9617.269026,3832.943904
25,Montana,177825497,35256995,29697,6678,250076813,11128321,0.0,0.0,189459617,...,8961.773866,1641.879212,7532.250758,6344.519791,9599.876841,1590.088649,7714.305355,6556.563413,10098.162528,1671.568387
26,Nebraska,446717302,277420452,49798,26142,423471846,69543626,0.0,0.0,464311999,...,8570.369273,2579.084328,11024.182423,13880.860404,8588.535792,2546.900134,11630.408451,14172.305280,8730.348407,2463.987333
27,Nevada,439927542,182977139,47398,29026,152932193,53609076,0.0,0.0,466772726,...,3892.349457,1962.387787,9860.574083,8232.266624,3694.496659,2017.459852,12120.092107,9904.565855,3738.333643,2579.963131
28,New Hampshire,68585277,50493263,26500,9853,357236798,56411095,0.0,0.0,78230478,...,13652.800762,5717.689288,3563.736977,8325.146712,13727.329957,5701.190411,4089.121457,9774.683179,13562.544160,5834.065052
29,New Jersey,1412319000,463026000,165182,99904,1837231894,324942786,0.0,0.0,1709490759,...,11660.625748,3630.350042,11764.978042,6281.062673,11693.871499,3184.913650,13344.975296,6595.442626,10689.062646,2916.286090
30,New Mexico,578461834,359404918,39242,37798,149864116,67574708,0.0,0.0,688336556,...,7303.581436,1961.079254,22804.267814,13943.772727,4493.499964,1384.210579,18962.740391,13446.452696,4416.157797,1555.711556
31,New York,4548248299,1953533426,327088,210891,2323477548,915835486,0.0,0.0,4616273600,...,6927.139656,5179.209940,16246.539107,12762.622526,7803.286351,5396.065889,17816.884740,12332.138573,7600.863274,5419.474042
32,North Carolina,2368608880,1291226029,214263,179659,1546595373,298247489,0.0,0.0,2376700413,...,7182.089402,1605.678720,13460.526316,8530.516309,7256.341301,1563.062513,14332.155007,8540.902156,7538.410171,1517.816979
33,North Dakota,197780892,50404041,26753,7028,275201702,26181191,0.0,0.0,202954826,...,12371.421891,3920.639025,8319.248215,8192.400293,12545.827619,3740.725459,9599.368455,8692.016658,11766.844543,3493.424567
34,Ohio,1508658985,660234134,287287,99164,2850770208,332789142,0.0,0.0,1505426792,...,11086.264836,2838.500569,6448.096648,7069.309839,11625.813354,3000.388496,6737.010511,7887.794683,11903.433676,3650.793422
35,Oklahoma,524251783,209392653,88260,40585,764105353,143294453,0.0,0.0,536320120,...,10205.379449,3560.643421,6852.497629,7187.042348,10894.563309,3240.930996,7662.969667,7765.109716,10223.146677,3032.557438
36,Oregon,421204801,476260495,83519,60770,1069729523,208716359,0.0,0.0,456336626,...,15127.566299,3575.956492,7224.001914,12766.899837,15483.731321,3337.650234,6918.000413,13640.282659,15884.629088,2753.307194
37,Pennsylvania,1191536050,412450009,251685,79979,3345838140,341933603,0.0,0.0,1235638032,...,13311.849849,4223.857225,6738.651359,7804.851011,13203.367900,4187.726009,6378.559406,7868.163744,13187.191779,4186.554447
38,Rhode Island,133322312,59403822,22645,9333,240348658,53997972,0.0,0.0,133573647,...,13693.659107,6714.444767,7572.592950,9157.742659,13272.404022,7027.211256,8720.247699,9547.410731,13909.889049,7185.104180
39,South Carolina,566846085,364277502,109116,57624,1515781725,179957743,0.0,0.0,634787323,...,14028.597458,3194.736113,7078.918365,7003.534884,14632.613458,2591.426637,8567.807613,8231.605462,13748.644167,4185.015763
40,South Dakota,150142598,25983216,27006,5810,249382055,19193609,0.0,0.0,169542514,...,9414.006810,6779.592554,7308.694810,5625.847093,9344.666425,6734.515342,8357.400394,6202.119648,9307.815163,6942.590124
41,Tennessee,984083013,558263729,111635,72783,990395049,117052372,0.0,0.0,1062138003,...,9266.531177,622.348311,11729.828869,12533.625305,9315.801684,250.870135,11580.894263,12875.228710,10590.274548,511.952161
42,Texas,3351297068,3356493121,577131,471903,6056394038,940022889,0.0,0.0,3412177926,...,11852.683164,2236.540976,6313.850682,9755.189008,11350.267181,1996.377470,6322.261155,10240.944082,11215.938975,2072.146163
43,Utah,781943425,229326889,102270,25832,723985904,73251211,0.0,0.0,861529818,...,7897.688535,3380.297548,10216.723937,12278.620899,8027.490730,3039.888789,12318.508588,13587.940347,8386.494868,2821.717416
44,Vermont,55157953,7945494,17806,2652,347319676,17998251,0.0,0.0,72460961,...,19427.158954,4970.157915,5515.987958,5847.953622,19680.433971,6340.442698,5496.225184,8379.109584,19955.909143,5074.845743
45,Virginia,1239774408,463489268,201878,100141,2221289749,378184627,0.0,0.0,1543298911,...,11427.089283,3253.475305,9007.888387,7027.483298,11563.627570,3077.424267,10302.744802,7572.889149,10984.971682,2539.971476
46,Washington,979885049,867911611,112000,123981,1036970470,322948389,0.0,0.0,1076781748,...,11150.324357,2494.250671,12422.615296,11124.211657,12605.484011,2088.625545,14357.699212,12552.274262,13316.461465,2608.141814
47,West Virginia,255066522,68309173,55501,11076,445541187,39613076,0.0,0.0,286050815,...,8701.384390,3594.487956,6000.308116,9304.549336,8615.166124,3526.667197,6171.073142,8837.371025,8627.314074,3774.469861
48,Wisconsin,707630934,795416572,137600,72054,1161149195,195823619,0.0,0.0,729357600,...,9195.000792,2482.689991,6148.822223,14025.160304,9756.439621,2381.878672,6652.688282,13845.767344,10195.371655,2444.312706
49,Wyoming,200168188,182604336,10980,11214,50599000,28846480,0.0,0.0,203413238,...,3811.944615,3182.495330,21325.476683,13777.941343,4581.978775,3657.227196,25804.425836,14266.189126,4027.821837,3990.092343