In [2]:
import pandas as pd
import numpy as np
import openpyxl

In [2]:
df = pd.read_excel("sepehr_colleges.xlsx")
df

,index,UID,name,yearEstablished,state,stateAbbr,zip,locationType,locationTypeKind,Public/ Private,...,reasonEnrollment,reasonPandemic,reasonMutualBenefit,reasonForClosure,EndowmentMedian2023,EndowmentMedian2022,EndowmentMedian2021,EndowmentMedian2020,EndowmentMedian2019,EndowmentMedian2018
0,0,237118.0,Alderson Broaddus University,1871,West Virginia,NaN,26416,Rural,Distant,Private,...,0,0,0,Financial,NaN,16256321.0,18685108.0,18456342.0,17367369.0,18150386.0
1,1,194161.0,Alliance University (Formerly Nyack College),1882,New York,NaN,10004,City,Large,Private,...,0,0,0,Accreditation Issues,NaN,622193.0,3736796.0,4577611.0,4393633.0,4255808.0
2,2,241100.0,American University of Puerto Rico,1963,Puerto Rico,NaN,960,City,Midsize,Private,...,0,0,0,Financial,NaN,0.0,0.0,0.0,0.0,0.0
3,3,497833.0,Ancilla College,1937,Indiana,NaN,46513,Rural,Distant,Private,...,0,0,1,Mutual Benefit,NaN,0.0,0.0,4394680.0,4351295.0,4110469.0
4,4,164720.0,Becker College,1784,Massachusetts,NaN,1609,City,Midsize,Private,...,1,1,0,Pandemic; Enrollment,NaN,0.0,0.0,5024459.0,5116037.0,4962182.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,61,165644.0,Eastern Nazarene College,1900,Massachusetts,NaN,2170,Suburb,Large,Private,...,0,0,0,Financial,NaN,19100262.0,19431518.0,18753406.0,19545720.0,19548765.0
62,62,176770.0,Cox College,1907,Missouri,NaN,65802,City,Midsize,Private,...,0,0,0,Financial,NaN,0.0,0.0,0.0,0.0,0.0
63,63,240462.0,University of Wisconsin–Platteville Richland,1967,Wisconsin,NaN,53581,Town,Distant,Public,...,1,0,0,Enrollment,NaN,0.0,0.0,0.0,0.0,0.0
64,64,164085.0,Maryland University of Integrative Health,1974,Maryland,NaN,20723,Suburb,Large,Private,...,0,0,1,Mutual Benefit,NaN,NaN,NaN,NaN,NaN,NaN
65,65,NaN,B. H. Carroll Theological Seminary,2004,Texas,NaN,76010,City,Midsize,Private,...,0,0,1,Mutual Benefit,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
stateAbbri = {"Alabama": "AL",
             "Alaska": "AK",
             "Arizona": "AZ",
             "Arkansas": "AR",
             "California": "CA",
             "Colorado": "CO",
             "Connecticut": "CT",
             "Delaware": "DE",
             "Florida": "FL",
             "Georgia": "GA",
             "Hawaii": "HI",
             "Idaho": "ID",
             "Illinois": "IL",
             "Indiana": "IN",
             "Iowa": "IA",
             "Kansas": "KS",
             "Kentucky": "KY",
             "Louisiana": "LA",
             "Maine": "ME",
             "Maryland": "MD",
             "Massachusetts": "MA",
             "Michigan": "MI",
             "Minnesota": "MN",
             "Mississippi": "MS",
             "Missouri": "MO",
             "Montana": "MT",
             "Nebraska": "NE",
             "Nevada": "NV",
             "New Hampshire": "NH",
             "New Jersey": "NJ",
             "New Mexico": "NM",
             "New York": "NY",
             "North Carolina": "NC",
             "North Dakota": "ND",
             "Ohio": "OH",
             "Oklahoma": "OK",
             "Oregon": "OR",
             "Pennsylvania": "PA",
             "Rhode Island": "RI",
             "South Carolina": "SC",
             "South Dakota": "SD",
             "Tennessee": "TN",
             "Texas": "TX",
             "Utah": "UT",
             "Vermont": "VT",
             "Virginia": "VA",
             "Washington": "WA",
             "West Virginia": "WV",
             "Wisconsin": "WI",
             "Wyoming": "WY",   
             "District of Columbia": "DC",
             "American Samoa": "AS",
             "Guam": "GU",
             "Northern Mariana Islands": "MP",
             "Puerto Rico": "PR",
             "U.S. Virgin Islands": "VI",
             "Federated States of Micronesia": "FM",
             "Marshall Islands": "MH",
             "Palau": "PW",
             "Armed Forces Americas": "AA",
             "Armed Forces Europe": "AE",
             "Armed Forces Pacific": "AP",
             "Alberta": "AB",
             "British Columbia": "BC"}

df['stateAbbr'] = df['state'].map(stateAbbri)

In [11]:
for x in ['yearEstablished', 'zip', 'UID', 'index', 'totalEnrollment', 'mergingInstitutionPopulation', 'mergingInstitutionZip']:
    df[x] = pd.to_numeric(df[x], errors='coerce').astype('Int64')

for x in df.columns:
    if x.startswith('Endowment'):
        df[x] = pd.to_numeric(df[x], errors='coerce').astype('float')

In [ ]:
for x in ['mergingInstitution',
        #   'mergingInstitutionPopulation',
          'mergingInstitutionType',
        #   'mergingInstitutionZip',
          'mergingInstitutionLocationType',
          'mergingInstitutionReligiousAffiliation',
          'specialDemographic',
          'religionAffiliation']:
    df[x] = df[x].fillna("NA").astype(str)

,index,UID,name,yearEstablished,state,stateAbbr,zip,locationType,locationTypeKind,Public/ Private,...,reasonEnrollment,reasonPandemic,reasonMutualBenefit,reasonForClosure,EndowmentMedian2023,EndowmentMedian2022,EndowmentMedian2021,EndowmentMedian2020,EndowmentMedian2019,EndowmentMedian2018
0,0,237118,Alderson Broaddus University,1871,West Virginia,WV,26416,Rural,Distant,Private,...,0,0,0,Financial,NaN,16256321.0,18685108.0,18456342.0,17367369.0,18150386.0
1,1,194161,Alliance University (Formerly Nyack College),1882,New York,NY,10004,City,Large,Private,...,0,0,0,Accreditation Issues,NaN,622193.0,3736796.0,4577611.0,4393633.0,4255808.0
2,2,241100,American University of Puerto Rico,1963,Puerto Rico,PR,960,City,Midsize,Private,...,0,0,0,Financial,NaN,0.0,0.0,0.0,0.0,0.0
3,3,497833,Ancilla College,1937,Indiana,IN,46513,Rural,Distant,Private,...,0,0,1,Mutual Benefit,NaN,0.0,0.0,4394680.0,4351295.0,4110469.0
4,4,164720,Becker College,1784,Massachusetts,MA,1609,City,Midsize,Private,...,1,1,0,Pandemic; Enrollment,NaN,0.0,0.0,5024459.0,5116037.0,4962182.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,61,165644,Eastern Nazarene College,1900,Massachusetts,MA,2170,Suburb,Large,Private,...,0,0,0,Financial,NaN,19100262.0,19431518.0,18753406.0,19545720.0,19548765.0
62,62,176770,Cox College,1907,Missouri,MO,65802,City,Midsize,Private,...,0,0,0,Financial,NaN,0.0,0.0,0.0,0.0,0.0
63,63,240462,University of Wisconsin–Platteville Richland,1967,Wisconsin,WI,53581,Town,Distant,Public,...,1,0,0,Enrollment,NaN,0.0,0.0,0.0,0.0,0.0
64,64,164085,Maryland University of Integrative Health,1974,Maryland,MD,20723,Suburb,Large,Private,...,0,0,1,Mutual Benefit,NaN,NaN,NaN,NaN,NaN,NaN
65,65,<NA>,B. H. Carroll Theological Seminary,2004,Texas,TX,76010,City,Midsize,Private,...,0,0,1,Mutual Benefit,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
endow = pd.read_csv("sepehr_endowments.csv")

endow['hasMissing'] = endow['hasMissing'].replace({0: False, 1: True})

endow['index'] = endow['index'].astype('Int64')
endow['yearClosed'] = endow['yearClosed'].astype('Int64')

endow.loc[endow['hasMissing'] == True, endow.columns[1:]] = endow.loc[endow['hasMissing'] == True, endow.columns[1:]].infer_objects().replace(0, np.nan)

#drop row with no index
endow = endow.dropna(subset=['index'])

# if none of the columns that start with 'Endowment' have a value, then mark noData as True
endow['noData'] = endow[[x for x in endow.columns if x.startswith('Endowment')]].isnull().all(axis=1)

In [ ]:
endow
endow.to_csv("sepehr_endowments_cleaned.csv", index=False)

,index,yearClosed,EndowmentMedian2023,EndowmentMedian2022,EndowmentMedian2021,EndowmentMedian2020,EndowmentMedian2019,EndowmentMedian2018,hasMissing,noData
0,0,2023,0.0,16256321.0,18685108.0,18456342.0,17367369.0,18150386.0,False,False
1,1,2023,0.0,622193.0,3736796.0,4577611.0,4393633.0,4255808.0,False,False
2,2,2023,NaN,NaN,NaN,NaN,NaN,NaN,True,True
3,3,2021,0.0,0.0,0.0,4394680.0,4351295.0,4110469.0,False,False
4,4,2021,0.0,0.0,0.0,5024459.0,5116037.0,4962182.0,False,False
...,...,...,...,...,...,...,...,...,...,...
61,61,2024,NaN,19100262.0,19431518.0,18753406.0,19545720.0,19548765.0,True,False
62,62,2025,NaN,NaN,NaN,NaN,NaN,NaN,True,True
63,63,2024,NaN,NaN,NaN,NaN,NaN,NaN,True,True
64,64,2025,NaN,NaN,NaN,NaN,NaN,NaN,True,True
65,65,2025,NaN,NaN,NaN,NaN,NaN,NaN,True,True