In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from newspaper import Article
from newspaper import fulltext
import requests
from requests.exceptions import RequestException
import time

df = pd.read_excel('colleges_final/sepehr_colleges_links.xlsx')
df.drop(columns=['UID', 'state', 'yearClosed', 'yearEstablished', 'index'], inplace=True)
df.rename(columns={'links': 'article'}, inplace=True)
df

,name,article
0,Alderson Broaddus University,https://www.cnn.com/2023/08/02/us/west-virgini...
1,Alliance University (Formerly Nyack College),https://www.highereddive.com/news/alliance-uni...
2,Ancilla College,https://www.inkfreenews.com/2020/08/28/ancilla...
3,Becker College,https://apnews.com/general-news-f28092c26214a6...
4,Bloomfield College,https://www.nbcnewyork.com/news/good-news/smal...
...,...,...
60,Eastern Nazarene College,https://www.highereddive.com/news/eastern-naza...
61,Cox College,https://www.highereddive.com/news/cox-college-...
62,University of Wisconsin–Platteville Richland,https://www.highereddive.com/news/uw-plattevil...
63,Maryland University of Integrative Health,https://www.highereddive.com/news/notre-dame-o...
64,B. H. Carroll Theological Seminary,https://baptiststandard.com/news/texas/carroll...

In [ ]:
def extract_article_text(url):
    try:
        article = Article(url, language='en')
        article.download()
        article.parse()
        text = ' '.join(article.text.split())
        return text if text else "No content extracted"
    except RequestException as e:
        print(f"Error downloading {url}: {e}")
        return "Error: Failed to download"
    except Exception as e:
        print(f"Error parsing {url}: {e}")
        return "Error: Failed to parse"

# def extract_article_text(url):
#     try:
#         article = Article(url, language='en')
#         article.download()
#         article.parse()
#         text = ' '.join(article.text.split())
#         return text if text else "No content extracted"
#     except RequestException as e:
#         print(f"Error downloading {url}: {e}")
#         return "Error: Failed to download"
#     except Exception as e:
#         print(f"Error parsing {url}: {e}")
#         return "Error: Failed to parse"

df['content'] = ""

for index, row in df.iterrows():
    url = row['article']
    college = row['name']
    print(f"Processing {college}...")
    text = extract_article_text(url)
    df.at[index, 'content'] = text
    time.sleep(1)

Processing Alderson Broaddus University...
Processing Alliance University (Formerly Nyack College)...
Processing Ancilla College...
Processing Becker College...
Processing Bloomfield College...
Processing Bluffton University ...
Processing Cabrini University...
Processing Cardinal Stritch University...
Processing Cazenovia College...
Processing Chatfield College...
Processing Compass College of Film and Media...
Processing Concordia College...
Processing Finlandia University...
Processing Fontbonne University...
Processing Hodges University...
Processing Holy Family College...
Processing Holy Names University...
Processing Independence University...
Processing Indiana University-Purdue University Indianapolis...
Processing Iowa Wesleyan University...
Processing Johnson University Florida...
Processing Judson College...
Processing Lincoln Christian University...
Processing Lincoln College...
Processing MacMurray College...
Processing Magdalen College of the Liberal Arts...
Processing Marlboro College...
Processing Martin Methodist College (UT Southern)...
Processing Marymount California University...
Processing Medaille University...
Processing Mills College...
Processing Multnomah University...
Processing Nebraska Christian College...
Processing Notre Dame College...
Processing Ohio Valley University...
Processing Pacific Northwest College of Art...
Processing Pennsylvania College of Health Sciences...
Processing Pine Manor College...
Processing Presentation College...
Processing Presidio Graduate School...
Processing Salus University...
Processing San Francisco Art Institute...
Processing Sierra Nevada University...
Processing St. Augustine College...
Processing St. John's University -- Staten Island...
Processing St. Louis Christian College...
Processing The College of Saint Rose...
Processing University of the Sciences...
Processing Urbana University...
Processing UW Oshkosh - Fond du Lac Campus...
Processing UW Green Bay - Marinette Campus...
Processing UW Milwaukee - Waukesha Campus...
Processing UW Milwaukee - Washington Campus...
Processing Wave Leadership College...
Processing Wesley College...
Processing Woodbury University...
Error parsing https://www.axios.com/local/san-diego/2024/05/01/urban-development-trendsetter-woodbury-school-architecture-closing: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.axios.com/local/san-diego/2024/05/01/urban-development-trendsetter-woodbury-school-architecture-closing on URL https://www.axios.com/local/san-diego/2024/05/01/urban-development-trendsetter-woodbury-school-architecture-closing
Processing Oak Point University...
Processing Birmingham-Southern College...
Processing Tulsa Community College at Owasso...
Processing Wells College...
Processing Eastern Nazarene College...
Processing Cox College...
Processing University of Wisconsin–Platteville Richland...
Processing Maryland University of Integrative Health...
Processing B. H. Carroll Theological Seminary...

In [ ]:
df.loc[df['name'] == 'Tulsa Community College at Owasso', 'content'] = "OWASSO, Okla. — Tulsa Community College (TCC) announced they will be no longer offering classes at its Owasso Community Campus following the end of the spring 2024 semester TCC said the decision was made due to several factors including enrollment patterns and course offerings. TCC leased the space at the Owasso Campus from Tulsa Tech. Tulsa Tech said its Owasso Campus and Conference Center will remain open and continue to provide Tulsa Tech classes. The full statement from TCC can be seen below: “After careful deliberation, Tulsa Community College has made the challenging decision to discontinue course offerings on the Owasso Community Campus beginning with the Summer 2024 semester. This decision is based on an evaluation of several factors, including enrollment patterns, operational effectiveness, course offerings, and alignment with our long-term strategic goals. We believe that reorganizing our resources will enable us to better serve our students and the community. TCC will continue to serve students from the Owasso area through our dual credit and online offerings, and the Northeast Campus is less than 20 minutes from the Owasso Community Campus."
df.loc[df['name'] == 'Woodbury University', 'content'] = "The San Diego outpost of the Woodbury School of Architecture will close permanently at the end of this semester. Why it matters: Faculty and alumni built notable projects and influenced development across urban San Diego over the school's 26-year run. Driving the news: Los Angeles-based Woodbury University this year announced a merger with the University of Redlands that includes shutting down the San Diego campus that opened in 1998. Catherine Herbst, chair of the Barrio Logan school, said the university started winding down operations three years ago, letting students and faculty transfer to the LA campus in preparation for this spring's formal end, once the last 11 students finish. By the numbers: Since its first class graduated in 2001, the school has turned out nearly 500 students from its bachelor's of architecture program. It issued 170 graduate degrees and minted 74 state-licensed architects. The intrigue: Woodbury was especially influential because of its master's in real estate development (MRED) program, which gained notoriety by creating a model that taught architects to pursue their own projects rather than work for others. Typically, developers make decisions about how a project should look and feel based on financial and zoning constraints, and then hire architects to execute those needs. Alumni and faculty from the MRED program instead are in charge of the entire project, and their architectural decision making dictates the end result. What they're saying: 'The program was a critique of the way we build buildings in the United States,' said Andrew Malick, an MRED graduate who has become a prolific developer around the region. 'Our critique was, when an architect empowered in the business of development makes decisions, better buildings and better lifestyles are the result,' he said. Between the lines: Buildings from Woodbury-affiliated architects are linked by 'an approach, not an aesthetic,' said Tyler Hanson, a graduate and professor who has built projects in Golden Hill, North Park and Azalea Park. Woodbury architect-developers pursued small or odd lots in vibrant neighborhoods, while institutional developers chased simple, big projects downtown or on the outskirts of the city. They mastered zoning laws to maximize what they could build without triggering community hearings or approvals. '[Faculty member Ted Smith] calls it civil disobedience — I just call it being smart,' Herbst said. 'Navigating zoning and procedural democracy is something we all get really good at.' The other side: The freedom Woodbury architects celebrate has also riled residents, especially over the lack of parking for many projects. The big picture: For a decade, city leaders have slashed parking mandates, increased allowed housing density and removed development restrictions — all part of Woodbury's legacy, Malick says. 'The shadow of the MRED program is a re-envisioning of how we develop infill neighborhoods,' he said. Yes, but: Those reforms — especially Complete Communities, which dramatically slashed development restrictions — eventually enticed institutional players into those neighborhoods, diminishing small developers' competitive edge. What's next: Relaxed rules on building multiunit projects on single-family lots are creating new advantages for architects and developers, Hanson said."

In [21]:
df

,name,article,content
0,Alderson Broaddus University,https://www.cnn.com/2023/08/02/us/west-virgini...,C N N — \n \n A s m a l l W e s t V i ...
1,Alliance University (Formerly Nyack College),https://www.highereddive.com/news/alliance-uni...,"A l l i a n c e U n i v e r s i t y , a ..."
2,Ancilla College,https://www.inkfreenews.com/2020/08/28/ancilla...,N e w s R e l e a s e \n \n I N D I A N A P ...
3,Becker College,https://apnews.com/general-news-f28092c26214a6...,"W O R C E S T E R , M a s s . ( A P ) — ..."
4,Bloomfield College,https://www.nbcnewyork.com/news/good-news/smal...,A n u n o r t h o d o x p a r t n e r s h ...
...,...,...,...
60,Eastern Nazarene College,https://www.highereddive.com/news/eastern-naza...,L i s t e n t o t h e a r t i c l e 4 ...
61,Cox College,https://www.highereddive.com/news/cox-college-...,L i s t e n t o t h e a r t i c l e 3 ...
62,University of Wisconsin–Platteville Richland,https://www.highereddive.com/news/uw-plattevil...,L i s t e n t o t h e a r t i c l e 5 ...
63,Maryland University of Integrative Health,https://www.highereddive.com/news/notre-dame-o...,L i s t e n t o t h e a r t i c l e 4 ...
64,B. H. Carroll Theological Seminary,https://baptiststandard.com/news/texas/carroll...,T o “ e l i m i n a t e r e d u n d a n c ...

In [17]:
df.to_csv("test_links.csv", index=False)